### ISSUE TITLE
Info about the entry in package.json for which the corresponding dependency's warnings are shown while installing packages

### ISSUE THREAD

**Issue by SafNaaz** [nodejs/security-wg#1041]
It would be really great for developers to understand, where to look at when the entry in package.json also is printed along with the warn.

eg: one warn is shown during install that some package is deprecated. it might be a dependency of another package mentioned in package.json.

for finding for which package, that warn was shown is very time consuming.

just an info of the main entry in package.json along with warn will help a lot.

![image](https://github.com/nodejs/security-wg/assets/9652574/ae498363-4d5c-4a37-a6fe-2e6307166844)

**Comment by RafaelGSS** [comment]
This is the npm cli output. There's nothing to do with Node.js. You might want to report it on the: https://github.com/npm/cli
