### ISSUE TITLE
Can I use --experimental-permission in new worker_threads.Worder's execArgv?

### ISSUE THREAD

**Issue by LongTengDao** [nodejs/security-wg#1043]
The doc said that's "process-based permission". But it's actually based on execArgv, does it mean that, it can also be used for create worker by design (and "process-based" is a only provisional loose wording used to emphasize the difference from "module-based")?

**Comment by RafaelGSS** [comment]
What do you mean by execArgv? If you want to create a worker when using the permission model, you should ensure to pass `--experimental-permission` + all the permissions the worker needs. We don't do it by default, it's up to the developer.

**Comment by LongTengDao** [comment]
So actually `--experimental-permission` is not a "process-based permission", but "thread-based permission"?

**Comment by RafaelGSS** [comment]
You can call main thread-based permission, yeah.

**Comment by RafaelGSS** [comment]
What's your use case?

**Comment by LongTengDao** [comment]
>   You can call main thread-based permission, yeah.

What about other threads?

>   What's your use case?

Thank you for your attentive.

I'm making a sandbox util to run test pure code and keep them away from disk.

There are many codes to run, so if I can use `new worker_threads.Worker` 100 times instead of `child_process.fork` 100 times, the cost will be less.

Currently, my code looks like sample 1 because the docs said it's "process-based permission":

```js
function fn (id) {
    return child_process.fork(`/path/to/${id}.js`, [], {
        execArgv: [ '--experimental-permission', '--allow-fs-read=/path/to/${id}.js' ]
    });
}
```

And if actually it's "thread-based permission", I want to make it looking like sample 2:

```js
function fn (id) {
    return worker_threads.Worker(`/path/to/${id}.js`, {
        execArgv: [ '--experimental-permission', '--allow-fs-read=/path/to/${id}.js' ]
    });
}
```
