### ISSUE TITLE
License checker process/script

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/security-wg#1104]
Recently, we had some concerns regarding licenses for the Node.js sub-dependencies, and there was a suggestion on https://github.com/nodejs/node/issues/49625 to include a script that validates the licenses for the Node.js dependencies.

As an initial kick-off, we had this comment on https://github.com/nodejs/node/issues/49625#issuecomment-1715734234.

This will require a good discussion within the team, but overall potential objectives (from https://github.com/nodejs/security-wg/issues/1100) are:
- Include a script/GH Action that consolidates the project dependencies and stores them.
- Trigger an alert (issue/PR) if there are changes in the licenses (sub-dependency added/removed, relicensed).
- Create documentation on how to review these changes and what the criteria are to accept/reject them.

**Comment by fasenderos** [comment]
I would like to take this one. 
Just to make sure I understand it correctly, when you say `consolidates the project dependencies and stores them`, you mean to save all the licenses in a separate file and checking against that file, or check the package LICENSE with the one already stored in repo?

**Comment by RikValens1988** [comment]
Thanks you ulises

**Comment by fraxken** [comment]
Interested to join on this as that something I'm working on for NodeSecure.

Spent quite few hours around license detection (and others) for [NodeSecure/scanner](https://github.com/NodeSecure/scanner). Most solution in the ecosystem doesn't detect much licenses compared what available in SPDX :\

**Comment by RafaelGSS** [comment]
Reference: https://github.com/nodejs/node/blob/main/.github/workflows/license-builder.yml

**Comment by richardlau** [comment]
> Reference: https://github.com/nodejs/node/blob/main/.github/workflows/license-builder.yml

This merely rebuilds the main Node.js license based on what was manually added to [`tools/license-builder.sh`](https://github.com/nodejs/node/blob/main/tools/license-builder.sh) -- i.e. it checks for consistency. It doesn't check the type of license or any sub-dependencies. For https://github.com/nodejs/node/issues/49625 npm's main license was unchanged but the license of one of its dependencies changed.

**Comment by pombredanne** [comment]
@fraxken you wrote: https://github.com/nodejs/security-wg/issues/1104#issuecomment-1739364753

> I'm interested in joining because that's something I'm working on for NodeSecure.
> 
> I spent quite few hours on license detection (and others) for [NodeSecure/scanner](https://github.com/NodeSecure/scanner). Most solution in the ecosystem doesn't detect much licenses compared what available in SPDX :\

If you want to give the node and its deps and embedded code a good license scrub, you may want to check out scancode-toolkit (or scancode.io) which is considered the leading FOSS tool in space. If there is any license or copyright not detected correctly, this is a bug. And we fix bugs. Also does SBOMs.
