### ISSUE TITLE
Evangelism and Communication

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#111]
Hello,

Here are the current evangelism initiatives for this WG:
* Recommended text and template for 3rd party module authors (#93)
* Starting to blog regarding our work

Suggested initiatives
* Updating README.md with more insides about what we are up to (by @bnb )

(Please feel free to edit this message with new topics or topics I might have missed)

**Comment by lirantal** [comment]
I have a couple of draft articles on the general Node.js security ecosystem that we've been up to recently, but writing on the WG work would be amazing.

Also, I started doodling an abstract about the WG that I want to send out to some confs with CFPs still open for this year, and will probably talk in local meetups on this too.

I know Kim from seradio podcast and will reach out to him to see if he wants to feature us on one of his episodes. Will also try to get a few more ideas out for evangelism activities and update here.

**Comment by mhdawson** [comment]
@lirantal good suggestions.  A talk from the security wg at Node Interactive and some of the other Node.js conferences (in addition to any others) would be great.  I'd be interested in collaborating on that if it makes sense to you.

**Comment by vdeturckheim** [comment]
+1 here. 

@lirantal @mhdawson I'm also pretty interested in collaborating on that. I think next major Node.js CFP would be Node Summit and CFP is already open (http://www.nodesummit.com/speakers/become-a-speaker/). Do you want to sync up on an abstract together?

**Comment by mhdawson** [comment]
Sounds good to me.  I'd suggest that we submit both a talk and a panel session as 2 options for the conference to consider.   For the panel we'd need to figure out who else it would make sense to have included.

**Comment by vdeturckheim** [comment]
Great! I'll write a few abstracts this week/weekend.

Regarding panels, I think we can submit the idea and iterate with the conference team.

**Comment by lirantal** [comment]
Great, glad to have you onboard :-)
@vdeturckheim maybe you can send out a hangout invite for us to quickly sync?

**Comment by vdeturckheim** [comment]
Let's schedule a call to prepare a CFP strategy next week.

**Comment by cjihrig** [comment]
@vdeturckheim did the CFP strategy call ever happen? Also, this has been on the WG meeting agenda since January 26th. Does it need to remain labeled as such?

**Comment by vdeturckheim** [comment]
We had a call with @mhdawson and @lirantal. I think we are safe to remove it from agenda.

**Comment by dgonzalez** [comment]
Are we happy if my company organises a webinar with our work in the third party triage team? If we are happy with it I can get it done in two weeks.

**Comment by dgonzalez** [comment]
We can choose that. I'd say an online round table where we have few questions prepared and the audience can ask more questions as we go would be amazing. People needs to know how hard is to keep the ecosystem safe.

**Comment by lirantal** [comment]
Yep, that will be nice.
Between me, @vdeturckheim, and @mhdawson already kick-started brainstorming some evangelism options so I'm happy to see more of this happening.

**Comment by mhdawson** [comment]
+1 from me.

**Comment by sam-github** [comment]
This appears to be either stalled, or more likely sucessfully occuring through other more specific issues. I'm closing, but if I misunderstand please reopen it.
