### ISSUE TITLE
[grace-hopper-day] Add wildcard mention to permission.has API doc

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#1112]
The Node.js Permission Model supports wildcard (`*`) in the `permission.has` API. We should update the documentation to mention this feature as well - https://github.com/nodejs/node/blob/e9ff81016dfcf183f4fcc2640497cb8b3365fdd7/doc/api/permissions.md?plain=1#L514.

Example: https://github.com/nodejs/node/blob/e9ff81016dfcf183f4fcc2640497cb8b3365fdd7/doc/api/permissions.md?plain=1#L554

**Comment by tniessen** [comment]
(On a side note, is that intended? What if the file path actually contains an asterisk?)

**Comment by RafaelGSS** [comment]
Yes, that was initially intended. I've created another issue to handle the paths with `*` (https://github.com/nodejs/security-wg/issues/1116).

For now, we can document the existing behaviour and when we fix/change it, we'll adjust in the `process.permission.has` as well.
