### ISSUE TITLE
Handling `*` paths in --allow-fs-* flags

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#1116]
Currently, the `*` char in `--allow-fs-read` or `--allow-fs-write` makes use of a _wildcard_ pattern. Consider the following list:

* `--allow-fs-read=/tmp/*` - allows read access to all files and folders under `/tmp/`.
* `--allow-fs-read=/tm*` - allows read access to all files and folders starting with `/tm*` i.e. /tm2.txt or /tmp/file.txt

While this might save quite some time when using the permission model, `*` is a valid path character and we should be able to handle it, in this case, ignoring the wildcard approach.

**Comment by tniessen** [comment]
The same probably applies to `process.permission.has()`.

**Comment by RafaelGSS** [comment]
I will leave this issue open, but, I have a feeling the trade-off of removing wildcards to handle specific cases where the file path contains the "*" is not worth it. So, I have stopped the work on this.
