### ISSUE TITLE
NodeJS Code integrity on Windows

### ISSUE THREAD

**Issue by rdw-msft** [nodejs/security-wg#1149]
Hey all,

Earlier this year I spoke about integrating NodeJS with Window's code integrity system. I've created a [PR demonstrating the changes we're proposing](https://github.com/nodejs/node/pull/50644). 

Could we get on the schedule for the next security working group meeting to discuss these changes?

Thanks,
Robert

**Comment by RafaelGSS** [comment]
Sure! Adding it to the agenda.
