### ISSUE TITLE
Does .wasm module under --experimental-pemission protect?

### ISSUE THREAD

**Issue by LongTengDao** [nodejs/security-wg#1168]
`.node` file is native and can't support under `--experimental-permission`, if I understand correctly.

What's the fundamental difference between `.wasm` and `.node`?

Does it safe if I enable both `--experimental-pemission` and `--experimental-wasm-modules`? Will `.wasm` module be limited run by `--experimental-pemission` exactly same as `.mjs`?

And what about `--experimental-wasi-unstable-preview1` (wasi)?

Thanks

**Comment by RafaelGSS** [comment]
`wasm` modules won't be limited by the permission model

**Comment by LongTengDao** [comment]
Is it not possible for `.wasm`, just like `.node`?

Or just currently not limit, and will do that in the future?

@RafaelGSS

**Comment by LongTengDao** [comment]
(Why can wasm bypass it? I remember wasm is module without side effects, without dom or io access ability, and the imports inside also need be apply by the `WebAssembly.instantiate()` explicitly. Thank you!)
