### ISSUE TITLE
zoom link does not appear on the calendar

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/security-wg#1202]
Unlike other meetings on the node calendar the security wg doesnt include the zoom link.
I think it would make much easier to have it in the event description
<img width="457" alt="Screenshot 2024-01-18 at 16 01 38" src="https://github.com/nodejs/security-wg/assets/36735501/2d4860a0-6555-464c-af56-4878d4c88b15">
Other meetings:
<img width="455" alt="Screenshot 2024-01-18 at 16 02 52" src="https://github.com/nodejs/security-wg/assets/36735501/239820d7-929b-4943-96f4-5548987f6c9e">

**Comment by mhdawson** [comment]
ok, added to calendar.
