### ISSUE TITLE
regarding installation of node

### ISSUE THREAD

**Issue by sk670994** [nodejs/security-wg#1218]
I downloaded the node msi file many times and tried to install and uninstall of node.tried everything manually adding path in environmental variables  but still its showing 
Microsoft Windows [Version 10.0.19045.3930]
(c) Microsoft Corporation. All rights reserved.

C:\Users\admin>node
'nod' is not recognized as an internal or external command,
operable program or batch file.
and also in vs code  its showing
PS D:\coding_ninjas\WEB DEVP\Javascript\Toggle Mode> node --version
node : The term 'node' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if 
a path was included, verify that the path is correct and try again.
At line:1 char:1
+ node --version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (node:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

kindly let me know what should i do and install node and nom correctly and why isnt installing in my laptop

**Comment by marco-ippolito** [comment]
Hi @sk670994 this is not the right repository.
Please open a discussion on nodejs/help https://github.com/nodejs/help
I'm not windows expert but
I think you should add `C:\Program Files\nodejs` to your `PATH` environment variable.
