### ISSUE TITLE
February 6 2024 Security Releases not announced to nodejs-sec

### ISSUE THREAD

**Issue by Yogu** [nodejs/security-wg#1224]
There is a [blog post to announce that there will be security releases today](https://nodejs.org/en/blog/vulnerability/february-2024-security-releases). In the past, these blog posts were accompanied by mails to the [nodejs-sec mailing list](https://groups.google.com/g/nodejs-sec) like [this](https://groups.google.com/g/nodejs-sec/c/mA_w780u1zw):

> The Node.js project will release new versions of all supported release lines on or shortly after Tuesday, August 8th, 2023.
> 
> For more information see: https://nodejs.org/en/blog/vulnerability/august-2023-security-releases/

This has not been the case for the February 6 2024 Security Releases.

Is the mailing list still used?

**Comment by RafaelGSS** [comment]
Hi @Yogu! Yes, this is still used, we have just missed it. @mcollina could you please send it to me? I'm having trouble with the new email address.

**Comment by mhdawson** [comment]
I posted an update today.

**Comment by mhdawson** [comment]
There were a few factors that led to it being missed this time, but it is part of our standard release process and will continue to be.

Closing as answer, please let us know if that was not the right thing to do.
