### ISSUE TITLE
Missing PGP key

### ISSUE THREAD

**Issue by BridgeAR** [nodejs/security-wg#123]
I just realized that there is no regular way to report a security issue in a safe way since there is no PGP key for `security@nodejs.org`. Using plain text to report a security issue is a no go. E-Mails are always unsafe in their nature when not used with PGP.

This is really a bad sign out of my perspective that a "secure" way is actually not secure at all...
Please fix that ASAP and also update https://nodejs.org/en/security/.

**Comment by jasnell** [comment]
This would definitely be a good thing to get set up. It's been needed for some time.

**Comment by mhdawson** [comment]
Does sound like something we should do.  Will investigate next week once I'm back from Index unless somebody beats me to it.

**Comment by reedloden** [comment]
Won't the move to HackerOne (i.e., web form over TLS) make this unneeded?

**Comment by lirantal** [comment]
some people will just prefer e-mail so I think it makes sense to support this.

**Comment by reedloden** [comment]
Speaking as somebody who personally dealt with a security@ inbox with PGP encrypted mails for years at one of my previous employers, it's a nightmare. PGP is now 27 years old, and in 2018, it is still just as bad from a UX-perspective as when it was created. I highly recommend that you do not support it, if at all possible.

Note that HackerOne supports [e-mail forwarding](https://support.hackerone.com/hc/en-us/articles/218142843), which is already being used for security-ecosystem@nodejs.org. Inbound mails are saved as drafts, and the submitter finishes his/her submission via the web interface.

**Comment by BridgeAR** [comment]
PGP is not ideal and there is a huge need for something better that everyone is able to deal with but as soon as it is once introduced, there is no big overhead anymore. I for example have very good experience with tools that automatically do (almost) everything for you.

**Comment by reedloden** [comment]
@BridgeAR I don't agree that the overhead goes down when implemented. Are you trying to manage the use of a single PGP key among multiple users? What happens when somebody leaves the team? How do you securely transmit the private key to others? So much overhead that lasts a long time.

**Comment by BridgeAR** [comment]
There is a super simple solution to this: a ticket system. That is how I dealt with these things before in quite a big scale. That way the system should already handle the encryption and decryption and adding the key etc. and users can just be onboarded / be removed easily again.

**Comment by DanielRuf** [comment]
Bump. Also Hashicorp Vault and other solutions can be used probably.

**Comment by reedloden** [comment]
Why is a PGP key needed? Shouldn’t this just be closed out?

**Comment by DanielRuf** [comment]
> Why is a PGP key needed?

I think your opinion is a bit biased based on your profile.
Still many security rersearchers use PGP to encrypt and send reports and this is also recommended by ISO/IEC 29147:2018 and OWASP.

I for example exchange infos with police and authorities solely using PGP and report issues using the same solutions. Emails are otherwise stored unencrypted and sent through the network (you can not always ensure that the network is safe / secure).

**Comment by mcollina** [comment]
I think this should be closed.

**Comment by lirantal** [comment]
I assume we can agree that our e-mail reporting mechanism at the moment is not considered a safe medium to report vulnerabilities. If that's the case then we either:
1. remove the e-mail option completely to mitigate potential security risks when disclosing sensitive information over e-mail, and direct everyone straight to H1 (which we can agree is a safe platform and medium to report on)
2. keep the e-mail option and figure out a maintainble way to send sensitive data on

a workaround to keep the e-mail option is that we explicitly say on the website that e-mails to the security@nodejs.org address should refrain from containing sensitive data.

**Comment by mhdawson** [comment]
One question that comes to mind is if we make it too hard to report will we get less reports? Is it better to have no report or one through email that might not be perfectly security.  We can highly recommend people use H1, and make it clear that using e-mail has risks disclosure but is it worth potentially missing reports by removing email as an option?

**Comment by lirantal** [comment]
@mhdawson I like your suggestion of making it clearer in the docs that the e-mail medium doesn't yet work with security keys and shouldn't be regarded as a secure medium to send sensitive data and that we recommend H1 as an alternative.

**Comment by sam-github** [comment]
Will be fixed by https://github.com/nodejs/nodejs.org/pull/2179

**Comment by fraxken** [comment]
Seems fixed to me, closing as there is no message since 2018-2019.
