### ISSUE TITLE
Read time outs in "Check for vulnerabilities daily" workflow

### ISSUE THREAD

**Issue by richardlau** [nodejs/security-wg#1243]
Probably because I was the last person to change the workflow, but I'm getting notifications for https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/workflows/daily.yml. The current ones are showing an increasing frequency of 503 read errors to services.nvd.nist.gov.

e.g. today's run passed for `main` but failed for v21.x, v20.x and v18.x: https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/8088837451
while yesterday's run failed everywhere: https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/8073093213

**Comment by RafaelGSS** [comment]
I think that's now fixed, right? https://github.com/nodejs/nodejs-dependency-vuln-assessments/actions/runs/9313213229

The failed checks means it found a vuln (there's a `continue-on-error` in the workflow)
