### ISSUE TITLE
Node.js Security Initiatives 2024

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#1255]
Hey!

Since May 2023 the Security team has been working on the following initiatives:

* Permission Model (2 Phase) - (Done)
* Automate update dependencies (Done)
* Assessment against best practices (Done)
* Automate Security release process (In progress)

As always, I want to express my gratitude to everyone who contributed to our latest project. The work was exceptional. During today's meeting (#1245), we discussed the need to explore new initiatives to enhance the Node.js security ecosystem. Therefore, I would like to use this issue as a forum for brainstorming and sharing ideas. Please feel free to share any problems you've encountered and any potential solutions you may have. Even if you don't have a solution in mind, please share the problem anyway. All input is welcome. This thread will be reviewed and discussed through the Node.js Security team meetings (feel free to join).

@nodejs/security-wg

**Comment by marco-ippolito** [comment]
I think SBOM should be an initiative for this year

**Comment by mhdawson** [comment]
I think we should make the work to audit the build processes of the dependencies an initiative for 2024. It both aligns well with the emphasis on supply chain security and should also help the project to limit the risk of issues during security release.

**Comment by mhdawson** [comment]
Proposal from discussion in the meeting today for 2024

* Permission Model (2 Phase) 
* Assessment against best practices
* Automate Security release process
* Including SBOMs with Node.js 
* Audit and improving the build processes of Node.js dependencies

**Comment by UlisesGascon** [comment]
Given the recent discussions around the xz incident, I suggest including a new initiative dedicated to mitigating potential threats originating from similar vectors within the organization. 

As an outcome of this initiative, I propose to:
- Evaluate the current situation of the project regarding this scenario.
- Prepare a list of potential changes to increase our resilience against this kind of threat.
- Share our learnings openly so that other projects within the OpenJS Foundation and outside can benefit from them.

**Comment by RafaelGSS** [comment]
We currently have two experimental security features: the Permission Model and the Policy mechanism. Although the Permission Model is still in development, the Policy mechanism requires further research to determine its next steps. Therefore, I suggest that we focus on improving the Policy mechanism as one of our initiatives for 2024.

**Comment by RafaelGSS** [comment]
Discuss the impact of our CI machines and attack vectors

**Comment by RafaelGSS** [comment]
Code Integrity feature for Node.js. @rdw-msft can you provide more details on this?

**Comment by RafaelGSS** [comment]
Include a "Defense in Depths" policy to Node.js Threat Model.

@mhdawson @rdw-msft can you include some context here? (Feel free to edit this comment)

**Comment by RafaelGSS** [comment]
https://github.com/nodejs/security-wg/issues/1282

**Comment by GeoffreyBooth** [comment]
> Code Integrity feature for Node.js.

Regarding this, there’s a WIP PR for import maps: https://github.com/nodejs/node/issues/49443. Import maps could be used as a place to store the subresource integrity hashes for modules: https://github.com/guybedford/import-maps-extensions#integrity. This would require some coordination with standards bodies such as WICG and WinterCG. cc @guybedford

**Comment by RafaelGSS** [comment]
https://github.com/nodejs/security-wg/issues/898#issuecomment-2083534350

**Comment by rdw-msft** [comment]
> Include a "Defense in Depths" policy to Node.js Threat Model.
> 
> @mhdawson @rdw-msft can you include some context here? (Feel free to edit this comment)

Here's the document we use to differentiate between "defense in depth" and "security boundary" features: https://www.microsoft.com/en-us/msrc/windows-security-servicing-criteria

**Comment by RafaelGSS** [comment]
Improve CII Best Practices and reach silver badge.

**Comment by RafaelGSS** [comment]
Defining scopes of the Security team

**Comment by RafaelGSS** [comment]
Selected Initiatives for 2024:

* 1) Automate Security release process - Champion: @RafaelGSS / @marco-ippolito
* 2) Node.js maintainers: Threat Model - Champion: @nodejs/security-wg
* 4) Audit build process for dependencies - Champion: @mhdawson 

Please note we have skipped item 3 (SBOM) as we don't have a volunteer for that. If you are interested in moving forward with this initiative, join us. 

Refs: https://github.com/nodejs/security-wg/pull/1319

**Comment by Md00772244** [comment]
![Screenshot_۲۰۲۴۰۶۲۴_۱۶۳۱۱۱_Outlook](https://github.com/nodejs/security-wg/assets/174484946/7e811295-db4e-4b46-ac1c-e608416c9c0f)
![Screenshot_۲۰۲۴۰۶۲۴_۱۶۵۶۴۱_Samsung Internet](https://github.com/nodejs/security-wg/assets/174484946/1509f435-7e92-472b-a8e6-28515dd1e466)
![Screenshot_۲۰۲۴۰۶۲۴_۱۴۰۳۲۱_Samsung Internet](https://github.com/nodejs/security-wg/assets/174484946/e4c6edc9-615f-4b9e-8c39-42887fc1a744)
![-6323463075998579925_121](https://github.com/nodejs/security-wg/assets/174484946/5468f26b-3581-4da3-86e0-e14e7e723cf2)
