### ISSUE TITLE
More control over remote debugging (and killing)

### ISSUE THREAD

**Issue by RedYetiDev** [nodejs/security-wg#1287]
(Ref: https://hackerone.com/reports/2469806)

I think the permissions policy should also provide a way to disable the use of `process._debugProcess(<PID>)` and `process.kill(<PID>)`, so that 'restricted' processes can't escape their restrictions via the debugging of a separate process.

Additionally, a process should be allowed to disable remote debugging.

**Comment by RafaelGSS** [comment]
I took a closer look at this and I don't think we should have this feature. This does not expose any surface attack to the process running with `--experimental-permission`. If all processes start with the permission model enabled `process._debugProcess` will do nothing. So, it works by default.

**Comment by RedYetiDev** [comment]
@RafaelGSS what about `kill()`ing?

**Comment by RafaelGSS** [comment]
It also has no impact in the current process. Even if you try to: `process.kill(process.pid)`
