### ISSUE TITLE
Threat Model  question about Permission Model

### ISSUE THREAD

**Issue by 4xpl0r3r** [nodejs/security-wg#1288]
According to the threat model, loaded code is trusted. What I want to know is, if a vulnerability is requireing monkey-patching to bypass the permission model, is it still recognized as a valid vulnerability? The response will direct my security research, thank you.

**Comment by RafaelGSS** [comment]
Most of the time, yes. If you find a way to use the official `require('fs')` module to bypass the capabilities imposed by the permission model, it is likely to be accepted. Important to note it should not be recognized as known limitation in https://nodejs.org/api/permissions.html#limitations-and-known-issues

**Comment by 4xpl0r3r** [comment]
Thank you, I see.
