### ISSUE TITLE
Add zoom link to recurring calendar invite

### ISSUE THREAD

**Issue by bmuenzenmeyer** [nodejs/security-wg#1399]
> [!NOTE]  
> This is cleanup from https://github.com/nodejs/admin/issues/923

People interacting with the WG via https://nodejs.org/calendar are met with not enough information to join.

![image](https://github.com/user-attachments/assets/a78fca67-4cdd-47cb-8bb1-098a63a22204)

And they won't necessarily know to look for issues like https://github.com/nodejs/security-wg/issues/1398

Further https://nodejs.org/en/about/get-involved/events only displays events with a zoom link.

To resolve all of this, please add https://zoom.us/j/92309450775 (which I think is a durable enough link, taken from the above issue) to the calendar.

**Comment by marco-ippolito** [comment]
Done can you verify?

**Comment by bmuenzenmeyer** [comment]
looks good thanks @marco-ippolito
