### ISSUE TITLE
Establish group membership

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#14]
Membership meaning:

- github permissions on this repo (for closing issues, merging, etc.)
- presence in meetings

Or are the two different?

**Comment by sam-github** [comment]
Without membership, for example, no one can label any issue so it ends up on the next working group agenda. Like this one! :-) How will initial membershp be determined? @rvagg @williamkapke @mikeal @jasnell

**Comment by williamkapke** [comment]
My suggestion is to just openly solicit who wants to be part of it. Keep the issue open for min 1 week- more is better... but make a some kind of enrollment period. Additional members can always be added later by nomination.

I would also like to start seeing a published "membership length" with easy renewal.

For instance: "Membership is for 6 months. The group will ask on a regular basis if the expiring members would like to stay on. A member just needs to reply to renew."
(also consider having a shorter "initial period")

**Comment by sam-github** [comment]
OK. I am requesting membership, please, so I can land PRs, tag issues, and generally help out.

**Comment by mcollina** [comment]
I'm requesting membership.

**Comment by vdeturckheim** [comment]
I'm requesting membership too.

**Comment by SomeoneWeird** [comment]
me three.

**Comment by cjihrig** [comment]
I just created the [security-wg](https://github.com/orgs/nodejs/teams/security-wg) team.

**Comment by gibfahn** [comment]
I'd like to join

**Comment by williamkapke** [comment]
Additionally from #3:

@jasnell, @MylesBorins, @bengl, @deian, @jbergstroem, @dougwilson, @chalker, @shigeki, @evilpacket, @roccomuso, @joshgav, @digitalinfinity, @ofrobots, @mhdawson,@drifkin, @mgalexander

This is a large membership once those are added. I (personally) would call the enrollment closed.

**Comment by cjihrig** [comment]
If your GitHub username is listed in the previous comment, please request membership at https://github.com/orgs/nodejs/teams/security-wg.

**Comment by bengl** [comment]
@cjihrig People not already part of the nodejs GitHub org cannot see that link and will probably have to be invited directly.

**Comment by cjihrig** [comment]
OK, I invited them.

**Comment by SomeoneWeird** [comment]
I think I might have been missed in that list :) I'd like to join as well if possible.

**Comment by grnd** [comment]
I'm requesting membership too. Thank you!

**Comment by roccomuso** [comment]
thanks! ok

**Comment by sam-github** [comment]
@cjihrig Thank you.

**Comment by sam-github** [comment]
Everybody added. For future inquiries, I think common WG practice after intial formation is to ask for membership by opening an issue and asking for it, and the issue is voted on by current members.
