### ISSUE TITLE
License of the database

### ISSUE THREAD

**Issue by mcollina** [nodejs/security-wg#156]
There is a significant number of vulnerabilities listed here. However, it's not clear what is the license that data is distributed under.

cc @nodejs/security-wg @nodejs/tsc we might as well ask to the Node.js Foundation lawyers about this, as these terms should have been discussed with the original data dump for nsp.

**Comment by ChALkeR** [comment]
@mcollina The repository has [MIT License](https://github.com/nodejs/security-wg/blob/master/LICENSE.md), and it looks to me that the db is currently being distributed under that liicense here.

An explicit confirmation would be great, though.

**Comment by vdeturckheim** [comment]
My understanding was that everything in the repo (including the vulnerabilities) was under MIT as @ChALkeR mentionned.

We can add a clarification to the vulnerabilities README if needed.

**Comment by mcollina** [comment]
The MIT license was added as part of the repository boilerplate (https://github.com/nodejs/security-wg/pull/9). The vulnerabilities were added in https://github.com/nodejs/security-wg/pull/26, and there was no discussion about the distribution license.

A clarification in the README would be good, thanks.

**Comment by dgonzalez** [comment]
Also we need to make sure that the appropriated license is MIT (at least for the vulnerabilities). We are allowing third parties to resell the information on the DB whereas with AGPL we guarantee that tools that use the data will be open or just internal for companies.

**Comment by ChALkeR** [comment]
Any updates on this?

**Comment by joepie91** [comment]
> We are allowing third parties to resell the information on the DB whereas with AGPL we guarantee that tools that use the data will be open or just internal for companies.

I'm not sure whether it works that way for data, given that the AGPL (and the MIT, for that matter) are specifically source code licenses, not data licenses.

**Comment by Trott** [comment]
> I'm not sure whether it works that way for data, given that the AGPL (and the MIT, for that matter) are specifically source code licenses, not data licenses.

@joepie91 IIUC, AGPL has been interpreted to work that way, which is why some people call it a "viral" license and many do not consider it an open source license at all.

**Comment by mhdawson** [comment]
Cross posted here: https://github.com/nodejs/community-committee/issues/271 to see if we can re-use what the community committee learned about the question they had and if not get some help to resolve.

**Comment by mhdawson** [comment]
Discussed in security WG meeting. Based on feedback from Foundation and discussion we believe that MIT is the right way to go.

**Comment by mhdawson** [comment]
Vladimir will update Readme.md to make it clear that it is under the same licence after

* pinging Adam on initial donation of data
* updating readme to clarify data will be published under MIT
* ensure that HackerOne template is clear that having submitted report includes agreement to have published under MITR.

**Comment by vdeturckheim** [comment]
I checked with @evilpacket this week. MIT works for him.
