### ISSUE TITLE
Create a badging tool for modules

### ISSUE THREAD

**Issue by dgonzalez** [nodejs/security-wg#157]
Similar to coveralls or travis, now that we have all the vulnerabilities information from npm modules automated, we can create a badging system similar to the one from coveralls so that we can issue badges for the `README.md` on whether they have any vulnerability on the security-wg or not. 

Not 100% sure about this but I think it is an idea worth exploring.

**Comment by vdeturckheim** [comment]
I love the idea, but I am not certain regarding the application. would that need some engineering on our side?

**Comment by dgonzalez** [comment]
I can do it. I build a vulnerability scanner based on the node.js swg (https://github.com/dgonzalez/gammaray) and issuing the badge depending on the security status is actually trivial (just need to add an http handler and off you go). Do not mind to migrate the repo to Node.js (it is golang as of now just for the convenience of being able to ship it in a container without any library dependency).

**Comment by lirantal** [comment]
I think if we do something like this then it has to be an officially supported (from our/the foundation side), production-ready service and properly maintained. It's easy and tempting to spin up lambdas for this or whatever, but taking it seriously in terms of pushing it to other repos and creating awareness means that this service shouldn't incur down-times or somehow become un-maintained after 3 months - it will not be very professional of us.

**Comment by dgonzalez** [comment]
Yeah that is true. Giving it a spin is almost a company like product....

**Comment by vdeturckheim** [comment]
looks like it's more a job for NSP and Snyk IMHO.

**Comment by dgonzalez** [comment]
Yeah... it almost look like a product. The idea came as it is an easy way to make sure that my module does not have any known vulnerability by the Node.js security working group (kinda official) but the logistics can be a bit problematic and suck up time.

**Comment by mhdawson** [comment]
I agree that we don't necessarily want to take on support for what would need to be a production application.

**Comment by dgonzalez** [comment]
So if no one else has any other objection, I will close this issue in a couple of days.

**Comment by didac-pf** [comment]
Related: #251 

(Thanks @dgonzalez for pointing it out, and sorry for not checking it before by my side)
