### ISSUE TITLE
Nominate Marcin Hoppe as member of the WG

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#163]
Hey @nodejs/security-wg,

I would like to nominate @MarcinHoppe to the WG to further help and support the triage team, as well as pick up on relevant agenda issues.

He's product security at auth0 and has been recently involved more with the WG through a PR to node.js website for the `security.txt` RFC.

Would be happy to get your support.

**Comment by cjihrig** [comment]
SGTM

**Comment by gibfahn** [comment]
SGTM

**Comment by vdeturckheim** [comment]
lgtm!

**Comment by mhdawson** [comment]
LGTM

**Comment by dgonzalez** [comment]
SGTM

**Comment by vdeturckheim** [comment]
@MarcinHoppe can you PR yourself as a member of the repo ? :)

**Comment by MarcinHoppe** [comment]
Both PRs have been merge so I guess this issue can be closed now?

**Comment by vdeturckheim** [comment]
Yes!
