### ISSUE TITLE
Standarize the format of vulnerabilities on core and npm databases

### ISSUE THREAD

**Issue by dgonzalez** [nodejs/security-wg#171]
There are few discrepancies in core and npm databases:
- https://github.com/nodejs/security-wg/tree/master/vuln/core
- https://github.com/nodejs/security-wg/tree/master/vuln/npm

For example dates are inconsistent across different files. We should document the format and add CI to validate PRs. @vdeturckheim I think you did some work on this with Joi validators.

**Comment by dgonzalez** [comment]
Here is the Joi schema: https://github.com/nodejs/security-wg/pull/102/files#diff-5b7a60d6cbe47068f950c8112a7c2a54R22

**Comment by vdeturckheim** [comment]
What format do you believe we should keep for dates @dgonzalez ? The Joi validation has been retro-engineered from what we had, but maybe it is time we make the change we want to the format before the db gets too big.

**Comment by dgonzalez** [comment]
I am ok with the dd-mm-yyyy or similar. Hour does not bring too much value.

**Comment by ChALkeR** [comment]
> dd-mm-yyyy

`yyyy-mm-dd`?

**Comment by vdeturckheim** [comment]
I'm usually pro `yyyy-mm-dd` ^^

**Comment by dgonzalez** [comment]
Works for me.

**Comment by lirantal** [comment]
yep

**Comment by lirantal** [comment]
sorry, accidentally hit the wrong button

**Comment by sam-github** [comment]
can this be closed now that #216 has landed?
