### ISSUE TITLE
NSWG-ECO-87 doesn't have patched_versions or vulnerable_versions set

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/security-wg#190]
https://github.com/nodejs/security-wg/blob/master/vuln/npm/87.json#L10-L11

NSP has 0.3.1 set for those, but that doesn't look correct to me.
It should be either 0.3.0 or smething higher — there look to be no related commits between 0.3.0 and 0.3.1.

/cc @evilpacket

**Comment by greysteil** [comment]
Snyk have this as vulnerable from 0.1.0 to 0.3.0. I'll open a PR to update the range to than.

https://snyk.io/test/npm/jwt-simple/0.1.0?severity=high&severity=medium&severity=low
