### ISSUE TITLE
Giving access to nodejs-private/security

### ISSUE THREAD

**Issue by shigeki** [nodejs/security-wg#195]
With a discussion with @rvagg via mail , I would like to ask for my access to nodejs-private/security in order to discuss OpenSSL issues.

**Comment by rvagg** [comment]
fwiw I suggested this to @shigeki, I've missed him for OpenSSL and crypto related issues since he resigned from the TSC, so +1 from me obviously.

**Comment by MylesBorins** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by danbev** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by rvagg** [comment]
done
