### ISSUE TITLE
Need consensus on exposing OpenSSL RSA KeyGen

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/security-wg#209]
As of now, we do not expose OpenSSL's RSA KeyGen functionality in the API as part of the `crypto` module.

This has been requested in https://github.com/nodejs/node/issues/15116

Quoting @bnoordhuis from the issue:

> There hasn't been much demand. It has been discussed a few times but since most people generate their keys ahead of time and since you can shell out to (for example) `openssl genrsa`, there doesn't seem to be a pressing need.

Quoting @tniessen,

> I would like to wait until we have a final decision about createCipher (see e.g. #13941) before making any further changes to the crypto API. Afterwards, I might consider implementing this.

Now that `createCipher` and `createDecipher` have been deprecated in favor of `createCipheriv` and `createDecipheriv`, could we have a quick consensus on this from the Security WG, perhaps in the upcoming (Friday, 20th April) meeting?

**Comment by tniessen** [comment]
@ryzokuken Why is this something to be decided by the security WG? Are there any security concerns related to RSA key generation that are out of the scope of nodejs/node?

**Comment by ryzokuken** [comment]
I tried looking for a working group to consult about the crypto subsystem
and mistakenly made the issue here. I just checked out the agendas of
previous meetings and realized my mistake. Closing this.

Meanwhile, could you point out some other place where we could ask people
about this apart from the TSC?

Thanks.

**Comment by tniessen** [comment]
@ryzokuken The nodejs/node repository should be used for such discussions, I will update https://github.com/nodejs/node/issues/15116.

**Comment by ryzokuken** [comment]
Thanks!
