### ISSUE TITLE
Vulnerabilities API

### ISSUE THREAD

**Issue by joshgav** [nodejs/security-wg#21]
One of the [proposed responsibilities of this group](https://nodejs.org/en/blog/announcements/nodejs-security-project/) is "owning and publishing the base dataset of disclosures." I think the ideal way to **publish** this data would be to make it available via a public, documented HTTP API.

The prime use case for such an API would be for tools and services to programmatically check for vulnerabilities alongside their main task; I suspect that's in fact how nsp works today. For example, npm might check for vulnerabilities on [`npm outdated`](https://docs.npmjs.com/cli/outdated).

Other uses would be to send notifications (e.g. via webhook) when new vulnerabilities are added, and to serve as a backend API for a human-readable website for searching and listing vulnerabilities.

I think we should host this API service on our "own" infrastructure as managed by the @nodejs/build team - "own" in quotes because most of it is backed by public cloud resources and not a private datacenter. In fact, I'm not sure what other options we have; any additional cloud resources needed by this service would likely be added to the Build group's responsibility too.

The conversation in #16 on how to **store** vulnerability data is loosely coupled to this conversation on a public API, in that we should be able to easily abstract the storage implementation from the API service.

In summary, this issue is to gather thoughts on:

1. Providing a public Vulnerabilities HTTP API.
2. How to build and host such an API service.

**Comment by mcollina** [comment]
This functionality is currently offered by several providers, and what we discussed in person at NINA  to _not_ have an API to query the dataset, but just providing the dataset to be downloaded, or something similar. If someone wants an API, they should build their own.

I am neutral to this, as I will not have any bandwidth to contribute to the development of this service.

**Comment by sam-github** [comment]
I'm in the same position of @mcollina, no time to implement this, but after we have some data stored, if someone wanted to do this, I can't think of any objects right now (though I don't think we want to get in the business of competing with the APIs behind any of the providers of security tools, we would want to be careful about that).

**Comment by sam-github** [comment]
This isn't a priority right now, but we'll leave open for the future if someone wants to pick it up (after we have the data managed and available).

**Comment by sam-github** [comment]
If no one is planning on working on this, perhaps we can close? It can always be repopened if someone does want to step up and make the case for this and implement it. Any objections, @joshgav ?

**Comment by sam-github** [comment]
I'm just going to close, but @joshgav (or anybody) feel free to reopen if you want to keep it alive.

**Comment by Haroenv** [comment]
So this was closed, but with npm acquiring nsp I'm not 100% sure which is the source of truth nowadays, @vdeturckheim told me it's https://github.com/nodejs/security-wg/tree/master/vuln/npm, but it isn't always super practical to fetch from GitHub, keep it up to date and have an API. I guess if there isn't an official one, I could make my own, would that be something you'd be interested in?

**Comment by vdeturckheim** [comment]
@Haroenv we discussed in some other issue to see if we could have an auto-published npm package containing issues (https://github.com/nodejs/security-wg/issues/115). I reopenned this issue I closed by mistake.
