### ISSUE TITLE
Small prose issue in HackerOne

### ISSUE THREAD

**Issue by bnb** [nodejs/security-wg#212]
Looks like the description of Node.js in HackerOne is slightly off:

> Only vulnerabilities in the core Node.js programming language and standard library [...]

Node.js isn't a programming language, it's a platform 😅

I suggest changing this to:

> Only vulnerabilities in Node.js core [...]

or

> Only vulnerabilities in Node.js itself [...]

**Comment by vdeturckheim** [comment]
Fixed, thanks for the heads up!

**Comment by bnb** [comment]
That was fast! Thanks Vladimir 💥
