### ISSUE TITLE
HackerOne help

### ISSUE THREAD

**Issue by dougwilson** [nodejs/security-wg#233]
Hello, I have a HackerOne report but I'm not getting any replies. I then tried to email security-ecosystem@nodejs.org and then security@nodejs.org but both go to HackerOne. What is the method to get a hold of someone. I'm trying to get a resolution on an issue before I leave in a few hours on vacation.

**Comment by jasnell** [comment]
Hey @dougwilson ... hmmm I'm looking at the HackerOne project for nodejs and it's not showing up there. Is the report for Node.js core or an ecosystem module? There are two separate HackerOne accounts, only one of which I can see.

Do you have access to the https://github.com/nodejs-private/security repo? If neither HackerOne account is working for you, and if you have access there, open an issue in that repo. Otherwise, feel free to send me an email with the issue and I'll get the report opened. 

We're still ironing out some issues with the HackerOne switch so apologies for the difficulty.

Definitely hope you enjoy your vacation!

**Comment by dougwilson** [comment]
Sorry, I didn't fully expand in my issue above, my bad :) So this is an ecosystem report that is already open against a module I maintain. I was not invited to the report until this morning, and want to get a fix out as soon as possible, especially since I'm just about to take extended leave from Node.js due to lack of Internet connectivity. I don't have the link handy at the moment, but the issue title starts with `[send]` in the ecosystem HackerOne section.

**Comment by dougwilson** [comment]
https://hackerone.com/reports/340051 is the report.

**Comment by mcollina** [comment]
@dgonzales will look into it asap (or so he told me).

**Comment by dgonzalez** [comment]
I am handling it. Sorry for the delay. Let's move to hackerone.

**Comment by MarcinHoppe** [comment]
@dougwilson Sorry for a late response but I am in a different timezone (CEST) and was away from the keyboard for a couple of hours. I did not mean to neglect your messages, just did not get them.

I responded on the HackerOne report and I think we are in a good shape right now. The change to the simple sample in the README is to me a sufficient remediation.

Thanks for your patience!

**Comment by vdeturckheim** [comment]
Maybe we should update our HackerOne page with a link to our Slack. That's probably the best way to obtain quick support from the triage team.
Also, a few of us are unavailable this week/weekend :/

**Comment by lirantal** [comment]
> Maybe we should update our HackerOne page with a link to our Slack.
👍

**Comment by MarcinHoppe** [comment]
The HackerOne report in question has now been closed. Are we good to close this issue?

I'd prefer to have a separate issue to add Slack info on the HackerOne page.

**Comment by dgonzalez** [comment]
I think we are good yes.

**Comment by MarcinHoppe** [comment]
It looks like we have a consensus (or at least nobody voiced any objections). Closing.

**Comment by dougwilson** [comment]
Yes, I have some super slow Internet right now and I did get help Friday and so this can be closed. A Slack group would be awesome for the future :+1:

**Comment by lirantal** [comment]
@vdeturckheim updated the Node.js Ecosystem landing page with that info https://hackerone.com/nodejs-ecosystem/

thanks for your input and patience @dougwilson
