### ISSUE TITLE
Activity seems to have petered out

### ISSUE THREAD

**Issue by joshbw** [nodejs/security-wg#25]
There hasn't been a lot of activity here since March - is there anything we should meet about, or delegate to get done?  We were looking at a more robust security issue reporting/tracking service, and since then HackerOne has made their platform free for open source projects.  What else needs attention?

**Comment by sam-github** [comment]
#17 needs attention if you are interested in evaluating HackerOne.

#16 needs attention if you have time.

Generally going through the open issues and seeing if there are any you can help out on would move things forward, IMO.

**Comment by mcollina** [comment]
@sam-github maybe we can have a wg meeting? I think there is plenty of structure to discuss, specifically on how we manage the disclosure flow.

**Comment by sam-github** [comment]
I'm planning on requesting a meeting for next week, still gathering a todo list of things to discuss. That said, anybody in the WG can request a meeting, I have no special powers! hint, hint, wink.
