### ISSUE TITLE
Brainstorm capturing/documenting areas people can contribute

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#253]
@detrohutt is volunteering to help document how people can get involved across the project and also to see if we can capture items from working groups and strategic initiatives.

I suggested we start with brainstorming with one or more WGs and is one of the first ones on the list.

**Comment by sam-github** [comment]
I'm not sure if brainstorming ocurred, but this has been open for a year without comment, I'll close for now. Please reopen if closing is premature.
