### ISSUE TITLE
vulnerable/patched versions for unfixed packages

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/security-wg#272]
For new reports, an approach like this is used (where 0.0.24 is the current version):
```js
"vulnerable_versions": "<=0.0.24",
"patched_versions": null,
```

But we have a large number of files (130, ~35% of the whole dataset),  that use the following approach for this situation:
```js
"vulnerable_versions": "<=99.999.99999",
"patched_versions": "<0.0.0",
```

Imo, we should use a single approach for those cases, i.e. update all entries to have either the first or the second approach.

The problem in the first (newer) case is that there are no reasons to believe that `0.0.25` would be not vulnerable (and we need to keep track of that and increase the vulnerable range if new versions were released). I.e. we would be getting false negatives.

The problem in the second (older) case is that there could be a new release with a fixed version (and we need to keep track of that and decrease the vulnerable range if new versions were released — but we still need to do that to update patched versions and recommendation). I.e. we would be getting false positives.

/cc @nodejs/security-wg thoughts? Perhaps @lirantal and @evilpacket personally.

_Note: `superstatic` was an exception because they had the fix landed and prepared for the next release._

**Comment by lirantal** [comment]
I'm in favor of the 1st option as it conveys more truth about the actual situation.
Meaning, you can easily understand that the version that was triaged against at that point in time was 0.0.24, and it is also flexible enough so that if one wanted to flag that module as vulnerable then it can rely on the `patched_version` being null to do just that, regardless if 0.0.25 is out.

**Comment by mhdawson** [comment]
In the first version since we have a special value (null) for no patched versions, how about doing the same for the case when all versions are vulnerable, possible 'all'.

**Comment by sam-github** [comment]
Is there something to be done here? Do the process docs need updating, or the vuln submission tool? Or were the changes suggested already implemented?

**Comment by fraxken** [comment]
I'm closing the issue as most subject related to DB seems outdated to me (and since there is no recent answers). Feel free to reopen if I'm wrong.
