### ISSUE TITLE
Enable Jenkins on this repo

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#278]
As discussed during meeting on 2018/05/17 @mhdawson and @vdeturckheim to set this up to validate reports on PRs.

**Comment by vdeturckheim** [comment]
@mhdawson maybe we should schedule a 30 min slot during next summit and do it if that works for you.

**Comment by mhdawson** [comment]
That works since it will be pretty busy between now and then.

**Comment by vdeturckheim** [comment]
We now have Travis.
