### ISSUE TITLE
Alex Knol (@Elexy) into the third party triage team (and security working group)

### ISSUE THREAD

**Issue by dgonzalez** [nodejs/security-wg#284]
Hi,

I propose Alex Knol (@Elexy) to become a member of the security working group and the third party triage team. He is a colleague of mine and has expressed his interest in helping with the triage of third 
party modules.

I can totally back him up from the professional (and personal) point of view.

**Comment by dgonzalez** [comment]
@Elexy is already part of the foundation and the delivery-channels team (https://github.com/orgs/nodejs/teams?query=%40Elexy)

**Comment by vdeturckheim** [comment]
LGTM :+1:

**Comment by dgonzalez** [comment]
Also, please be aware that he is a colleague of mine (we work on the same company).

**Comment by mhdawson** [comment]
LGTM.

**Comment by MarcinHoppe** [comment]
👍

**Comment by dgonzalez** [comment]
@Elexy can you PR yourself in the security-wg and the third party triage team?
- Here: https://github.com/nodejs/security-wg/blob/master/README.md
- And here: https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md

**Comment by Elexy** [comment]
PR here https://github.com/nodejs/security-wg/pull/312
Thanks for having me :-)

**Comment by dgonzalez** [comment]
Alex has been onboarded. Closing this.
