### ISSUE TITLE
Join the Node.js Security Working Group

### ISSUE THREAD

**Issue by rvagg** [nodejs/security-wg#3]
Add your name here or tag people that you think might be interested in joining a public working group focused on Node.js core and ecosystem security matters.

At Node.js Interactive today, @evilpacket announced that the @nodesecurity project will be moving in to the Node.js Foundation. This Working Group should be able to inform how that integration will happen and may end up maintaining that project. The evolution of this group and its relationship with the @nodesecurity project is not defined and will be up to those involved to guide.

See https://github.com/nodejs/security-wg/pull/1 for a proposed purpose and scope of work for this group.

See https://github.com/nodejs/security-wg/pull/2 for the proposed relationship between activities here and the private management of security vulnerability reporting, patching and releasing of Node.js core.

/cc @nodejs/security

**Comment by jasnell** [comment]
+1 ... Add me to the list

**Comment by mcollina** [comment]
+1 add me.

**Comment by SomeoneWeird** [comment]
I'd like to be involved if possible :)

**Comment by sam-github** [comment]
+1 add me

**Comment by TheAlphaNerd** [comment]
o/ +!

**Comment by bengl** [comment]
+ me plz!

**Comment by deian** [comment]
+1

**Comment by jbergstroem** [comment]
Hey, it's me. I'm interested if this covers infra/ci.

**Comment by dougwilson** [comment]
I'm interested for representing some of the ecosystem.

**Comment by ChALkeR** [comment]
+1, count me in =).

**Comment by shigeki** [comment]
+1 for me.

**Comment by evilpacket** [comment]
Please add me to the list.

**Comment by roccomuso** [comment]
+1

**Comment by joshgav** [comment]
Please add me.

/cc @jasongin @digitalinfinity (please indicate if you'd like to join).

/cc @williamkapke to help us follow best practices for setting this up.

**Comment by digitalinfinity** [comment]
+1

**Comment by ofrobots** [comment]
+1

**Comment by mhdawson** [comment]
+1 for me

**Comment by cjihrig** [comment]
Please add me.

**Comment by drifkin** [comment]
I'd like to join

**Comment by mgalexander** [comment]
+1

**Comment by vdeturckheim** [comment]
+1 I actually work full time on Node.js security related stuff

**Comment by joshgav** [comment]
Closing this now, follow @sam-github's instructions [here](https://github.com/nodejs/security-wg/issues/14#issuecomment-272568074) to request to join.
