### ISSUE TITLE
Review membership

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#302]
It may be time to review our membership list.  There are quite a few people that I don't think have been active for quite a while.  It is probably a good time to do this as the WG is being formally chartered.

What I'd suggest is:

1) Post an issue with an @ notice to all members asking they confirm they still plan to be active in the WG.
2) Remind after 2 weeks
3) After 4 weeks move all of those who have not responded to 'emeritus'
4) Allow a grace period of 4 more weeks where people can request to be added back without requiring consensus reaching by the WG.

@nodejs/security-wg thoughts?

**Comment by vdeturckheim** [comment]
LGTM!

**Comment by MarcinHoppe** [comment]
I suspect that after all grace periods elapse, all the access rights will be revoked for emeritus WG members? It would be good to compile list of action items before we have to do it.

**Comment by mhdawson** [comment]
@MarcinHoppe, correct. Starting list would be:

1) Updated README.md
2) remove from https://github.com/orgs/nodejs/teams/security-wg

**Comment by mhdawson** [comment]
Possibly also remove from security-wg slack ? @lirantal. @vdeturckheim

**Comment by mhdawson** [comment]
We should also likely remove hacker one access if the team member had it.

**Comment by vdeturckheim** [comment]
@mhdawson 
We can remove them from the private channels and H1 as needed yes. @lirantal and I are admin on both and should be able to do so.
