### ISSUE TITLE
2018 CVE's?

### ISSUE THREAD

**Issue by beetle-ibm** [nodejs/security-wg#308]
It appears https://github.com/nodejs/security-wg/tree/master/vuln has not kept up with the 2018 CVE disclosures that are posted on the blog.  Is this not considered an authoritative/definitive source of CVE's affecting Node and core modules? If not, is there a definitive (preferably easily machine readable) source other than the blog itself?

**Comment by lirantal** [comment]
Are you possibly referring to items in the following open PR https://github.com/nodejs/security-wg/pull/201 ?

**Comment by beetle-ibm** [comment]
Thanks for the quick response!  I am actually indirectly asking this question for someone else - they will check if those PR's contain what they expect. 

In the meantime, so I am clear, is this repo meant to be a definitive source of vulns pertaining to node core?  And if so, what would you estimate is the average lag time between the blog (https://nodejs.org/en/blog/vulnerability/) and PR's getting merged with new vulns here?  Thanks again!

**Comment by mhdawson** [comment]
I don't have an estimate on the lag time as obviously we've not done that well in the last few releases, but I'd hope that we'd get it down to a week or less.

**Comment by beetle-ibm** [comment]
Cool - thanks for the input!
