### ISSUE TITLE
Third party triage team outgoing email

### ISSUE THREAD

**Issue by dgonzalez** [nodejs/security-wg#309]
When we approaching a module author about a report submitted to hacker, we usually do with our personal/work email which leads into "is this true or a scam?". I think we should be having an official email/alias to contact module authors.

some of the names we could use:

- third-party-triage-team@...
- triage-team@...
- security-triage@...

**Comment by mhdawson** [comment]
PR for meeting minutes: https://github.com/nodejs/security-wg/pull/310
