### ISSUE TITLE
Document Security Announcement process

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#31]
First cut at documenting the security announcement process.  I think we have agreement that our processes documented publicly even in cases like the security announcement process were some of the work must be completed in private.  The security wg is probably the place to discuss these and possibly the place to document them.  Once we are in general agreement on where the doc should go I'll move the text into a PR on the appropriate repo.

* On issue for security vulnerability in private security repo, propose candidate text based on past announcements.

* Once reviewed, agree on timing for announcement and line up releasers to make sure they are available to do the release on that date.

* Post to https://groups.google.com/forum/#!forum/nodejs-sec. Note that you will need to have
been given access by one of the existing managers (Ben Noordhuis, Rod Vagg, Trevor
Norris, Michael Dawson). You will have to manually edit to add formatting and links
properly.

* Mirror post in vulnerabilities section of Nodejs.org blog section.
Submit PR and leave 1 hour for review. After one hour even if no reviews, land anyway so that we
don't have too big a gap between post to nodejs-sec and blog. Text was already reviewed in security
repo so.

* In original PR for security issue, post candidate text for updates that will go out with releases that
will indicates releases are available and include full vulnerability details.

* Once releases are made, post response to original message in
https://groups.google.com/forum/#!forum/nodejs-sec indicating releases are available and with the
full vulnerability details.

* Update the blog post in https://github.com/nodejs/nodejs.org/tree/master/locale/en/blog/vulnerability
with the information that releases are available and the full vulnerability details.
Keep the original blog content at the bottom of the blog. This is an example:
https://github.com/nodejs/nodejs.org/blob/master/locale/en/blog/vulnerability/june-2016-security-releases.md. Make sure to update the date in the slug so that it will move to the top of the blog list.

* Tweet out a link to the nodejs-sec announcement

* Email foundation contact to tweet out nodejs-sec announcement from foundation twitter account ?

**Comment by mhdawson** [comment]
Since I've not had any negative/positive feedback on this I'm going to PR.

**Comment by gibfahn** [comment]
Sorry, missed this earlier.

Generally this makes sense, but for:

>Submit PR and leave 1 hour for review. After one hour even if no reviews, land anyway so that we
don't have too big a gap between post to nodejs-sec and blog.

Making it an hour seems a bit arbitrary. As you say, it's already been reviewed, so if you double-check it (or maybe get someone else to have a look if you have a willing volunteer) it could just be landed right? An hour seems like the perfect amount of time to forget and be distracted by something else 😁 .

NBD though, and we can always revise it later.

**Comment by rvagg** [comment]
@gibfahn ftr I've never maintained a strict time on posting these, most of them have been published immediately. _However_ that Website WG is good at picking up spelling, grammar and other text problems, they've done so for a number of my posts, so it's good to have them involved. All of that stuff can be edited afterward too so NBD either way.

**Comment by mhdawson** [comment]
Closing as PR landed. https://github.com/nodejs/security-wg/pull/39
