### ISSUE TITLE
Membership review

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#313]
Membership review as agreed in: https://github.com/nodejs/security-wg/issues/302.

@bengl ->confirmed, but emeritus from triage
@brycebaril -> confirmed, but emeritus from triage
@ChALkeR -> confirmed
@cjihrig -> confirmed
@dgonzalez ->confirmed
@deian ->confirmed
@digitalinfinity -> emeritus
@dougwilson ->  emeritus
@drifkin  -> confirmed
@evilpacket -> emeritus
@gergelyke -> emeritus
@gibfahn -> emeritus
@grnd ->confirmed
@jasnell  ->emeritus
@jbergstroem -> emeritus
@joshgav -> emeritus
@lirantal  -> confirmed
@MarcinHoppe -> confirmed
@mcollina -> emeritus
@mdawson   ->confirmed
@mgalexander -> confirmed
@ofrobots -> emeritus
@roccomuso -> emeritus
@sam-github -> emeritus
@shigeki -> emeritus
@SomeoneWeird -> confirmed
@vdeturckheim -> confirmed

Please confirm by posting a comment on this issue if you plan to continue being active in the Security WG.  If we don't hear from you we will move you to emeritus as outlined in https://github.com/nodejs/security-wg/issues/302.

**Comment by mhdawson** [comment]
I'm confirming that I'm planning to continue being active in the WG as requested.

**Comment by drifkin** [comment]
I plan to continue being active.

**Comment by jasnell** [comment]
I'll still be part of the security and triage team for core, but feel free to move me to emeritus status in the Security WG.

**Comment by SomeoneWeird** [comment]
I still plan on helping out as much as possible 👍

**Comment by bengl** [comment]
Confirming that I plan to continue being active in the WG.

**Comment by deian** [comment]
Confirming to be (more) active

**Comment by dgonzalez** [comment]
I confirm that I will remain as active WG member.

**Comment by lirantal** [comment]
I'm confirming that I plan to continue my activities with the WG

**Comment by grnd** [comment]
Confirming that I plan to continue being active in the WG.

**Comment by mcollina** [comment]
Please move me to Emeritus status.

**Comment by mgalexander** [comment]
I hope to get reengaged during the summer months and would like to stay an active WG member.

**Comment by shigeki** [comment]
Please move me to the emeritus list for I can only work for embargoed security patches and releases in Private Node.js core security group.

**Comment by gergelyke** [comment]
Please move me to Emeritus status - I am still planning to be active on Slack, and help whenever I can.

**Comment by gibfahn** [comment]
Please move me to Emeritus status.

**Comment by digitalinfinity** [comment]
Please move me to Emeritus as well

**Comment by brycebaril** [comment]
Confirming I will remain active in the security-wg, though I should probably step down from the triage team given how little time I've been able to make for that part.

**Comment by bengl** [comment]
I already commented stating my intention to stay on, but I think I need to join @brycebaril in stepping down from the triage team for the same reasons. If my work schedule changes in the future, I'd be happy to step in again.

**Comment by ChALkeR** [comment]
I plan to continue being active in the Security WG.

**Comment by lirantal** [comment]
@mcollina @jasnell @gibfahn @digitalinfinity @gergelyke can you open a PR to move yourself into emeritus?
see reference https://github.com/nodejs/security-wg/pull/323

**Comment by mcollina** [comment]
@lirantal that PR you linked only refers to the 3rd-party triage team, but not this full team.

Check this out: https://github.com/nodejs/security-wg/pull/331

**Comment by dougwilson** [comment]
Please move me to Emeritus status, as I just haven't had time to truly be active in the group :(

**Comment by mhdawson** [comment]
@evilpacket
@jbergstroem
@joshgav
@ofrobots
@roccomuso
@sam-github

This is the second reminder.  If we don't hear from you, we'll move you to emeritus.

**Comment by mhdawson** [comment]
Review complete, closing.
