### ISSUE TITLE
Node Summit - Node.js What's next talk

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#334]
I'm doing a Node.js "What's next talk" and I have one slide on the security wg which is as follows:

![image](https://user-images.githubusercontent.com/9373002/42345583-c94cae86-806d-11e8-9dba-ecac54cd4909.png)

Anything else that I should be highlighting ?

**Comment by vdeturckheim** [comment]
Nice! LGTM

**Comment by mhdawson** [comment]
Thanks for the review, closing
