### ISSUE TITLE
ESlint fallout: understand npm access security and possible tightening

### ISSUE THREAD

**Issue by Elexy** [nodejs/security-wg#342]
Today it became apparent that the eslint module was compromised. 
reference: https://github.com/eslint/eslint-scope/issues/39

From our perspective we want to understand better how access to the npm repository is controlled in a general manner and what the options are to tighten down security. Specifically for the Eslint breach we want to find out how the attacker was able to publish the malicious version.

One question that came up during our WG meeting was about signing the images and how to ensure that the verification of the signatures remains valid.

We want to engage with the NPM team to understand their process and timeline around this subject

**Comment by Elexy** [comment]
Wanted to reference this resource here: 
https://medium.com/redpoint/introducing-pkgsign-package-signing-and-verification-for-npm-5b833e0ec2d4

**Comment by mhdawson** [comment]
@bengl thanks for the pointers on how far along npm is with signing. I was sure there was progress on that front.  I think in my case it would have needed the author to be able to sign in order to mitigate the risk that sounds like the next step npm is working on.

**Comment by Elexy** [comment]
The [post mortem](https://eslint.org/blog/2018/07/postmortem-for-malicious-package-publishes) of the incident

**Comment by Elexy** [comment]
Suggestions:

1. NPM could force `npm token create --cidr=<cidr-ranges>` for non 2FA authentications
2. Async 2fa, so CI/CD can upload with a `upload only` token and then confirm with the author asking them to release publication. 

Async 2FA publishing allows to add `npm audit` into the process, before things go live.

**Comment by sam-github** [comment]
This seems like it has stalled, and would be best opened as an issue with npm. I'm closing, but if someone feels it should remain open, I'm happy to do so.
