### ISSUE TITLE
Post Node Summit discussion: policies in Node.js core 2018-07-26

### ISSUE THREAD

**Issue by drifkin** [nodejs/security-wg#350]
As discussed in #327, several security-wg members will be in San Francisco due to Node Summit, so it seems like a good opportunity to discuss policies in Node core in person. We decided that the best day to meet is the day after the conference (a Thursday).

We'll host the meeting at Intrinsic (in the financial district) and also set up a video chat for anyone who wants to join remotely (so far we know of @bmeck joining remotely)

- Date: 2018-07-26
- Proposed time: 2:30 PM PDT (see <https://www.timeanddate.com/worldclock/fixedtime.html?iso=20180726T1430&p1=224> for other timezones)
- Location: Intrinsic, 50 Osgood Pl, SF 94133 (<https://goo.gl/maps/B9QcXkNrwik>)
- Call in URL: https://meet.google.com/fjr-gedt-vmi

Does 2:30 PM PDT work for everyone who wanted to join? /cc @mhdawson @mikesamuel @vdeturckheim

**Comment by rvagg** [comment]
I'm in town and may come along if that's ok

**Comment by mhdawson** [comment]
Going to bring along @gireeshpunathil with me as well (another Node.js collaborator from IBM).

**Comment by bnb** [comment]
Super glad we connected the dots with @gireeshpunathil 🙌

**Comment by thlorenz** [comment]
I'm coming by as well today .. looking forward to the discussions :)

**Comment by bengl** [comment]
For folks coming to the Intrinsic office today: If I'm not at the door to let you in, there's a sign on the door at 50 Osgood Pl with my phone number so I can come let you in.

**Comment by drifkin** [comment]
Video call up at https://meet.google.com/fjr-gedt-vmi

**Comment by sam-github** [comment]
Closing, since the call happened last July.
