### ISSUE TITLE
Vuln 440 data seems wrong

### ISSUE THREAD

**Issue by evilpacket** [nodejs/security-wg#353]
Semver ranges don't align with what's in the hacker1 report and and the commit message for it is for express-cart so wondering if it's for another vuln?

**Comment by lirantal** [comment]
Looks like `express-cart` is reported well on https://github.com/nodejs/security-wg/blob/master/vuln/npm/441.json and 440 is indeed mixed up.

I pushed a fix here: https://github.com/nodejs/security-wg/pull/354

**Comment by evilpacket** [comment]
Duplicate vuln deleted, closing.
