### ISSUE TITLE
doc: Expected target WG size

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/security-wg#364]
https://github.com/nodejs/security-wg/blob/master/GOVERNANCE.md#wg-membership

> WG seats are not time-limited. There is no fixed size of the WG. However, the expected target is between 6 and 12, to ensure adequate coverage of important areas of expertise, balanced with the ability to make decisions efficiently.

That doesn't look true, we are way above that. Has this been copied from some boilerplate?
Perhaps it would be worth to remove the "expected target" whatsoever, as those numbers don't really affect anything.

**Comment by richardlau** [comment]
> Has this been copied from some boilerplate?

It's in the bootstrap governance boilerplate in the TSC WG document: https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#bootstrap-governance

**Comment by Trott** [comment]
Yeah, that bootstrap boilerplate is basically unmaintained. Improvement PRs welcome. In the meantime, I'd recommend this WG remove that last sentence if not that entire paragraph.

**Comment by mhdawson** [comment]
I believe this can be  closed as  PR to address landed, closing.
