### ISSUE TITLE
doc: WG is chartered

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/security-wg#365]
[WORKING_GROUPS.md#security](https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#security) is there, https://github.com/nodejs/TSC/pull/548 landed, https://github.com/nodejs/TSC/issues/486 is resolved, but [Readme states](https://github.com/nodejs/security-wg#security-working-group): 

> ## Security Working Group
> Note: this group is in the process of seeking Charter by the TSC (https://github.com/nodejs/TSC/issues/486)

That should be updated, as I presume. /cc @mhdawson @vdeturckheim

**Comment by lirantal** [comment]
🎉 🎉 🎉
