### ISSUE TITLE
add CHARTER.md or similar

### ISSUE THREAD

**Issue by Trott** [nodejs/security-wg#368]
It would be good to have the TSC-approved CHARTER document in this repository. CHARTER can't be changed without TSC approval, but anything else is up to WG discretion/process. Or at least that's what I'd assume.

**Comment by richardlau** [comment]
I'm not aware of any other chartered WG's having an equivalent document. What is it expected to contain?

**Comment by Trott** [comment]
> I'm not aware of any other chartered WG's having an equivalent document. What is it expected to contain?

Hmmm...that's interesting. TSC and CommComm repos have docs like that and I just assumed all the WGs did too, but clearly, I'm wrong. I'll close this and bring it back to the TSC and CommComm if I think it's something all WGs should do.
