### ISSUE TITLE
Request to join the wg

### ISSUE THREAD

**Issue by brycebaril** [nodejs/security-wg#37]
:wave: Hi everyone, I've been keeping an eye on this repo, but I'd like to formally request to join the working group. As for who I am, I'm the VP of Engineering at NodeSource, and I've been using Node for, like decades now ;)

Thanks for your consideration!

**Comment by sam-github** [comment]
Sounds good to me, Bryce, can we get a couple more thumbs up?  Actually, it looks like we need unanimous consensus: https://github.com/nodejs/security-wg/blob/master/GOVERNANCE.md#wg-membership Not sure what that means, probably no objections? :-(

@mhdawson @cjihrig how should this work? do we discuss in private before the next meeting and then invite Bryce? Wait for any objections? What?

**Comment by cjihrig** [comment]
It looks like we should add it to the agenda for the next meeting. Personally, I'd rather just call for objections (private objections can be sent to me) here, and add Bryce next week.

**Comment by mhdawson** [comment]
For many WGs the process is often that people join the meetings, volunteer for work and then get added after some level of activity.  

Since the WG is still really in bootstrap mode and we have a longish list of members with varying levels of activity though I have no objection to adding Bryce as we want as many active participants as possible.

I do suggest the WG adopt participation guidelines along the lines of (take from Community Committee governance): 

```
CC members are expected to regularly participate in CC activities.

In the case where an individual CC member -- within any three month period -- attends fewer than 25% of the regularly scheduled meetings, does not participate in CC discussions, and does not participate in CC votes, the member shall be automatically removed from the CC. The member may be invited to continue attending CC meetings as an observer.
```

**Comment by gibfahn** [comment]
+1 to @brycebaril, and +1 to adding directly.

**Comment by mhdawson** [comment]
Seems like the consensus is to move forward. @brycebaril can you submit a PR on the README.md adding you to the WG.

**Comment by brycebaril** [comment]
@mhdawson will do!

**Comment by bengl** [comment]
Looks like this went through, so I'm gonna close this. Welcome @brycebaril!
