### ISSUE TITLE
Adding a security vulnerability that was disclosed in the public

### ISSUE THREAD

**Issue by mcollina** [nodejs/security-wg#371]
In https://github.com/mcollina/aedes/issues/211 a security vulnerability was posted in the public. In https://github.com/mcollina/aedes/pull/212 it was fixed, and I've just released that fix.

I would like to get this added to the database, and I would definitely need a CVE. Should I pass through H1 anyway, or should I just send a PR?

**Comment by lirantal** [comment]
per the policy we can just PR to the repo the vulnerability. however, if you don't have already a CVE assigned for that then we'll need to request that manually. I suggest you to PR the report and I'll request it for you through the H1 platform.
