### ISSUE TITLE
462 a duplicate of 442?

### ISSUE THREAD

**Issue by evilpacket** [nodejs/security-wg#387]
At first glance it appears that 462 is a duplicate of 442 but with information missing? cc @lirantal

**Comment by lirantal** [comment]
oh that's true!
I'll go ahead and update it.

@pxlpnk maybe we can add another linter check that makes sure there aren't any duplicates? I think we can compare based on the hackerone report number

**Comment by pxlpnk** [comment]
@lirantal do we always have a h1 report number?

**Comment by lirantal** [comment]
In most of the cases yes.
The only times we don't have any H1 reference is when the vulnerability has been disclosed or fixed outside of the program and then we just PR it directly to the database.
