### ISSUE TITLE
Vulnerabilities from academics

### ISSUE THREAD

**Issue by davisjam** [nodejs/security-wg#415]
1. Work from Microsoft Research / UC Berkeley on misc. vulnerabilities: http://jacksongl.github.io/vuln.html
2. Work from Virginia Tech on regexes: I have a spreadsheet which I shared with Snyk. I don't think all were validated or responded so I'm unwilling to share publicly. Contact me for private link.

**Comment by vdeturckheim** [comment]
Thanks @davisjam !

@nodejs/security-wg what do you think is the best way to include all of that ijn our dataset?

**Comment by lirantal** [comment]
Great work Jamie, and thanks for sharing it.
First thought after creating the awesome nodejs security repo is that maybe it could be added there as part of the research work.

With regards to somehow pulling those vulnerabilities to our db I'm not so sure. They're already found/covered in other databases/tools and if we start importing these to our db then where do we stop? should we also crawl and import all of npm advisories, etc?

I'm thinking this ties into a much larger idea that we started discussing in the collab summit about possibly having a joint hub of vuln dbs where the community/industry can collaborate on.

**Comment by davisjam** [comment]
> With regards to somehow pulling those vulnerabilities to our db I'm not so sure. They're already found/covered in other databases/tools

Some of them are; some are not.
- I did not disclose everything I found.
- Some of those I disclosed have not been addressed and are not in a vulnerability DB.

**Comment by lirantal** [comment]
Ah got it. Would you want to disclose them through the WG?

**Comment by davisjam** [comment]
Like I said, you can have the spreadsheet if you want :)

**Comment by lirantal** [comment]
yes, let's discuss! :-)

**Comment by lirantal** [comment]
@davisjam I'll take it with you offline to review and figure out how we want to work on them.
For the mass-disclosure I think we can just import them into the Security WG DB instead of pushing that mass into H1 because that will be a major work for us to do because it's a manual process.

Let's review the data and figure out what can be disclosed flat out because maybe those are old and unmaintained libraries, and what could be considered as 0 days and we can work together with maintainers to mitigate it.

**Comment by lirantal** [comment]
@davisjam we tried to meet couple of times but it didn't work out, I'll send you another invite :)

**Comment by davisjam** [comment]
@lirantal Great! My holiday is almost over so we can sync up soon.

**Comment by lirantal** [comment]
Scheduled us 2 sessions

**Comment by lirantal** [comment]
Discussed this with Davis. Probably not much to do on the input from Liang Gong as that already happened I believe. Will follow up with him on the redos dataset, perhaps disclosing through snyk if more appropriate to handle mass disclosure.

**Comment by fraxken** [comment]
Has the topic been addressed @lirantal ?

**Comment by lirantal** [comment]
Yep, we can close this up.
