### ISSUE TITLE
What is the good time for the Security WG monthly meeting

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#416]
Currently it's once a month on Thursdays at UTC 19:00 (07:00 PM):
It seems it conflicts with some other meetings. Can you please suggest other times?

edit: Please specify all available times and days in the week that you will be able to attend: https://doodle.com/poll/2s5qr4xhgvkh2syg
- You may suggest a new time if it's not showing up on the poll

**Comment by gireeshpunathil** [comment]
any time at or before 4 PM UTC (3 hours before the current time) works for me. thanks!

**Comment by lirantal** [comment]
+1 on @gireeshpunathil's suggestion. 3PM or 4PM UTC would work for me, earlier not so much.

**Comment by sam-github** [comment]
Anytime 6-4 pacific time works for me, mon-wed-fri evenings after 7pm works, tues & friday don't work so well, though I will make it once a month if that's the time.

**Comment by lirantal** [comment]
I created a doodle to make it easy to visualize the available timing options (it will show it in your timezone), please use it: https://doodle.com/poll/2s5qr4xhgvkh2syg

**Comment by lirantal** [comment]
Thanks for everyone who submitted their times.
It seems like we got the most votes for Monday 8AM PST (10 votes).

Reference to poll results: https://doodle.com/poll/2s5qr4xhgvkh2syg?utm_campaign=poll_added_participant_admin&utm_medium=email&utm_source=poll_transactional&utm_content=gotopoll-cta#table

Is there anyone who strongly objects to that option?

**Comment by lirantal** [comment]
Thanks Sam!
Let's try and see how it goes, hopefully more people will join than usual.

**Comment by sam-github** [comment]
I should have followed up... I don't currently have the privileges to do that, I lost them during the last year.

See https://github.com/nodejs/security-wg/issues/426#issuecomment-434079140 and follow up.

**Comment by mhdawson** [comment]
I missed the part about it being moved to monday, and I thought you had said you had updated the calendar which on reflection does not make sense.

I'll update to monday and I think I should just close this issue and let the tool auto generate a new one.

**Comment by mhdawson** [comment]
Going to close this and let the new issue be opened a few days before the meeting. Calendar is now updated.  

As a Note I won't be able to make the meeting on Monday.  @cjihrig are you going to make it/be able to start the zoom/stream?

**Comment by cjihrig** [comment]
As of now I should be able to make it on Monday.
