### ISSUE TITLE
Recognising Maintainer effort

### ISSUE THREAD

**Issue by Elexy** [nodejs/security-wg#427]
We recognise hackers for their efforts by way of Tweet. Also we spoke about sending swag to the most active ones.
Could we do the same for maintainers whom have gotten positively involved in solving issues?

**Comment by lirantal** [comment]
Definitely! There are some plans on how to recognize hackers and they should be applied to maintainers as well:
1. Social media tweets
2. Quarterly medium posts
3. Swag (tshirts, stickers, etc)

**Comment by mhdawson** [comment]
That is a good idea :)

**Comment by fraxken** [comment]
👋 Closing the issue since it's old.

But no worry we will continue to love and support maintainers for their efforts 💪❤️.
