### ISSUE TITLE
process/format to add JSON for advisories

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#437]
There is an npm tool to add vulns, but I'm not sure where it is, and the top-level README doesn't describe where it is, or link to the format of the JSON that will be added.

The top-level also doesn't link to https://github.com/nodejs/security-advisories or describe it (as https://github.com/nodejs/security-advisories/blob/master/README.md promises).

I assume that once security-advisories is live, https://github.com/nodejs/security-wg/tree/master/vuln will be deleted?

**Comment by waveywaves** [comment]
I will update the README with the tools being used for updating the vulns. Seems like the vulns in the security-wg repo are ordered numnerically and the ones in the security-advisories repo are ordered nominally based on the package which has the vulnerability. Is it supposed to be like, all vulnerabilities will be added one by one to the sec-wg repo and they will be sorted in the sec-advisories repo ?

**Comment by lirantal** [comment]
>I assume that once security-advisories is live, https://github.com/nodejs/security-wg/tree/master/vuln will be deleted?

Yep.

@waveywaves thanks, that would be great.

**Comment by fraxken** [comment]
Closing the issue since that it has not moved since 2018.
