### ISSUE TITLE
issue a vulnerability to address event-stream

### ISSUE THREAD

**Issue by mcollina** [nodejs/security-wg#444]
Please review https://github.com/dominictarr/event-stream/issues/116 and https://github.com/dominictarr/event-stream/issues/115.

**Comment by bnb** [comment]
There was a comment by someone from Snyk (Danny?) that they'd submitted it to the hackerone.

**Comment by dgonzalez** [comment]
This is done: https://github.com/nodejs/security-wg/pull/445. I will close this issue. H1 report has been managed (thanks Danny!) and vulnerability is about to be merged to the DB.
