### ISSUE TITLE
Add tests to the reporter tooling

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#447]
# What

The reporter tool the community uses is missing tests to ensure it is working properly as contributors modify and refactor it.

- [ ] Add tests for `tools/reporter` 
- [ ] Update travis CI accordingly

Notes:
- The tooling will move soon along with the vulnerability database to their new home: https://github.com/nodejs/security-advisories. It should be ok to go ahead and PR on that repo directly.
- Please chime in on the thread to ask about being involved to avoid duplicate work instead of silently working on this and submitting a PR.

**Comment by waveywaves** [comment]
I'll write the tests for  the reporter. Let me know if there are any things I might have to keep in mind for the same.

**Comment by lirantal** [comment]
Go go jest!

**Comment by waveywaves** [comment]
Opened a PR at https://github.com/nodejs/security-wg/pull/459

**Comment by sam-github** [comment]
https://github.com/nodejs/security-wg/pull/459 landed
