### ISSUE TITLE
Add tests to the vulnerabilities format validator

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#448]
# What

The vulnerabilities format validator tool is used in CI to ensure that all the vulnerability reports are well formatted to suit the security-wg agreed-upon format.

- [ ] Add tests for `tools/vuln_valid` 
- [ ] Update travis CI accordingly

Notes:
- The tooling will move soon along with the vulnerability database to their new home: https://github.com/nodejs/security-advisories. It should be ok to go ahead and PR on that repo directly.
- Please chime in on the thread to ask about being involved to avoid duplicate work instead of silently working on this and submitting a PR.

**Comment by waveywaves** [comment]
I will be writing tests for vuln_valid. Do we need to mock`joi` to test this ?

**Comment by lirantal** [comment]
🎉

Don't mock joi, just give the vuln_valid code mocked input and confirm that it fails/succeeds based on expectation.

**Comment by waveywaves** [comment]
Opened a PR at https://github.com/nodejs/security-wg/pull/471
