### ISSUE TITLE
Add new migration tool to transform the report id

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#449]
# What

The RFC stated in https://github.com/nodejs/security-wg/issues/402 has proposed to convert the existing report id from a manual incremental numbering to a randomly generated id. The issue holds all the details with regards to the change to be implemented.

It is required to create a migration tool similar to the existing set that we have in `tools/migration` that will be able to convert all the current issues to the new format.

Notes:
- The tooling will move soon along with the vulnerability database to their new home: https://github.com/nodejs/security-advisories. It should be ok to go ahead and PR on that repo directly.
- Please chime in on the thread to ask about being involved to avoid duplicate work instead of silently working on this and submitting a PR.

**Comment by waveywaves** [comment]
Will be working on this. Do let me know if there is anything else I need to go through apart from #402 .
I have understood that the new format should be like 

`{
  "id": "NSWG-ECO-zu96s5c0",
  "// rest of the fields": ""
}`

where "zu96s5c0" in the above id field has been obtained after running the command `new Date('2059').getTime().toString(36)`.

Instead of that we would just have to run `new Date().getTime().toString(36)` right ?
or do we have to pass the date and time of submission of the vulnerability. Does that make sense ?

**Comment by lirantal** [comment]
There are 2 parts to this migration:

1. New reports should indeed use `new Date().getTime().toString(36)` when they get created so there is no meaning of deriving it from other fields
2. Old reports - for the scope of this change we currently don't want to change old reports, but we might do so in the future, and so if you can work on that migration that will be great. For that - I would indeed feed it the date of the `created_at` field, however, notice that this is only a date field without a time provided, and if two reports are created on the same day (very much likely) we will get the same id generated which will result in a conflict. To mitigate that I'd spice up the date with any value of time too and keep a record of all the previously created times so you can compare against previously generated ids and if that's the case then spice up again the time for that day.

**Comment by fraxken** [comment]
@lirantal Should we close this issue ? Feel like things around the db are outdated.

**Comment by lirantal** [comment]
Yes, this needs to be closed as we've yielded the whole database and security disclosure program out to Snyk. Thanks for following up on it!
