### ISSUE TITLE
New format for core vulns

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#452]
In https://github.com/nodejs/security-wg/pull/450 @rvagg gave ideas about how to update the format for core vulns. 
Does anyone want to champion this topic?

**Comment by pxlpnk** [comment]
I think aligning it as much as possible with the ecosystem vulns make the most sense.

**Comment by thoqbk** [comment]
@vdeturckheim I can want to work on this. Can you give me some guidance?

**Comment by lirantal** [comment]
👋 hi @thoqbk 
this is a pretty old issue that has been superseded with https://github.com/nodejs/security-wg/issues/200

would you like to review that #200 issue that has already received some work and see what is left to pick up?

**Comment by thoqbk** [comment]
@lirantal thanks, I will check #200

**Comment by lirantal** [comment]
Cool thanks. I'll close this issue then.
