### ISSUE TITLE
Coinminer in libraries

### ISSUE THREAD

**Issue by danielcaime** [nodejs/security-wg#456]
malware detected Coinminer
![npm](https://user-images.githubusercontent.com/34689906/49442188-7fc4c080-f7a7-11e8-9b74-a7452d4edad3.jpg)
.JS.MALBEC.AA.component
index.min.js
data.js

this files are gets from npm by commandline

**Comment by SomeoneWeird** [comment]
What package are these files from?

**Comment by lirantal** [comment]
Thank you @danielcaime for contacting us!

Joining @SomeoneWeird's asks - can you give us more information about what node package is exactly triggering the anti virus alert? This can be referred to from the file path that shows up in `node_modules`. Basically any kind of information you can provide us to look into the problem will help to understand what exactly is triggering the alert and why.

**Comment by lirantal** [comment]
the vulnerable `flatmap-stream` package also had a `data.js` file so pretty reasonable estimation that this is what the alert is detecting.

**Comment by danielcaime** [comment]
data.js
index.min.js
xxx no name

C:\Users\154232\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\94\0a
C:\DESARROLLO\Node\chat\node_modules\flatmap-stream\test
C:\DESARROLLO\Node\chat2\node_modules\flatmap-stream





Daniel Caime.
________________________________
De: Liran Tal <notifications@github.com>
Enviado: martes, 4 de diciembre de 2018 15:29
Para: nodejs/security-wg
Cc: danielcaime; Mention
Asunto: Re: [nodejs/security-wg] Coinminer in libraries (#456)


the vulnerable flatmap-stream package also had a data.js file so pretty reasonable estimation that this is what the alert is detecting.

**Comment by danielcaime** [comment]
this is package.json

{
  "name": "chat",
  "version": "1.0.0",
  "description": "web-chat",
  "main": "index.js",
  "scripts": {
    "start": "nodemon server/index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "chat",
    "node",
    "sockets"
  ],
  "author": "dcaime",
  "license": "ISC",
  "dependencies": {
    "express": "^4.16.4",
    "socket.io": "^2.1.1",
    "socket.io-client": "^2.1.1"
  },
  "devDependencies": {
    "nodemon": "^1.18.4"
  }
}



Daniel Caime.
________________________________
De: Daniel Caime <caime.daniel@outlook.com>
Enviado: martes, 4 de diciembre de 2018 17:02
Para: nodejs/security-wg; nodejs/security-wg
Cc: Mention
Asunto: RE: [nodejs/security-wg] Coinminer in libraries (#456)

data.js
index.min.js
xxx no name

C:\Users\154232\AppData\Roaming\npm-cache\_cacache\content-v2\sha512\94\0a
C:\DESARROLLO\Node\chat\node_modules\flatmap-stream\test
C:\DESARROLLO\Node\chat2\node_modules\flatmap-stream





Daniel Caime.
________________________________
De: Liran Tal <notifications@github.com>
Enviado: martes, 4 de diciembre de 2018 15:29
Para: nodejs/security-wg
Cc: danielcaime; Mention
Asunto: Re: [nodejs/security-wg] Coinminer in libraries (#456)


the vulnerable flatmap-stream package also had a data.js file so pretty reasonable estimation that this is what the alert is detecting.

**Comment by lirantal** [comment]
Thanks for all the input!

The issue looks to be related indeed to the recent malicious package that was triaged by the Security WG. You can find our report for it and the full disclosure on HackerOne here: https://github.com/nodejs/security-wg/commit/52745f7283bb5f7a07f809bd946be013cbd1c5c4

**Comment by lirantal** [comment]
Daniel I'm closing as there's nothing specific for us to do here.
If you need any further help on how to mitigate the issue on your side you're welcome to re-open it.
