### ISSUE TITLE
Secure Node

### ISSUE THREAD

**Issue by prettydiff** [nodejs/security-wg#457]
Feature Request

I would like to propose Node as an official development platform within the US Army.  In order for this to happen I would need Node to be a bit more locked down.  Could there be a more secure subset of node so that the following features require administrative privileges?

* npm
* file system (fs, path)
* network access (net, http, https, http/2, udp)

In a secure platform Node would be available to regular users without the above features.  Attempting to access those features in code without administrative access would throw an error.  Using an administrative console or sudo those features would be available just the same as they are today.

**Comment by prettydiff** [comment]
@mikesamuel Thank you for your time.  I will have to play around with this.

**Comment by fraxken** [comment]
👋 Hello,

Some work is currently happening here: https://github.com/nodejs/security-wg/issues/791

I guess it will solve some of the concerns raised by this old issue/proposal.
