### ISSUE TITLE
Advice regarding issue

### ISSUE THREAD

**Issue by benjamingr** [nodejs/security-wg#458]
Hey, I got an issue in https://github.com/petkaantonov/bluebird/issues/1567 regarding a possible security issue.

I don't think it's a big deal but I want to make sure that I'm being responsible about it as bluebird has 8 million weekly downloads.

cc @nodejs/security-wg

**Comment by lirantal** [comment]
thanks for pinging us benji
let's take the discussion on the original thread as I have some questions to raise with the user. your familiarty with the project will be useful for some of the questions.

**Comment by sam-github** [comment]
Should this be closed now? It looks as if the discussion was sensitive, and moved to a private channel.

**Comment by lirantal** [comment]
Yes, closing this due to an issue opened on the other repo and we outlined all the details there. No expected work on our side at this point.
