### ISSUE TITLE
feature request for `require.pure(id)` or `pkg.pure:true`

### ISSUE THREAD

**Issue by LongTengDao** [nodejs/security-wg#467]
Feature request.

Most third part module we are using are pure function things. If we can control that (when we require them even install them), then maybe most security problems could under control easily?

"pure module require" means:
1. no i/o, like `fs`, `net` native module.
2. no context pollute, like viciously rewritting to standard lib and native module exports.
3. other things, like `Buffer.allocUnsafe`, `child_process` API.
4. `pkg.scripts` field actions will have no chance to attack the computer.
5. pure module can only require pure module.

soft additional design objective:
1. maybe we need "pureAsync", different with "pure(Sync)", to give a way auto force run in "Worker"-like thing, to protect "while ( true ) ;" (and bind to cpu different with main app context). not very important, because it's almost no benefit for author, and easy to be found by the most careless user (no different with a lib has no user just because it's too slow).
2. maybe we need consider "import" solution together, like "import mod from 'x' assert { pure: 'sync' }".

**Comment by LongTengDao** [comment]
@vdeturckheim My pleasure. But I'm an userland coder, I have no idea about the engine level things. If I can help you in any case, tell me and I'll be glad to do something.

**Comment by hax** [comment]
@LongTengDao It's a very interesting idea. I plan to first try to figure out whether we can implement it in user land (though I don't know how to achieve point 4.)

**Comment by LongTengDao** [comment]
> though I don't know how to achieve point 4.

Thank you, predecessor!

We usually inevitably use scripts field for self building after install it. We can limit it can only use `fs` module under the module directory, in addition to this, the scripts must run in "pure" mode.

**Comment by LongTengDao** [comment]
> This is a good idea, but we need a SES-like protection to prevent the globals tempering. I need to check what is the status here.

@vdeturckheim I can't find information about "SES" by Google, what does that mean? And I found "[Chrome Content Scripts](https://developer.chrome.com/extensions/content_scripts#execution-environment)" in [Electron docs](https://electronjs.org/docs/api/browser-window), do you mean that? Thanks!

**Comment by vdeturckheim** [comment]
@LongTengDao sure, here is a wiki page https://github.com/google/caja/wiki/SES

you can also check the current state of the realms proposal on TC39 https://github.com/tc39/proposal-realms

**Comment by LongTengDao** [comment]
@vdeturckheim Oh, it's cool! Realms is good for plugins of software like vscode. Maybe it's a solution behind require, but I can't see how to use it directly for most module requiring without support of node, am I right? Should we wait realms for meeting this need, or still do it with SES at now?

**Comment by LongTengDao** [comment]
I found a related repo today: https://github.com/secure-require/secure-require

Hope it works, if it's possible in userland.

**Comment by LongTengDao** [comment]
@vdeturckheim <https://github.com/tc39/proposal-shadowrealm/issues/347> realms proposal seems won't do what here said, it's still a sticky problem

**Comment by hax** [comment]
@LongTengDao Yeah, shadow realms itself can not satisfy what u want in this issue, though it could be the basis of SES in long term. Currently it seems very hard to achieve point 2 without performance burden.

**Comment by LongTengDao** [comment]
@hax if performance burden is the main problem, then maybe here is a compromise way:

imagine an app, has two directly third-party dependency we call them "x" and "y" here, which expeced to be pure, and "x" has 100 dependencies behind it, "y" too.

then we can only create two isolated context, one for "x" and all it's dependencies, one for "y" and all it's dependencies, that means there is no need to create 202 isolated contexts.

because "pure module" idea mainly protect the main business part, and not intended to promise lib work completely right, including a lib is broken by it's furthur dependencies.

above based on that, "performance burden" you said refer mainly to "create context", not for "run in context". if you mainly mean "run in context", I don't know much, I can only imagine that by "Proxy", I think a cost like "Proxy" is not "too heavy"?

**Comment by LongTengDao** [comment]
*still waiting to discuss*
