### ISSUE TITLE
Security WG meeting 2017-10-12 (bumped a week later)

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#47]
There would normally be a WG meeting this Thursday, Oct 5th, but its in the middle of NINA, and many participants may be unavailable, and some may only be available for a Working Group session (https://github.com/nodejs/summit/blob/master/2017-10/agenda.md#2017-10-06-day-one) in the afternoon.

I propose we bump the meeting by a week to October the 12th.

cf. https://github.com/nodejs/security-wg/issues/44

**Comment by cjihrig** [comment]
I'll be on vacation the week of the 12th, but obviously that shouldn't stop the meeting from happening. I'm in favor of canceling this week due to NI.

**Comment by mhdawson** [comment]
+1 for moving out a week.

**Comment by joshbw** [comment]
sure

**Comment by gibfahn** [comment]
So this will be at 19:00 UTC on October 12th (exactly 1 week after the previous meeting) AIUI.

@Trott or @mcollina could you update the calendar?

**Comment by sam-github** [comment]
@mhdawson also has the power of the calendar

**Comment by Trott** [comment]
Added.

I think @williamkapke can add people to the calendar, and I don't think there's any rules or restrictions. So I imagine if you're scheduling meetings for a WG or even a proto-WG like this, you can probably get added to the calendar. I'm happy to handle the calendar requests for you, though, if you'd rather not deal.

**Comment by gibfahn** [comment]
I end up doing a lot of the meetings for Build and Release, so would love Calendar privileges.

**Comment by williamkapke** [comment]
I've created: https://github.com/nodejs/admin/pull/17

@gibfahn we can def get you added! I just found your gmail address and added it. LMK if you have any trouble.

**Comment by vdeturckheim** [comment]
closing in favor of https://github.com/nodejs/security-wg/issues/52
