### ISSUE TITLE
CNA summit

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#472]
Hello CNAs,

 

Happy Holidays! 

 
From the CNA mailing list: 

We plan to hold two CNA summits early next year, the first will be virtual and the second will be face-to-face. This will provide CNAs with the time to discuss the many pressing issues that they are encountering as the program continues to grow and evolve. 

Please click the link below and select the dates you will be available.

SUMMIT 1 - VIRTUAL

Weeks of: 

February 4th – February 8th

February 25th – March 1st

If somebody is interested in representing Node.js and our work as an CNA please let me know.

**Comment by lirantal** [comment]
I would recommend @vdeturckheim for all the work that has been put for the H1 program and acting as a CNA for ecosystem modules.

**Comment by cjihrig** [comment]
+1 to @vdeturckheim if they are OK with it.

**Comment by vdeturckheim** [comment]
LGTM thanks for this! I need to sync up with Sqreen too

**Comment by mcollina** [comment]
+1!

**Comment by mhdawson** [comment]
@vdeturckheim I'll send you the email with the link to select dates.

**Comment by mhdawson** [comment]
@vdeturckheim also if you are interested in getting the regular emails from the Mitre you can PR yourself into: https://github.com/nodejs/email/blob/master/iojs.org/aliases.json

In the cve-mitre-contact and cna-discussion-list sections.

**Comment by mhdawson** [comment]
Closing for now.
