### ISSUE TITLE
NINA lunch or dinner

### ISSUE THREAD

**Issue by joshbw** [nodejs/security-wg#48]
Anyone have availability to meet up for lunch or dinner tomorrow? We're looking at a get together to talk WG business at the collab summit, but since we are collaborating together I think an event to get to know each other outside of simply talking business also makes sense.

And on that note, for people who do want to meet up, any cuisines you have strong opinions on, either good or bad?  I'll eat most anything, though particularly love the breadth of east Asian cuisines (Sushi, Thai, Vietnamese, Dim Sum, etc.).  I'd be happy to make reservations tomorrow morning when I have a sense for how many folks we are talking about, availability (lunch, dinner) and food preferences.

**Comment by vdeturckheim** [comment]
I love the idea but sadly I'm on booth duty with Sqreen all day (please pass by and say hi ;) ).

Although, I should be available for dinner.

**Comment by joshbw** [comment]
I'm free for dinner, and I'll swing by and say high.

**Comment by sam-github** [comment]
I'm free for dinner as well, shall we go after the keynote? I suggest anyone interested meet at the registration booth after the keynote, which looks like it will be a bit before 6pm today (thursday).

I've a few ideas on places to go, depending on how far we want to walk.

**Comment by vdeturckheim** [comment]
lgtm!

**Comment by evilpacket** [comment]
I’m down for dinner.

**Comment by joshbw** [comment]
Sounds like a plan

**Comment by gibfahn** [comment]
SGTM

**Comment by bengl** [comment]
i'm in

**Comment by joshbw** [comment]
It was great meeting you all in person.
