### ISSUE TITLE
Nominate myself Ron Perris to join the Security WG and Triage team

### ISSUE THREAD

**Issue by ronperris** [nodejs/security-wg#490]
Hi @nodejs/security-wg,

I'd like to humbly nominate myself @ronperris to the WG to help triage reports on third-party modules in the Node.js ecosystem.

I see two things I can help with in 2019:
* Improve response standards and reopen the Hackerone reporting channel. ([Closed due to lack of triage activity](https://hackerone.com/nodejs-ecosystem))
* Improve CVE issuing timelines and process. #97 #468

Why let me join?

I want to help with Node.js ecosystem security.

I write courses on secure coding techniques in JavaScript for [Synopsys](https://www.synopsys.com/software-integrity/training/elearning.html). 

I co-founded and help run a [software security conference](https://locomocosec.com/) focused on building software securely.  

I've worked for a commercial [vulnerability management company in Sweden](https://outpost24.com/) for 6 years, as their CTO. Thousands of companies still rely on the risk scoring and classification systems we operated.

**Comment by MarcinHoppe** [comment]
+1 from me. I think the triage team could use more people.

**Comment by lirantal** [comment]
Definitely. I think Ron's experience in this field can help us, as well as his community insights as we try to improve on how we engage with the community too.

**Comment by mhdawson** [comment]
+1 agree more help would be good.

**Comment by vdeturckheim** [comment]
+1 here too!

**Comment by ronperris** [comment]
@nodejs/security-wg I've read and agree to follow the [Code of Conduct](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md).

**Comment by mhdawson** [comment]
@ronperris I think the next step would likely be a PR adding yourself to the list in the README.md
