### ISSUE TITLE
[ANN - APR 26th 2019] Migrating vulnerabilities database into its own repository

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#494]
As planned in #359, the content of the vulnerabilities is migrated to their own repository.

Starting **April 26th 2019**, all PR of new vulnerabilities will be performed in the new repository: https://github.com/nodejs/security-advisories.

On **May 26th 2019**, we will remove the vuln directory and it's content from this repository.

Please reach to anyone you know who might be using this dataset to share this roadmap.

I added the `security-wg-agenda` label to ensure this is mentionned to the next meetings of the WG.

**Comment by sam-github** [comment]
This is on agenda to make sure this is mentioned:

> On May 26th 2019, we will remove the vuln directory and it's content from this repository.

But the time is past. Maybe we can take off agenda?

**Comment by mhdawson** [comment]
I think we can just close the issue.  Closing, please let me know if it should still be open.

**Comment by sbs2001** [comment]
What's the status on this ? The advisories are still at this repo, and https://github.com/nodejs/security-advisories seems to be outdated.

**Comment by vdeturckheim** [comment]
@sbs2001 we never concluded on this and the WG is not handling ecosystem vulnerabilities anymore.
