### ISSUE TITLE
Reopen the Official HackerOne Report Channel for Third-party Module Vulnerabilities

### ISSUE THREAD

**Issue by ronperris** [nodejs/security-wg#497]
## Summary
The [reporting channel for third-party module vulnerabilities](https://hackerone.com/nodejs-ecosystem) has been mostly(totally?) paused since November of 2018.

![image](https://user-images.githubusercontent.com/963451/53660653-3b648780-3c13-11e9-9bb2-c1c16d4ca193.png)

The reason the program is paused is because the team has not met the [published](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md) service level agreement for triaging vulnerabilities that are reported within 2 days.

The current report [triage time](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md#triage) is 11 days, and the published process requires all triage activities to be completed in 2 business days.

As a new member of the team, I see a few reasons that triage might not be happening within 2 business days.

1. The [triage process document](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md#triage) incorrectly documents the steps that are required to triage a vulnerability report.
2. Triage team members do not have appropriate access permissions to complete the triage steps.
3. The program lacks visible accountability to published standards.

## Solution Steps
- [ ] Fix the process documentation to reflect the actual steps required to triage a vulnerability. #498 
- [ ] Fix the permission settings on HackerOne to allow team members to complete the triage steps. #499  
- [ ] Make compliance with published standards more visible to team members.

**Comment by lirantal** [comment]
I reached out to H1 support to ask them to re-enable it again.
Would love to see what you had in mind for bullet 3 but other than that I think we don't need to keep this issue open as it is. As in, no other action items to take in a public manner to re-enable the program.
