### ISSUE TITLE
Update Third-party Triage Team Permissions in HackerOne

### ISSUE THREAD

**Issue by ronperris** [nodejs/security-wg#499]
## What I expected
To be able to complete the triage process steps as a member of the triage team.

## What I experienced
My account and the most of the other team members accounts lack the permissions required to triage a vulnerability because we can not add assets.

## Solution
- [ ] Add the `Program` permission via groups on HackerOne to all triage team members, checkout the docs [here.](https://docs.hackerone.com/programs/groups-and-permissions.html#___gatsby)

**Comment by lirantal** [comment]
@ronperris I replied on this internally on our slack channel with my concerns for this.
Happy to discuss further first on a closed channel since this is detailing more data that I'm not sure we should be discussing publicly.
