### ISSUE TITLE
In-person kick-off at Collaborator Summit this week

### ISSUE THREAD

**Issue by rvagg** [nodejs/security-wg#5]
Full agenda of summit: https://github.com/nodejs/summit/issues/35

Will try and figure out location. Feel free to jot down some ideas for discussion here.

**Comment by mcollina** [comment]
Let me add my point of view: help module authors address high-impact security vulnerability. Having a trusted group of people that can provide help and guidance will help the ecosystem.

**Comment by joshgav** [comment]
Notes: https://docs.google.com/document/d/1-gY_sNt4CgySEale_13e2n9S9ucjuoM7djCq3Njal-0

**Comment by sam-github** [comment]
https://github.com/nodejs/security-wg/pull/10

**Comment by joshgav** [comment]
PR landed for notes so closing this now. Thanks!
