### ISSUE TITLE
I would like to join

### ISSUE THREAD

**Issue by codepilot** [nodejs/security-wg#50]

**Comment by vdeturckheim** [comment]
I have not objection so :+1:

**Comment by sam-github** [comment]
@nodejs/security-wg this will be discussed at next WG meeting, if there are no objections, we'll assume consensus on adding @codepilot to the WG, per https://github.com/nodejs/security-wg/blob/master/GOVERNANCE.md#wg-membership

**Comment by sam-github** [comment]
Approved in todays meeting. @codepilot , PR your name to the WG members in the README
