### ISSUE TITLE
IoC for advisories

### ISSUE THREAD

**Issue by DanielRuf** [nodejs/security-wg#501]
So far we have no IoC (Indicators of Compromise) of malicious packages.

In general this would be helpful for creating YARA rules and other solutions.

https://www.npmjs.com/advisories/774

**Comment by MarcinHoppe** [comment]
@DanielRuf This is an interesting topic to discuss. Do I understand correctly that you want to create Yara rules for packages that were identified as malware and not "just" vulnerable?

**Comment by DanielRuf** [comment]
> @DanielRuf This is an interesting topic to discuss. Do I understand correctly that you want to create Yara rules for packages that were identified as malware and not "just" vulnerable?

Exactly. It could be also helpful for vulnerable packages (hashes and code parts) but it's less relevant then.

Think about someone reuploading malicious files and code snippets (which I did) and which are not automatically detected by npm. In this case a search with YARA rules based on indicators of compromise might catch these.

**Comment by MarcinHoppe** [comment]
Ideally this detection would be handled at the package repository level, correct?

**Comment by DanielRuf** [comment]
So far there is no detection ;-) But this is a different problem / topic.

But we are a bit off-topic, IoC information is still something that I miss in advisories.

The question is probably which information we need there (hashes, strings, filenames, IPs, domains, ...).

I think this can only be obtained from an analysis / incident report of the actual malware then and what it does.

**Comment by MarcinHoppe** [comment]
We'd definitely need to collaborate with or delegate it to some body that has this sort of information (CERT) but I think it would be valuable addition to advisories.

@nodejs/security-wg Do you think this _should_ become part of our charter?

**Comment by lirantal** [comment]
I like the idea I'm just worried, or not entirely sure we are able to sustainably maintain that but I like the idea.

If there's interest in adding that into [npq's](https://github.com/lirantal/npq) marshalls or turning them into YARA rules then I'm all happy to experiment with that.

**Comment by MarcinHoppe** [comment]
I have a similar concern. We do not own npq as a WG, so that would be a separate initiative.

**Comment by lirantal** [comment]
Yep. Was suggesting npq as a good place to experiment with this on.
Also, I'm happy to consider moving the npq project under the foundation's ownership, that's actually not a terrible idea at all!

**Comment by DanielRuf** [comment]
@lirantal I guess for this it would be probably the best to reuse real YARA rules then and spawn a YARA instance.

I have hacked a simple example at https://github.com/DanielRuf/yara-childprocess
Also see https://github.com/VirusTotal/yara/issues/1045

Or what do you think?
YARA is powerful and depending on the bundled modules (yextend binaries might be also helpful) is often better than writing a solution from scratch.

By the way, ClamAV for example supports YARA rules (with some limitations) and returns the proper exit codes.

See https://travis-ci.com/DanielRuf/clamav-test/builds/105412604 and https://github.com/DanielRuf/clamav-test/blob/master/.travis.yml

**Comment by lirantal** [comment]
That's pretty nice but how does it handle data that doesn't strictly exist on the file being looked at? For example, one of the heuristics for npq is to find out how many downloads a module has, or if it has an SCM repository URL assigned, etc.

**Comment by DanielRuf** [comment]
> That's pretty nice but how does it handle data that doesn't strictly exist on the file being looked at? For example, one of the heuristics for npq is to find out how many downloads a module has, or if it has an SCM repository URL assigned, etc.

I guess we have different ideas. I mean file based IoC information (file hash, file content, ...). Like normal antivirus solutions do it. And this is also what my issue is about. You can only check such things after the download, not before.

**Comment by DanielRuf** [comment]
> That's pretty nice but how does it handle data that doesn't strictly exist on the file being looked at? For example, one of the heuristics for npq is to find out how many downloads a module has, or if it has an SCM repository URL assigned, etc.

I guess we have different ideas. I mean file based IoC information (file hash, file content, ...). Like normal antivirus solutions do it. And this is also what my issue is about. You can only check such things after the download, not before.

**Comment by DanielRuf** [comment]
Keep in mind that npm unpublishes malicious packages which they found or have got the info about them.

In all other cases where someone reuploads the same under a different package name and npm do not know about it (yet) or when you want to audit an existig project this is different.

**Comment by DanielRuf** [comment]
> or if it has an SCM repository URL assigned

Which is not used in many cases as `npm publish` can upload completely different things and this us just some metadata. There is no check if the published files are the same like the repo files (and if they are signed, ...).

**Comment by lirantal** [comment]
I completely understand your idea of being only file-based, just that I think the two ideas are complementary, not conflicting :)

An SCM repository URL may indeed not be used, which is why it may flag some warning for users.

**Comment by DanielRuf** [comment]
I think we can close this issue. Sonatype, Snyk, GitHub and others probably will handle such information in reports and internal databases.
