### ISSUE TITLE
should there be security-wg presentation at nodeconf.eu?

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#504]
- conf: https://www.nodeconf.eu/
- call for sessions: https://sessionize.com/nodeconf-eu-2019

@mhdawson suggested a panel discussion or presentation by the WG might be interesting, is anyone interested in putting together such a proposal?

**Comment by lirantal** [comment]
Sounds good. We had one last year too at Node.js Interactive.

What would be some interesting topics for us to cover?
Some ideas for things we can put together for either a panel or a talk:
1. Share some H1 stats (this is something that I've been meaning to put together and share around anyway) regarding vulns, number of disclosures, avg time of fix, etc.
2. We could evangelize on some recent work around security-related topics for Node.js such as the experimental integrity policies, process-wide access control and others
3. Other ideas we had in the past was about bringing to a panel a maintainer point of view as well as a bug hunter and running that discussion.
4. Intro about CVEs, how does triage work, the processes we go through, CVSS, etc - could prove useful and interesting for devs and maintainers who wish to get more insight into this

**Comment by MarcinHoppe** [comment]
I was thinking about submitting a session and if it is selected, doing a panel would be pretty awesome :).

**Comment by vdeturckheim** [comment]
In for a panel (btw, we probably want to set on up for Node Summit and Node+JS interactive this year too)

**Comment by mhdawson** [comment]
I agree, getting together a plan/set of submissions for the 3 main conferences this year would be good,

**Comment by sam-github** [comment]
@mhdawson what are the 3 main conferences? Would it be a panel for each?

Does anybody have a link to (or text) for previous panels? What would be discussed, and who would be on the panel?

**Comment by mhdawson** [comment]
@sam-github I think whatever makes sense for each conference.

**Comment by vdeturckheim** [comment]
Closing as the event is over now

**Comment by vdeturckheim** [comment]
CFP is closed.

**Comment by mhdawson** [comment]
Since CFP is closed I don't think there is too much to discuss on this front, closing.
