### ISSUE TITLE
Threat model

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#51]
In https://github.com/nodejs/node/issues/15564#issuecomment-335424327 @hashseed proposed that a threat model would be defined as framework for evaluating the severity of future vulnerabilities.

What are your opinions on that topic?

**Comment by sam-github** [comment]
I've never seen a threat-model for a runtime, but I'd imagine python, ruby, and node would all have similar ones, if it was documented anywhere. Does anyone have a reference to another platform's threat model?

I used python's docs as a model for https://github.com/nodejs/node/pull/14485

**Comment by vdeturckheim** [comment]
I think this is good to close. Feel free to reopen.
