### ISSUE TITLE
Attendance in the upcoming Collaborator Summit in May?

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#510]
Any of us is expected to make an appearance on the upcoming Node.js Collaborator Summit in May? (I unfortunately can't make it due to extensive travel already planned for me but will plan  for the one in Node+JS Interactive)

Follow-ing up on https://github.com/nodejs/summit/issues/155 we could take more active part in the conversation and such. There are quite a few open things that we can push forward from the issue queue list.

**Comment by mhdawson** [comment]
I'm going to be there.

**Comment by vdeturckheim** [comment]
Sadly, I'll be giving a talk at OWASP conference in Tel Aviv at the same dates.

**Comment by lirantal** [comment]
Mini Sec WG summit 💕

@mhdawson Would love it if you could create some engagement with the rest of the foundation around things we do and our challenges. I'm wondering if you'd be too busy with other WG and general TSC things going on as you're kinda all over the place :)

**Comment by mhdawson** [comment]
If the team put's together some slides we might see if there is an opportunity to present something like a lightning talk.  I'm also trying to get Sam there so hopefully one of the 2 of us could present it

**Comment by sam-github** [comment]
I can present slides, but I'm not working on package security, so I don't have much to say about the topic.

@lirantal 

> There are quite a few open things that we can push forward from the issue queue list.

Where is the list? I just skimmed through https://github.com/nodejs/security-wg/issues/ and I think it needs some pruning.

**Comment by lirantal** [comment]
Let's try to figure out who is actually there.
@nodejs/security-wg can you please +1 on this comment or the top one if you are attending the collaborator summit? Would also be great if you can comment with topics you'd like to present.
