### ISSUE TITLE
Reaching out to other projects of the OpenJS Foundation

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#511]
We should probably start to reach out to other projects in the Foundation to check which ones would be interested in building a larger security community around JavaScript.

Do we have any way to setup such discussion?

**Comment by mhdawson** [comment]
One the CPC is established there will be representatives from each of the projects and it should be pretty easy.  At this point @jorydotcom would be the best intermediary.  It might be good to wait for the CPC to ramp up but if we want to start earlier than that then we could start by reaching out to Jory for contacts.

**Comment by vdeturckheim** [comment]
@mhdawson thanks for the clarifications! Let's wait for the CPC indeed.

**Comment by jorydotcom** [comment]
@vdeturckheim in the interim I can sent an old-fashioned email to our old-fashioned JSF mailing list pointing folks to this repo!

**Comment by vdeturckheim** [comment]
@jorydotcom thanks a lot! Let's discuss this in our next meeting!

**Comment by christian-bromann** [comment]
I am in 💪

**Comment by sam-github** [comment]
Discussed at #541 , removing from agenda (but please add back if it should be discussed again).

**Comment by sam-github** [comment]
related: https://github.com/openjs-foundation/cross-project-council/issues/326

**Comment by mhdawson** [comment]
This was mentioned in the CPC meeting today in the context of openjs-foundation/cross-project-council#326.  I think its the right time to discuss/make a decision on what we think is best.

@nodejs/security-wg what are your thoughts?  I'm thinking it would make sense to have a group at the OpenJS level, and that the ecosystem triage might fit at that level as well.

**Comment by lirantal** [comment]
I think that's a good idea and perhaps that's an additional one on top of the Node.js one. Just a thought, but I figure that at that level there will be many project ecosystems and so processes and systems (i.e: H1) might vary. So to say, I don't think we'd be copy&pasting the Node.js Security WG to the OpenJS as-is.

**Comment by MarcinHoppe** [comment]
If I understand things correctly, the scope here is slightly different: for the Node.js ecosystem we are handling responsible disclosure to a large extent and for OpenJS right now we are more interested in having consistent policies across several high profile projects. Then helping those projects out from triage and disclosure perspective (as we do today for Node.js) would be the next step.

@mhdawson @lirantal Does it sounds reasonable?

**Comment by sam-github** [comment]
Feedback from last sec-wg meeting: For this to move forward, it will need a champion, someone willing to follow up with the OpenJS foundation, and keep this moving forward. Do we have a volunteer?

**Comment by jorydotcom** [comment]
@sam-github @mhdawson I'm happy to help broadcast this group's meetings or generally put out a call for participation in the weekly update I send out to the projects email list. Also, we could encourage some discussion in the openjsf slack workspace.

**Comment by MarcinHoppe** [comment]
@jorydotcom I'd love to be a part of this. I already had a preliminary conversation about it with @mhdawson. I will reach out on Slack.

**Comment by sam-github** [comment]
There doesn't seem to be any topic to discuss live, so removed agenda.

If folks want to champion this, they should get involved, it seems reasonable.

**Comment by MarcinHoppe** [comment]
I am already doing some work with the CPC but it's progressing very slowly, mostly due to my availability. I will report back when there is progress.

For now we have a stage 0 proposal about security reporting for OpenJSF projects:

https://github.com/openjs-foundation/cross-project-council/pull/489

**Comment by lirantal** [comment]
Is it worth to create a new doc in `processes/` folder to document progress which you can PR to as things progress and close this one?

**Comment by MarcinHoppe** [comment]
Or perhaps link to process docs being worked on with the OpenJSF CPC?

**Comment by lirantal** [comment]
Yep, good enough too.

**Comment by MarcinHoppe** [comment]
I need to take one more action on the OpenJSF proposal. I will link to that proposal from our docs next week and close this issue then.

**Comment by fraxken** [comment]
@MarcinHoppe can we close the issue ?
