### ISSUE TITLE
Bounty for ecosystem package: pilot program

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#525]
HackerOne suggests we define a list of pilot projects we would mark as eligible for bounties if vulnerabilites are reported into. I have an arbitrary list (based on popularity and how maintained I feel these projects are):

* lodash
* jQuery
* node-red
* ~~Express (all packages under the GH org)~~ (https://github.com/nodejs/security-wg/issues/525#issuecomment-489447509)
* hapi (all packages under the GH org)
* Koajs (all packages under the GH org)
* Webpack
* ESLint
* socket.io

wdyt?

**Comment by lirantal** [comment]
@vdeturckheim this is very much connected to https://github.com/nodejs/security-wg/issues/503 so we can't really start without that being resolved either.

**Comment by dougwilson** [comment]
Based on what has transpired with the finalhandler incident, please do not include Express in this bounty program, as I don't have confidence in the processes that are in place here.

**Comment by lirantal** [comment]
We could probably add some of Matteo's projects to that list as he is pretty active on them as well and they're popular too (/cc @mcollina)

**Comment by vdeturckheim** [comment]
Good point for @mcollina 's repos!

**Comment by mhdawson** [comment]
I'm ok with the list provided we get opt-in by the maintainers.

**Comment by lirantal** [comment]
handled in https://github.com/nodejs/security-wg/issues/593 so closing
