### ISSUE TITLE
Publicizing information about packages using deprecated/insecure buffer APIs

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#544]
@ChALkeR would like to start publicizing some of the information he has gathered on this, as a github repo, but before we do this we'd like to give the community a blog post discussing the current state of affairs, what we think people should do, and what we will be doing soon.

I'll draft a post and get some comment. See #543 and #505

**Comment by fraxken** [comment]
@sam-github Do you still plan to do something or should we close this issue ?
