### ISSUE TITLE
Joining the Security WG

### ISSUE THREAD

**Issue by karenyavine** [nodejs/security-wg#545]
👋 Hey all!

I'd like to nominate myself to joining the Security WG. I've triaged (quite a few) vulnerabilities as part of my work as a security analyst at Snyk and have since changed positions. I would like to help around here when I can :)

**Comment by lirantal** [comment]
I know and have worked with Karen for quite some time now. She had actually triaged one of the security vulnerabilities I reported on to Snyk before I joined the Node.js Security WG. I know she's been a long time lurker here and would really be like to get involved more and have some ideas to contribute.

With her experience in communicating with researchers, maintainers and basically triaging vulns for a couple of years it would be great to have her on the team.

**Comment by sam-github** [comment]
+1, I'm happy to have more people helping out.

**Comment by lirantal** [comment]
cc @nodejs/security-wg

**Comment by MarcinHoppe** [comment]
Sounds amazing! Welcome @karenyavine!

@lirantal is it safe to assume you will onboard Karen to the WG?

**Comment by lirantal** [comment]
Yes definitely.
I'll open a PR soon with all the details and request for review.

**Comment by karenyavine** [comment]
🎉
