### ISSUE TITLE
Onboarding Karen to the Security WG

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#550]
Check-list for onboarding Karen Yavine Shemesh to the Security WG:

- [x] I scheduled an onboarding session with Karen on Thursday 4th of July, will tick this once we've gone through all the docs and processes.
- [x] Karen went through our [CoC](https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md)
- [x] @cjihrig @mhdawson @sam-github @ChALkeR - can one of you please add @karenyavine to this repository?
- [x] @karenyavine has 2FA enabled for GitHub
- [x] @karenyavine to join our Slack group and [identify herself](https://github.com/orgs/nodejs/teams/security-wg/discussions/3)
- [x] @lirantal to add @karenyavine to H1 for triage team

References:
- https://github.com/nodejs/security-wg/issues/545
- https://github.com/nodejs/security-wg/pull/547

**Comment by cjihrig** [comment]
> can one of you please add @karenyavine to this repository?

Invite sent.

**Comment by lirantal** [comment]
Great, thanks.

**Comment by lirantal** [comment]
FYI team that spent time with on-boarding Karen and so I checked the first and last items on the list. @karenyavine once you're done reviewing CoC and vuln process + guidelines we can check the last item and close the issue.

**Comment by karenyavine** [comment]
Done!

**Comment by lirantal** [comment]
All done here, closing.
