### ISSUE TITLE
Update on program eligibility settings

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#577]
This is mostly an FYI but an important one since it came as a feedback from a hacker submitting a report on H1 and expecting a bounty.

Apparently, now that we have the bounty supported when creating new scopes of projects we need to manually toggle off the "eligible for bounty". I don't think a whole lot of us has access to do that but keep in mind anyway to make sure it isn't turned on.

![image](https://user-images.githubusercontent.com/316371/65362597-e0997a00-dbbc-11e9-9482-b486b091ba3c.png)

On the same note, I went ahead and enabled/created the following scopes for bounties per what's currently supported:

![image](https://user-images.githubusercontent.com/316371/65362680-3c640300-dbbd-11e9-806f-c17c27f4b38b.png)

--

We'll go ahead and close this issue in a week's time as this is more of an announcement to make sure everyone are on the loop.

**Comment by MarcinHoppe** [comment]
Thanks @lirantal! Looks good to me.

**Comment by lirantal** [comment]
Great, closing :)
