### ISSUE TITLE
Responsible security disclosures 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#578]
Please comment in https://github.com/openjs-foundation/cross-project-council/issues/326

**Comment by mhdawson** [comment]
@nodejs/security-wg

**Comment by MarcinHoppe** [comment]
Thanks @mhdawson. I think it makes sense and I chimed in in OpenJS foundation repo thread.

**Comment by lirantal** [comment]
Closing for the sake of involvement and activity on the original issue.
