### ISSUE TITLE
Node+Interactive Security WG Agenda

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#586]
Let's use this issue to track all the suggestions and recommended agenda for Security WG in upcoming Collab Summit in Node+Interactive Montreal.

-- Update 13/12/2019
Participants: @lirantal @ChALkeR @vdeturckheim 
Working Items and Discussions:

1. Bug Bounty Criteria - agreed and confirmed on current guidelines that we've set via https://github.com/nodejs/security-wg/pull/603 , https://github.com/nodejs/security-wg/issues/593 and https://github.com/nodejs/security-wg/issues/525
2. Buckets and Prioritization - we are thinking that the current bucket order helps and a step in a good direction but we want to further improve it. Right now we have 2 buckets: `Low priority <100 d/l weekly` and `High priority >100 d/l weekly` and current stats are 30 vs 36 respectively. So it helps, but we'd like to also make sure we don't starve the reports in >100 that are affecting a good part of the ecosystem (i.e: >100000 downloads). To be discussed in https://github.com/nodejs/security-wg/issues/604
3. Membership activity / On-boarding Program - discussed that many triage group members are existing but not all are actively participating which doesn't improve our state of items in the queue for triage. Related to this topic, we discussed perhaps creating an on-boarding program where we would have members rotating for a 3-6 months on and off the triage team, since we the work can be burning out for most people, and also have a program where members start off with low priority buckets to help them grow with experience and into the "way of things" and then transition to one of the other higher priority buckets.

**Comment by lirantal** [comment]
Idea: We had a call before with Lee Holmes from MS which we can further extend with regards to figuring out what needs to be done, PRs, changes, etc. It can be a small working group to flush all of this out.

**Comment by MarcinHoppe** [comment]
Were the any concrete follow up actions or ideas for improvement after meeting with Lee?

**Comment by lirantal** [comment]
Mostly #604 but we also spent a bit of time cleaning up H1, sorting out the non-queued items (66 of them) into the proper buckets and pulling some stats form npm to figure out thresholds. 
@ChALkeR shared this data from publicly disclosed reports we currently have:

```
downlads/week unknown: 46
downlads/week >= 1: 33
downlads/week >= 100: 5
downlads/week >= 500: 1
downlads/week >= 1000: 16
downlads/week >= 10000: 5
downlads/week >= 100000: 22
```

**Comment by fraxken** [comment]
Closing the issue since the event is over.
