### ISSUE TITLE
Membership review

### ISSUE THREAD

**Issue by MarcinHoppe** [nodejs/security-wg#591]
Before we onboard new members (#581, #582, #583), let's do an annual membership review as agreed in #302.

@aeleuterio -> responded: leaving.
@bengl -> responded: leaving.
@brycebaril -> responded: leaving.
@ChALkeR -> responded: staying.
@cjihrig -> responded: staying.
@dgonzalez -> responded: staying.
@deian -> responded: staying.
@drifkin -> responded: leaving.
@Elexy -> responded: leaving.
@grnd -> responded: staying.
@karenyavine -> responded: staying.
@lirantal -> responded: staying.
@MarcinHoppe -> responded: staying.
@mhdawson -> responded: staying.
@mgalexander -> responded: staying.
@pxlpnk -> responded: staying.
@ronperris -> responded: staying.
@sam-github -> responded: staying.
@SomeoneWeird -> responded: staying.
@vdeturckheim -> responded: staying.

Please confirm by posting a comment on this issue if you plan to continue being active in the Ecosystem Security WG. If we don't hear from you we will move you to emeritus as outlined in #302.

**Comment by vdeturckheim** [comment]
I'd like to saty in.

**Comment by MarcinHoppe** [comment]
I confirm that I want to remain a member of this WG.

**Comment by cjihrig** [comment]
I'd like to stay.

**Comment by lirantal** [comment]
I'd be honored to keep working with this amazing bunch ❤️

**Comment by sam-github** [comment]
I'd like to stay

**Comment by ronperris** [comment]
I'd like to continue.

**Comment by deian** [comment]
+1 I'd like to continue as well

**Comment by mgalexander** [comment]
I would love to continue, but have not managed to see you guys in some time and regret that I probably will not become more available near term. Keep up the great work and I will stay as watcher to participate as/when able and please feel free to reach out if I can be of assistance.

**Comment by grnd** [comment]
I'd love to continue

**Comment by karenyavine** [comment]
+1  would love to continue

**Comment by Elexy** [comment]
-1 count me out

**Comment by pxlpnk** [comment]
I confirm that I want to remain a member of this WG.

**Comment by ChALkeR** [comment]
I'd like to continue =).

**Comment by SomeoneWeird** [comment]
Would like to stay too.

**Comment by MarcinHoppe** [comment]
Thanks to all members who responded within the first 2 weeks!

@aeleuterio @bengl @brycebaril @dgonzalez @drifkin do you plan to stay involved in this WG?

**Comment by MarcinHoppe** [comment]
Another 2 weeks have passed, and I think we can wrap up the annual membership review.

@nodejs/security-wg we have not heard from @aeleuterio @bengl @brycebaril @dgonzalez @drifkin. Do you agree to move them all to emeritus status?

**Comment by lirantal** [comment]
Should we try and reach out to them individually over social as they might have been unable to get these notifications and extend this by 1 week before we move them out to emeritus?

**Comment by dgonzalez** [comment]
I am staying if possible!  I need to reassess the situation on the third party modules (I don't have too much bandwidth) but I am defo interested in the security working grup.

**Comment by MarcinHoppe** [comment]
@lirantal I will reach out individually over the course of the next week and will comment on this issue.

**Comment by aeleuterio** [comment]
Hi folks, apologies for not replying earlier. I have not had the bandwidth to be an active member and unfortunately that will not change in the near future. I will drop now but will follow the great work you do.

**Comment by bengl** [comment]
I don't see myself being active in this WG in the foreseeable future, so please move me to emeritus.

**Comment by lirantal** [comment]
@MarcinHoppe anything else to do here? perhaps let's update per current status and run this again in 6 months time?

**Comment by MarcinHoppe** [comment]
Give me 1 more week to get hold of @brycebaril and @drifkin. Then we can proceed to update the membership and offboard members who decided to step down.

Then we can schedule the next review in 6 months.

**Comment by MarcinHoppe** [comment]
I was able to get in touch with everybody. Next step is move people who voted to leave to emeritus status.

@nodejs/security-wg do you agree with tracking each departure as a separate GitHub issue with a simple checklist based on https://github.com/nodejs/security-wg/blob/master/processes/wg_offboarding.md.

**Comment by lirantal** [comment]
Yes, sounds good @MarcinHoppe and thanks for working this out

**Comment by MarcinHoppe** [comment]
I created the following issues to offboard members that decided to leave the WG:

- #608 
- #609 
- #610 
- #611 
- #612 

I think this issue can be closed now.
