### ISSUE TITLE
Nominating Daniel Ruf to the Ecosystem Triage team

### ISSUE THREAD

**Issue by lirantal** [nodejs/security-wg#614]
Hi @nodejs/security-wg

I would like to nominate Daniel Ruf (@DanielRuf) to join the Security WG and the Ecosystem Triage team specifically.

Daniel has been a long time activist around software security through meetups and conferences, his open source projects on the matter, and [recent security disclosure impacting npm, yarn and pnpm](https://blog.daniel-ruf.de/critical-design-flaw-npm-pnpm-yarn). He is also participating in quite a few open source projects such as verdaccio and gatsby and has a good understanding of the JavaScript ecosystem.

**Comment by lirantal** [comment]
I would also like to add, with regards to recent conversations about activity within the working group, that I have laid out the expectations with Daniel before opening this about being an active triager within the H1 program and this being the primary focus.

**Comment by sam-github** [comment]
+1 for more triagers: :tada:

**Comment by MarcinHoppe** [comment]
👍

**Comment by vdeturckheim** [comment]
Lgtm!

**Comment by DanielRuf** [comment]
Hi, thanks for the nomination =)

Is there some update / news regarding this?

**Comment by MarcinHoppe** [comment]
I think this somehow fell through the cracks. Let me circle back with the team to find an onboarding buddy.

**Comment by lirantal** [comment]
We have +1's it's just that we didn't have any agenda meetings happening recently and we didn't bring this up to confirm, that's all.

Let's make sure we're on it in the upcoming one and if not I'll ping here again for confirmation so we don't delay. Daniel will be an amazing addition to the team and the vulnerabilities queue is only piling up :-)

**Comment by MarcinHoppe** [comment]
The next meeting is on Monday, sounds like we should be able to get Daniel's onboarding moving soon?

**Comment by DanielRuf** [comment]
Any news? =)

**Comment by MarcinHoppe** [comment]
We've had a problem meeting for the last few weeks but I don't think we should wait any longer.

@nodejs/security-wg I think we should proceed with adding @DanielRuf to the WG and the ecosystem triage team without having to wait for the WG meeting to take place. What do you think?

**Comment by lirantal** [comment]
Yes let's proceed with this please, my bad for dropping the ball on continuing here.
This has been open for a while already so I'd assume if anyone wanted to voice against they would've done so already.

If no one objects in the next couple of days let's make it official.

**Comment by lirantal** [comment]
So this has been open for quite a bit and we've got nothing but support on Daniel joining so I'll ping him to run with all the necessary onboarding tasks and I'll buddy him over in terms of training.

**Comment by MarcinHoppe** [comment]
@lirantal This would be amazing, thank you!

@DanielRuf Welcome!

**Comment by MarcinHoppe** [comment]
I think we can close this issue now that @DanielRuf has been onboarded?

**Comment by DanielRuf** [comment]
From my side everything is clear so far and I am already actively working on the HackerOne reports =)

**Comment by MarcinHoppe** [comment]
Cool. Closing then.
