### ISSUE TITLE
Change repo name?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/security-wg#628]
I believe that this group has changed it's name to the "Ecosystem Security Working Group"... I think it would be prudent to change the name of the repo to reflect that./

**Comment by MarcinHoppe** [comment]
I agree. I think we should get a consensus among WG members first and then rename the repo.

**Comment by mhdawson** [comment]
A few things to consider:

* The repo contains the vulnerability database any any effect that will have tools that use the database.  In the past we provide a period of time before making a potentially breaking change like this
* The vulnerability database also contains the core vulns: https://github.com/nodejs/security-wg/tree/master/vuln/core

**Comment by DanielRuf** [comment]
>     * The repo contains the vulnerability database any any effect that will have tools that use the database.  In the past we provide a period of time before making a potentially breaking change like this

By default GitHub creates redirects and these should work in most cases.

**Comment by mhdawson** [comment]
@DanielRuf good point on the redirects.

**Comment by lirantal** [comment]
If we're making this change then let's please bundle it with the move of the DB to the security-advisories repo too.

**Comment by sam-github** [comment]
No objections, but should change after the DB has moved out of this repo, which is close to done.

**Comment by lirantal** [comment]
On the call now with Sam, reviewing this issue and agreed on:
1. Name change - are we all agreeing on the name? Ecosystem Security WG?
2. Moving existing DB of vulns (both core and ecosystem) to security-advisories per planned

@DanielRuf maybe you'd fancy completing the work of moving the DB around to a new repo? I believe Vladimir already started this and it just needs finishing. @vdeturckheim ?

**Comment by DanielRuf** [comment]
> @DanielRuf maybe you'd fancy completing the work of moving the DB around to a new repo?

What are the exact steps that I have to do? =)
The DB is just https://github.com/nodejs/security-wg/tree/master/vuln or more?

**Comment by lirantal** [comment]
@DanielRuf Yep that's the DB but as it seems with the discussion in the recent days going in Marcin's issue and on the Slack that we want to retire the DB entirely (https://github.com/nodejs/security-wg/issues/662#issuecomment-641132031) and so moving it out anyway doesn't make sense or worth the effort at this point.

**Comment by fraxken** [comment]
👋

Is this topic still relevant? Maybe we should add the agenda label to discuss it quickly (cc @RafaelGSS).

**Comment by RafaelGSS** [comment]
Is it still a valid suggestion? Honestly, I wasn't around to understand the whole context. We can add to the agenda and discuss, but since it's pretty old I don't see a good reason to rename the repository.

**Comment by lirantal** [comment]
So, previously, we wanted to change the working group name to Ecosystem Security WG (the 'ecosystem' is the added one) because it was focused on ecosystem vulnerabilities. This isn't the case today so I'd defer this issue to close for now until we work out proper charter.

**Comment by RafaelGSS** [comment]
Thank you @lirantal
