### ISSUE TITLE
Ecosystem triage team membership review

### ISSUE THREAD

**Issue by MarcinHoppe** [nodejs/security-wg#632]
Before we onboard new members (#614), let's do an annual membership review.

@cjihrig -> responded: leaving.
@dgonzalez -> responded: leaving.
@grnd -> responded: staying.
@karenyavine -> responded: staying.
@lirantal -> responded: staying.
@MarcinHoppe -> responded: staying.
@pxlpnk -> responded: leaving.
@ronperris -> responded: staying.
@sam-github -> responded: staying.
@vdeturckheim -> responded: staying.

Please confirm by posting a comment on this issue if you plan to continue being active in the Ecosystem Security WG triage team. If we don't hear from you we will move you to emeritus as outlined in #302.

**Comment by MarcinHoppe** [comment]
I confirm that I want to remain a member of the triage team.

**Comment by ronperris** [comment]
Remaining.

**Comment by sam-github** [comment]
I am not involved in ecosystem triage per-se, but I think its useful to retain membership, having visibility into nodejs and ecosystem makes it possible for me to notice misfiled issues.

**Comment by pxlpnk** [comment]
I do not have the time at the moment to triage reports. I would like to stay on the WG, but won't be of help on the Triage team at the moment.

**Comment by lirantal** [comment]
Staying

**Comment by vdeturckheim** [comment]
I don't really have time to triage but I'd like to stay to keep an eye on what's going on and help admin the H1 account.

**Comment by karenyavine** [comment]
I'd like to stay :)

**Comment by MarcinHoppe** [comment]
I was able to get in touch with everybody. Next step is move people who voted to leave to emeritus status.

**Comment by MarcinHoppe** [comment]
I created the following issues to offboard members that decided to leave the ecosystem triage team:

- #636 
- #637 
- #638 

I think this issue can be closed now.
