### ISSUE TITLE
Acknowledging documented restrictions on use of info from private security repos

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#64]
@sam-github suggested that people who are listed in https://github.com/nodejs/security-wg/blob/master/processes/security_team_members.md

should acknowledge the restrictions in:

> Node.js security team members are expected to keep all information that they have privileged access to by being on the team completely private to the team. This includes agreeing to not notify anyone outside the team of issues that have not yet been disclosed publicly, including the existence of issues, expectations of upcoming releases, and patching of any issues other than in the process of their work as a member of the security team.

by PR'ing themselves into the list.  This makes sense. 

As a bootstrap for those already part of the lists, please acknowledge as a comment in this issue.

@ChALkeR - Сковорода Никита Андреевич
@Fishrock123 - Jeremiah Senkpiel
@MylesBorins - Myles Borins
@Trott - Rich Trott
@addaleax - Anna Henningsen
@bnoordhuis - Ben Noordhuis
@cjihrig - Colin Ihrig
@dougwilson - Douglas Wilson
@ejratl - Emily Ratliff
@evanlucas - Evan Lucas
@evilpacket - Adam Baldwin
@grnd - Danny Grander
@indutny - Fedor Indutny
@jasnell - James M Snell
@jbergstroem - Johan Bergström
@joaocgreis - João Reis
@joshgav - Josh Gavant
@mhdawson - Michael Dawson
@mscdex - Brian White
@ofrobots - Ali Ijaz Sheikh
@rvagg - Rod Vagg
@saghul - Saúl Ibarra Corretgé
@sam-github - Sam Roberts
@shigeki - Shigeki Ohtsu
@targos - Michaël Zasso
@thefourtheye - Sakthipriyan Vairamani
@trevnorris - Trevor Norris

[EDITED by @trott: formatting of text to be acknowledged for legibility--no content change, just format)

**Comment by mhdawson** [comment]
I acknowledge.

**Comment by cjihrig** [comment]
ACK

**Comment by jasnell** [comment]
I acknowledge

**Comment by shigeki** [comment]
I acknowledge.

**Comment by bnoordhuis** [comment]
ack

> expectations of upcoming releases

That's somewhat unspecific.  What does it mean?

**Comment by evanlucas** [comment]
I acknowledge

**Comment by targos** [comment]
I acknowledge.

**Comment by MylesBorins** [comment]
I acknowledge

**Comment by joaocgreis** [comment]
I acknowledge.

**Comment by evilpacket** [comment]
I acknowledge.

**Comment by addaleax** [comment]
I acknowledge.

**Comment by dougwilson** [comment]
I acknowledge.

**Comment by ofrobots** [comment]
I acknowledge.

**Comment by Trott** [comment]
ack

**Comment by mcollina** [comment]
I acknowledge as being an org owner. I do not have access to node-private.

**Comment by joshgav** [comment]
ack

**Comment by rvagg** [comment]
ack **but** I'd really like this wording to be amended to explicitly include the option to include outsiders as long as the private security groups agrees (in practice it'd be -- "I'd like to share with X, does anyone disagree?"). I can't say enough how hard it can be to get proper feedback on many security problems, their fixes and the handling process. There have been instances where having external help in reviewing or getting expert feedback has been essential. The security group is too small and not engaged enough right now and this restriction is just going to make it more difficult for the person trying to address a security concern and/or shepherding a fix out and will impact our ability to ensure quality fixes (we don't have a solid track record here, there are many instances of follow-up patches to our security fixes once the broader collaborator group gets to review).

**Comment by grnd** [comment]
Ack

**Comment by vdeturckheim** [comment]
I think this is good to close at this point.
