### ISSUE TITLE
Changing WG meeting time

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#642]
It seems we are not able to hold meetings on the current time spot anymore.

Should we:
* switch to another date and keep it monthly
* move to a meeting every other month
* move to a meetingless WG with a fully async system
* something else?

Wdyt @nodejs/security-wg ?

**Comment by MarcinHoppe** [comment]
Is this purely a scheduling problem, or the agenda items do not warrant getting together on a monthly basis? I feel this could impact the preferred option.

**Comment by vdeturckheim** [comment]
I think currenlty it is mostly a scheduling issue

**Comment by MarcinHoppe** [comment]
Then I'd vote for option 1 or 2.

**Comment by SomeoneWeird** [comment]
Out of curiosity, what would option 3 look like? I've never been able to join a meeting as the current slot puts it at 4am for me, slightly out of reach of both staying up late and getting up early to join.

**Comment by vdeturckheim** [comment]
@SomeoneWeird I think it would mean we find a way to replace everything the monthly meeting is for by Github interactions. And if needed we would schedule ad-hoc meeting on specific topics :)

**Comment by sam-github** [comment]
I'm fine with finding another time, option 1. monday+friday are good days to avoid, I suspect that's one problem with current time, too close to weekends.

option 2:  think if its every 2 months that when one gets missed, it ends up every 4 months, which is not  frequent enough to discuss anything current. Might be OK for deciding strategic directions, if that's needed, but essentially means everything gets done async.

I'm OK with async, option 3, as well.

I don't know what other options there are :-)/

**Comment by mhdawson** [comment]
I'd agreed with @sam-github, anything less frequent than once a month will lead to long gaps if even a single meeting is missed.

**Comment by MarcinHoppe** [comment]
One option I'd like to propose it to alternate meeting times month to month to accommodate different timezones.

**Comment by sam-github** [comment]
I'm easily available, M-F, 9-5, north american EST. I'm also available after that thru the evening on some days (and while COVID restrictions are in place, basically every evening, but that is hopefully not long term).

So, folks with more restricted schedules or with more pre-existing meetings, what are the times that work for you?

**Comment by esarafianou** [comment]
@nodejs/security-wg We discussed in the meeting yesterday to find another time for our monthly meetings so that more people can attend. I created a Doodle poll to get your availability for a new day/time. Don't pay attention to the dates of the Doodle, just the day and time. Could you please fill it out? https://doodle.com/poll/uh2teyuuvim4bn67

**Comment by lirantal** [comment]
Thanks for pinging on this @esarafianou, I added my timelines too on that one.

**Comment by DanielRuf** [comment]
Short question, is the displayed time different per timezone or uses Doodle a specific timezone?
Because I have never used it with other people from other timezones and I do not know if the displayed time is my local time and you see other numbers.

<img width="158" alt="Bildschirmfoto 2021-01-31 um 12 33 53" src="https://user-images.githubusercontent.com/827205/106382549-9f27fa00-63c0-11eb-88c2-17d78caf20b5.png">

**Comment by esarafianou** [comment]
@DanielRuf the times displayed are in your local timezone.

**Comment by esarafianou** [comment]
Based on the poll and the last meeting decisions, the Security WG meeting day/time is changing to the following:

We will alternate the meeting days/times between:

- Mondays, 4pm UTC
- Thursdays, 2pm UTC

This means that the meetings will re-occur every month. Every two months the meeting will be on Thursday, 2pm UTC. For the in-between months, the meeting will be on Monday, 4pm UTC.

This goes in effect this week, with the meeting happening on Thursday, March 25th, 2pm UTC.
