### ISSUE TITLE
Ask Me Anything with OpenJS Foundation?

### ISSUE THREAD

**Issue by RRomoff** [nodejs/security-wg#655]
Hello All,
The OpenJS Foundation has been doing monthly AMAs with projects. These AMAs take place on the first Wednesday of the month at 9 am PT. I'd like to invite the Node.js Security WG to participate in the next AMA (June 3rd at 9 am PT).

Liran recommended I open an issue to get participants. So far, Liran has volunteered to join the AMA. We need 2-3 more panelists and a volunteer to moderate the AMA. 

Please let me know if there are other folks interested in participating. I'm hoping to get the panel locked by end of the week so we can start full promotion.

Here are some other AMAs we've done-
NodeRed: https://www.youtube.com/watch?v=gGr1SX7nxfw
Node.js TSC:  https://www.youtube.com/watch?v=aq4qW_y29h8

**Comment by lirantal** [comment]
would be amazing to get a maintainer on the panel as well, one that we've worked with on some security reports, so that there will be that kind of representation of thoughts too. What do you think? need to reach out soon to those folks if so :)

**Comment by MarcinHoppe** [comment]
Having a maintainer and a security researcher would give us an even more complete perspective, I think.

**Comment by RRomoff** [comment]
The purpose of the AMA is to tell the community what the Node.js WG does, and why it's important and what is being worked on. It would be great to have maintainer and researcher perspectives, are those folks on the WG? What's the best way to get invites out?

**Comment by MarcinHoppe** [comment]
I will also be very happy to participate.

**Comment by mhdawson** [comment]
I'd be willing to participate, but would give preference to the more active members.

**Comment by RRomoff** [comment]
As of right now, we have three participants. Does anyone care to moderate?  If we could get one more, that be great, but three is also a good number.  I'll be sending a calendar invite and an email to get us organized. If anyone else is interested in participating, please let me know.

**Comment by lirantal** [comment]
Michael won't be able to make it, so chiming here again in case anybody wants to join the AMA...
At the moment we're just Marcin and myself.

**Comment by MarcinHoppe** [comment]
The AMA has been put on hold for the time being due to the US protests.

**Comment by fraxken** [comment]
I close the issue considering the dates. Feel free to open a new issue if there is a new AMA where you want to invite the WG members.
