### ISSUE TITLE
Nominate Eva Sarafianou to the triage team

### ISSUE THREAD

**Issue by MarcinHoppe** [nodejs/security-wg#657]
Hi @nodejs/security-wg

I would like to nominate Eva Sarafianou (@esarafianou) to the triage team.

Eva is a product security engineer at Auth0. She brings tons of experience with vulnerability management and JavaScript security and I am confident she will be a great asset to the team.

I can onboard Eva to our processes.

**Comment by vdeturckheim** [comment]
+1 LGTM!

**Comment by lirantal** [comment]
+1 here too

**Comment by sam-github** [comment]
+1 LGTM

**Comment by sam-github** [comment]
@lirantal and @sam-github  discussed in wg meeting, we've no objections, and no one else has had any objects.

**Comment by MarcinHoppe** [comment]
Great! I will move to onboarding @esarafianou and we will close this issue with a PR adding her to the WG.
