### ISSUE TITLE
offboarding sam-github

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#663]
Hi folks, I won't have so much time to participate in the WG (and honestly, haven't had for a while), so I'm going to offboard myself. Thanks for all the hard work you all do.

Cheers,
Sam

## Revoking Access to Confidential Systems

The following is a check-list of actions to be taken upon departure of users from the Security WG (either voluntarily or due to inactivity as described above):
* [x] Remove user from [Repo README](https://github.com/nodejs/security-wg/blob/master/README.md), [Triage Team](https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md)
* [x] Remove membership from [Node.js WG GitHub Team](https://github.com/orgs/nodejs/teams/security-wg)
* [x] Remove user from [HackerOne platform](hackerone.com/nodejs-ecosystem)
* [x] Revoke any user-specific access tokens from HackerOne platform
* [ ] Remove user access from private team channels in slack (nodejs-security-wg.slack.com)

**Comment by sam-github** [comment]
I did things in the wrong order, I left the nodejs-ecosystem program, and now I can't revoke my API token! Can someone do that for me, please? Its the one called `sam-github`.

**Comment by sam-github** [comment]
Can be closed once the api token is removed.

**Comment by lirantal** [comment]
@sam-github I removed the token now.
