### ISSUE TITLE
Kick off meeting Core triage team

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#67]
As discussed in last [WG meeting](https://github.com/nodejs/security-wg/pull/65/files#diff-f7ce60c033d98d56c49b614d7db03a2dR57), we need to set up a meeting to handover the HackerOne Organization to the core triage team:

@bnoordhuis
@indutny 
@rvagg 
@jasnell 
@shigeki 
@MylesBorins 

Are you available on Wednesday 15 NOV 2017 at 19:00 UTC ([other timezones](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Core+triage+team+meeting&iso=20171115T19&p1=1440)) ?

Alternative dates might be Monday 20 NOV or Tuesday 21 NOV at the same time.

**Comment by bnoordhuis** [comment]
I don't have evenings available for the foreseeable future.  What needs to be handed off and can it be done in writing?

**Comment by rvagg** [comment]
I'd prefer not to add a 6am to my calendar if possible

**Comment by vdeturckheim** [comment]
@rvagg @bnoordhuis the meeting was mostly to demo HackerOne to the whole team. If that sounds better, I will add you all to the organization so you can get familliar with it and I can answer questions you might have in an issue.

**Comment by bnoordhuis** [comment]
Sounds good, thanks.

**Comment by jasnell** [comment]
That time works for me. I can do later on that day, or even later in the evening to better accommodate those in non-US timezones. Please do send out a calendar invite once it is scheduled or I will be quite likely to miss it.

**Comment by vdeturckheim** [comment]
@jasnell If you're available tonight, let's do a hangout together so I show you the HackerOne interface. I'll send you an invite right now. If this is a too short notice let's do that next week.

**Comment by vdeturckheim** [comment]
Closed in favor of #103
