### ISSUE TITLE
Self-nomination to H1 triage

### ISSUE THREAD

**Issue by ChALkeR** [nodejs/security-wg#673]
I would like to help triage at least some issues on H1, more specifically:
 * I want to be able to invite people to issues (especially the ones I reported myself) to avoid having to disturb everyone.
 * I want to take a look at the ecosystem impact of certain issues before those are disclosed publically.
 * Perhaps occasional issue confirmation.

I can't guarantee a hard commitment there though.

**Comment by MarcinHoppe** [comment]
👍 from me.

**Comment by DanielRuf** [comment]
:+1: from me, so far I saw very helpful contributions

**Comment by mcollina** [comment]
+1

**Comment by ChALkeR** [comment]
What should be the next steps?

**Comment by MarcinHoppe** [comment]
I think we got enough +1s to proceed with onboarding.

Can you submit a PR similar to #659?

**Comment by mhdawson** [comment]
+1

**Comment by fraxken** [comment]
Hello 👋 @ChALkeR. Friendly ping to know if we can close this issue?

**Comment by mhdawson** [comment]
I think we can close this as the ecosystem program was would down. @ChALkeR let me know if that was not the right thing to do.
