### ISSUE TITLE
Nominate GENTILHOMME Thomas as member of the WG

### ISSUE THREAD

**Issue by fraxken** [nodejs/security-wg#678]
Hi,

I would like to nominate myself to the Security WG to help as much as possible.

I don't necessarily have a big security background, and I also don't work in the security area. I have been working with Node.js for over six years now and have been very actively involved in various security subjects for the past 1-2 years. I work as a freelancer and therefore I am now forced to deal on a daily basis with various security matters.

I'm also working on a free open-source [monitoring solution](https://github.com/SlimIO/Governance) written in Node.js where i manage more than one hundreds Node.js repo (packages, API, CLI, N-API addons etc). So I'm very invested in the ecosystem and very concerned about various safety issues.

Some tools I've recently created:
- https://github.com/ES-Community/nsecure
- https://github.com/fraxken/js-x-ray (SAST scanner created for Nsecure, but which is gradually becoming an independent project)
- https://github.com/SlimIO/Security (HTML & PDF Security report that use Nsecure API under the hood)

I really enjoy working on these projects, and I want to put a lot more effort into improving the ecosystem (as much as possible with my skills). I have been observing the work of the group for a while now and have always wished I could find my own way to contribute to Node.js.

And I think getting involved in this WG will be a great start.

Sorry to write a novel ^^. I wanted to provide as much context as possible on me and why i wanted to be part of this group :)

Best Regards,
Thomas

**Comment by mhdawson** [comment]
+1

**Comment by vdeturckheim** [comment]
Closing as of https://github.com/nodejs/security-wg/pull/685
