### ISSUE TITLE
at nodejs/security has no description

### ISSUE THREAD

**Issue by sam-github** [nodejs/security-wg#7]
@nodejs/security the github at-completion lists this alias with no description, it should probably have one that describes its purpose.

Is it for members of the working group? Or to notify people of possible security issues? I would think not the latter, because that's private, and best handled by email.

**Comment by sam-github** [comment]
@cjihrig I don't have permissions to add descriptions to teams, perhaps you do?

https://github.com/orgs/nodejs/teams?utf8=%E2%9C%93&query=sec

![sec-alias-no-description](https://cloud.githubusercontent.com/assets/17607/21948790/2a58452e-d9a2-11e6-8367-9f7d25d6bb4a.png)

I think the @nodejs/security team description would be "Reviewers of private security vulnerability reports".

**Comment by cjihrig** [comment]
I added a description - Users handling security reviews and patches
