### ISSUE TITLE
Invalid cvss vector string

### ISSUE THREAD

**Issue by dimay7** [nodejs/security-wg#703]
NSWG-ECO-443, NSWG-ECO-444, NSWG-ECO-445, NSWG-ECO-446 & NSWG-ECO-472 contain `AV`, `C` and `AC` with value `U`  which is invalid for those keys

**Comment by lirantal** [comment]
Thanks for the find @dimay7 
Fixed all of these in the above PRs. I'll merge them in a few days if you don't find anything particular standing out there about them.

**Comment by fraxken** [comment]
I close the issue as it seems resolved.

**Comment by dimay7** [comment]
Thanks @lirantal!!
