### ISSUE TITLE
Add more automation around sending of security alerts

### ISSUE THREAD

**Issue by maclover7** [nodejs/security-wg#72]
There may already be a thing that does this and I'm missing it, but is there a tool that helps with generating and sending the security alerts in the google group, and then generates the post for the nodejs.org? If not, I am happy to try and with this.

cc @mhdawson

**Comment by mhdawson** [comment]
Most of the work is getting agreement on the content of the 2 posts  Once we have the draft in the security issue it would helpful if we had something that would spit out the PR and the cut/paste for the google group (although not sure that is possible as they have their own editor).  

@maclover7 if you want to look if we can automate a post or the content for a google group post I'd be happy to discuss the flow of what I've had to do.

**Comment by dgonzalez** [comment]
https://github.com/dgonzalez/gammaray -> this might help. It uses the vuln database to scan node apps... it does not send alerts but allows to match the content on https://github.com/nodejs/security-wg/tree/master/vuln/npm with a given application.

**Comment by sam-github** [comment]
I've prepared a couple of these posts. Its timeconsuming, but mostly involves creation of correct and readable descriptions of vulnerabilitites. It doesn't look amenable to automation.

With that caveat, the process is described at https://github.com/nodejs/security-wg/blob/master/processes/security_release_process.md, and if anyone does come up with some ideas for automation of parts of it, they would gratefully be accepted!
