### ISSUE TITLE
Third party triage team membership

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#73]
As discussed in [our last meeting](https://github.com/nodejs/security-wg/blob/master/meetings/2017-11-30.md) it is time to kick off the triage team.

The job is described in [the soon-to-be-merged process document](https://github.com/nodejs/security-wg/pull/57).

Please state your interest in this issue. I plan to open a vote in another issue to have this team validated by the WG early next week (but anyone is still welcome to state interest after this date of courses).

As of [OCT 12th meeting](https://github.com/sam-github/security-wg/commit/63de78e2c5a24dab2598c8ece02e844a6ffc27e5#diff-9aedc283b5a59c313c918f23bd775ad3R66), pinging @brycebaril and @mgalexander.

Also, @cjihrig, @sam-github and I are already member of the HackerOne team. Let's consider it as an will to be a member of this team unless stated otherwise.

(edit): this is on: https://nodejs.org/en/security/#reporting-a-bug-in-a-third-party-module

(edit): Also @reedloden from HackerOne is currenlty a member of the organization. He offered to stay a bit until we are certain we handle the platform well. I think this is a good opportunity for us!

**Comment by bengl** [comment]
I'm interesting in helping with third party triage.

**Comment by vdeturckheim** [comment]
I will PR current membership batch later today.

cc @nodejs/security-wg anyone else?!

**Comment by brycebaril** [comment]
I'll help out best I can!

**Comment by grnd** [comment]
Hello team! 
I'd love to take part in the triage

**Comment by vdeturckheim** [comment]
Awesome @grnd , please open a PR to add yourself in https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md

**Comment by lirantal** [comment]
Added Danny and myself to the triage team: https://github.com/nodejs/security-wg/pull/78

**Comment by grnd** [comment]
Thanks @vdeturckheim, @lirantal 

PR: https://github.com/nodejs/security-wg/pull/81

**Comment by jasnell** [comment]
I am interested in participating in this group. Note that I am also part of the node.js core triage team as well.

**Comment by vdeturckheim** [comment]
Hey @jasnell . I'd love to have you in this team! can you PR yoursefl to https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md#the-triage-team ?

**Comment by dgonzalez** [comment]
I am interested in participating in this group.

**Comment by sam-github** [comment]
I think the team was formed, and there is a process for joining, so this can be closed now. Please reopen if that is not the case.
