### ISSUE TITLE
Found a critical Vulnerability in a 3rd party module ?

### ISSUE THREAD

**Issue by abhisek3122** [nodejs/security-wg#742]
Hackerone program is disabled, How to report?

**Comment by Trott** [comment]
We do not have an ecosystem vulnerability program anymore. You might also choose a third-party service like https://snyk.io/vulnerability-disclosure/. And of course you can report the issue directly to the module maintainers.

**Comment by adam-nygate** [comment]
Hi @abhisek3122, happy to accept the disclosure over at https://huntr.dev and to work with the maintainer to prepare a patch for it.

**Comment by abhisek3122** [comment]
I have submitted a form for the vulnerability
