### ISSUE TITLE
how to report an issue without using hackerone?

### ISSUE THREAD

**Issue by sirdarckcat** [nodejs/security-wg#769]
hi

we have an issue we want to report to node.js but we won't be able to submit it through hackerone.com (Node.js enforces a Signal Requirement, and requires agreeing to HackerOne https://www.hackerone.com/disclosure-guidelines which we won't agree to).

please document an alternate reporting path.

**Comment by sirdarckcat** [comment]
https://github.com/nodejs/security-wg/blob/main/processes/responsible_disclosure_template.md says:
```
One may also directly contact the project’s maintainers, but through the HackerOne program the Security WG members will take care of triaging the vulnerability and invite project maintainers to participate in the report.
```

There's also an email at https://nodejs.org/.well-known/security.txt

We'll try both of those.

**Comment by Trott** [comment]
Did you report an issue? I haven't seen anything come in during the last few days. Did you get any kind of response (automated or otherwise)?

**Comment by sirdarckcat** [comment]
We received the following auto-response.

```
Thank you for submitting a potential vulnerability to the Node.js Vulnerability Disclosure Program. We are HackerOne and we partner with Node.js to manage and track submissions.

In order to complete the submission of this report, please use the link below. Before you submit the report please read the HackerOne Privacy Policy. By clicking on the link below, you confirm that you have read and agree to the terms of the Policy.

Please be aware that this link will be valid for a period of 60 days. After this date the link and report that you have submitted will be deleted.

ACTION REQUIRED: Submit Vulnerability Report

If you did not intend to submit a vulnerability report or if you think you have received this message in error, please contact us at support@hackerone.com to prevent further email notifications regarding this issue.
```

Please provide an alternate reporting path.

**Comment by sirdarckcat** [comment]
Note we also contacted a couple NodeJS maintainers, but didn't receive a response (and also, we don't know if they even read the emails on github).

**Comment by lirantal** [comment]
@sirdarckcat if you need to submit to the Node.js project use this program on HackerOne: https://hackerone.com/nodejs

**Comment by DanielRuf** [comment]
@lirantal see the first comment:

> Node.js enforces a Signal Requirement, and requires agreeing to HackerOne https://www.hackerone.com/disclosure-guidelines which we won't agree to

**Comment by lirantal** [comment]
Oh that's right up there on the top comment which I completely drove-by and focused on the last set.

Well in general, this is better taken in nodejs/node repo which deals with the core Node.js project.
That said, we can try and pull some folks here. I don't think contacting any Node.js core contributor directly is the way to go.

Let's revisit that signal requirement thing. What's the actual issue there from your end @sirdarckcat ?
From [the hackerone docs about signal requirements](https://docs.hackerone.com/programs/signal-requirements.html#:~:text=Signal%20Requirements%20enable%20a%20program,submit%20reports%20to%20the%20program.&text=This%20means%20that%20a%20hacker's,Program%20%3E%20Hacker%20Management%20%3E%20Submission.) this seems to be more of a setting on the program side of things, no?

**Comment by sirdarckcat** [comment]
Hi!

Thats a setting on your program, yes.

We also won't be able to agree to Hackerone's vulnerability disclosure policy. The code of conduct and finder terms of service disallow the finder from making a vulnerability public without permission, and is different from our vulnerability disclosure policy.

Anyway, we can also just publicly report it on github.com/nodejs/node if that's what you meant here:
> this is better taken in nodejs/node repo which deals with the core Node.js project

**Comment by DanielRuf** [comment]
> Anyway, we can also just publicly report it on github.com/nodejs/node if that's what you meant here:

No, please don't post it publicly. There are rules regarding the responsible disclosure.

**Comment by DanielRuf** [comment]
> That said, we can try and pull some folks here. I don't think contacting any Node.js core contributor directly is the way to go.

That would be great if you could coordinate this @lirantal

**Comment by mcollina** [comment]
Here are our current settings:

![Screenshot 2021-09-29 at 15 59 29](https://user-images.githubusercontent.com/52195/135283559-0458ff8d-e77e-4850-8f52-bf789d4ce690.png)

We already receive too many invalid reports, so I'm happy to lower that signal.

---

> We also won't be able to agree to Hackerone's vulnerability disclosure policy. The code of conduct and finder terms of service disallow the finder from making a vulnerability public without permission, and is different from our vulnerability disclosure policy.

I'm sorry but I do not understand this. We worked with Google Project Zero in the past and their 90 days timeline, so there is no real problem there from our end. HackerOne is mainly a tool to manage/organize the work and award the bounties.

If for whatever reason you are not comfortable in sending them to HackerOne, you can send them to me. I'm the one doing triaging anyway.

**Comment by fraxken** [comment]
I consider this issue to be solved by @mcollina comment so I'm closing the issue.
