### ISSUE TITLE
Outdated information on nodejs.org Security page

### ISSUE THREAD

**Issue by rcowsill** [nodejs/security-wg#775]
The [nodejs.org Security page](https://nodejs.org/en/security/) has outdated information on [reporting vulnerabilities in third party modules](https://nodejs.org/en/security/#reporting-a-bug-in-a-third-party-module):

>Security bugs in third party modules should be reported to their respective maintainers _and should also be coordinated through the Node.js Ecosystem Security Team via HackerOne._

The [Node.js Ecosystem program](https://hackerone.com/nodejs-ecosystem?type=team) is no longer accepting reports as of October 2021.

The [nodejs program](https://hackerone.com/nodejs?type=team) page has been updated with new instructions for reporting a bug in a third party module. The corresponding change hasn't been made on the nodejs.org Security page yet. Does this just require an issue and PR over at https://github.com/nodejs/nodejs.org?

Also, do the `processes/third_party_*` docs in this repo need updating, or should they be removed?

**Comment by Trott** [comment]
Does https://github.com/nodejs/node/blob/b323cec78f713bc113be7f6030d787804a9af5a0/SECURITY.md#reporting-a-bug-in-a-third-party-module likewise need to be updated?

**Comment by rcowsill** [comment]
> Does https://github.com/nodejs/node/blob/b323cec78f713bc113be7f6030d787804a9af5a0/SECURITY.md#reporting-a-bug-in-a-third-party-module likewise need to be updated?

Yes, it has the same outdated content as [nodejs.org/en/security](https://nodejs.org/en/security/#reporting-a-bug-in-a-third-party-module). 

This section from the nodejs HackerOne project seems like a good replacement:

> ## Reporting a Bug in a third party module
> 
> Third-party modules are no longer handled by the Node.js [security-group](https://github.com/nodejs/security-wg). Vulnerabilities in npm packages should be reported directly to the package maintainers. We strongly advise doing this privately. You can find contact information about package maintainers with npm owner ls <package-name>. If the source code is hosted on GitHub please refer to the repository's Security Policy.

**Comment by arhart** [comment]
@rcowsill @Trott Is there any action left to be taken on this, other than closing?
