### ISSUE TITLE
transfer of primordials package

### ISSUE THREAD

**Issue by DanielRuf** [nodejs/security-wg#780]
@ljharb wants to provide a robust version of the primordials package and asked me to transfer the package to him.

For those who are not aware, primordials is a core package of Node and in many cases people face an issue where their Nodejs application throws an error, that it does not exists.

See also https://stackoverflow.com/search?q=primordials+is+not+defined and https://github.com/search?q=primordials+is+missing&type=issues for relevant bug reports.

I have picked up this package name to prevent abuse since some try to install it manually (like node-gyp, node-waf, fs and so on which are often just security holding packages from npm or me).

To document the transfer and finish it, this issue is created by me. So everyone is aware of it.

Another relevant discussion probably: https://github.com/nodejs/TSC/issues/1104

**Comment by ljharb** [comment]
Thanks Daniel! You asked me to say “RYFyC68HPYCjLC5q“ in this issue. My npm is https://npmjs.com/~ljharb

**Comment by DanielRuf** [comment]
I've invited you now as additional maintainer.
You can remove me then.

![image](https://user-images.githubusercontent.com/827205/149803019-563cc711-aac1-4990-b01f-2726f6b59220.png)

**Comment by ljharb** [comment]
Thanks!

**Comment by DanielRuf** [comment]
Transfer done. Closing as resolved.

Thank you very much for taking care of `primordials`.
Have a nice day!
