### ISSUE TITLE
Node.js Security WG - Reactivating meetings

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#793]
Hello folks!

I was talking with @mhdawson and @UlisesGascon in the last week and we are planning to back with the Security WG Meetings.
The initiative for the Permission Model (#791) came up with a few points that would be worth it to discuss in a meeting:

- Document the current security model
- Document threats
- Design the Permission Model

And of course, any other initiative that you think would be worth it to discuss, just add to the calendar. 

For those who want to participate, what's the best time? The last security-wg meeting was scheduled in https://nodejs.org/calendar: `12:00 PM ~ 01:00 PM UTC`. This value suits me.

cc: @nodejs/security

**Comment by vdeturckheim** [comment]
Lgtm!

**Comment by RafaelGSS** [comment]
What about meeting every 15 days?

**Comment by vdeturckheim** [comment]
I'd say as long as we have an agenda for each meeting, sounds good.

**Comment by mhdawson** [comment]
12:00 PM UTC is 8AM my time so I would not be able to make it.

This is the last one I can find - https://github.com/nodejs/security-wg/issues?q=is%3Aissue+is%3Aclosed which was 2PM UTC?

Having said that I don't necessary want/need to be at all the meetings so whatever time works for the largest group makes sense to me and I can participate async.

@RafaelGSS I'm assuming you can act as the Chair/stream the meetings. Let me know if that is correct and I'll start the process of getting you access to the Youtube/zoom so you can do that.

**Comment by RafaelGSS** [comment]
> @RafaelGSS I'm assuming you can act as the Chair/stream the meetings. Let me know if that is correct and I'll start the process of getting you access to the Youtube/zoom so you can do that.

Yes, I can do that if no objections.

**Comment by UlisesGascon** [comment]
Thanks @RafaelGSS! 

2PM UTC works for me better than 12:00 PM UTC, but I can adapt :)

**Comment by mhdawson** [comment]
Issue to get @RafaelGSS zoom/youtube access so that he can chair/stream meetings - https://github.com/nodejs/admin/issues/684

**Comment by lirantal** [comment]
Looking forward to jump aboard the new train route for the Security WG :-)
Thank you all for bringing these topics back to the table.

**Comment by RafaelGSS** [comment]
All good! https://github.com/nodejs/security-wg/issues/794
