### ISSUE TITLE
Threat Model

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#799]
This issue is just to keep tracking the work we've been doing in the Security WG. We've created a [Threat Model document](https://docs.google.com/document/d/10so8HJdNVYr9q66tyl6caK9s56c4ucNIUs_J1BzjZLo/edit?usp=sharing).

The intention of this document is to list all the current threats and their mitigation for each environment using Node.js. _It may change over releases_.
This document was created aiming to provide context on what will/will not be considered a vulnerability in Node.js, targeting Security Researchers.

Normally, the discussion around this document happens in the OpenJS Foundation slack (#nodejs-discussion-security-model). Feel free to contribute.

**Comment by lirantal** [comment]
Thanks for putting that together!

**Comment by facutuesca** [comment]
As a possible reference, [this](https://github.com/osquery/osquery/blob/master/ASSURANCE.md) is how  `osquery`  documents their threat model, along with its considerations for security and the design decisions taken in consequence.

**Comment by RafaelGSS** [comment]
Renaming it as Threat Model as defined in #801

**Comment by lirantal** [comment]
@facutuesca that's some nice work by `osquery`. Thanks for sharing.

**Comment by RafaelGSS** [comment]
Hi folks!

In the last Security WG #822 we've decided to create a separate meeting (next week) to discuss just the Threat Model. The idea is to finish the draft in this meeting and then open a PR for feedback.

I suggest the same time as usual (2 pm UTC) - Monday. For those who want to join, please comment on your preferred email to send the invite. cc: @facutuesca @mhdawson

**Comment by mhdawson** [comment]
I'm on Monday and booked that time the rest of the days, but I could decline what I had accepted for that time on Friday.

**Comment by arhart** [comment]
@RafaelGSS Is that Monday the 22nd? I'm interested. I could also do Friday the 26th, which I think is the day @mhdawson is suggesting.

I currently have other commitments most Thursdays. [This comment](https://github.com/nodejs/security-wg/issues/793#issuecomment-1115170109) proposed meeting every 15 days, which would result in the meeting rotating across days-of-the-week, but it looks like meetings have been being scheduled on Thursdays.

**Comment by RafaelGSS** [comment]
Let's do it Friday. Invite [link](https://calendar.google.com/event?action=TEMPLATE&tmeid=NXNyN3VvMGtkdGNuM2E2Z2dmdnNycmpkdWwgcmFmYWVsLnNpbHZhQG5lYXJmb3JtLmNvbQ&tmsrc=rafael.silva%40nearform.com)
