### ISSUE TITLE
What to do about the request module?

### ISSUE THREAD

**Issue by kanongil** [nodejs/security-wg#805]
I am not a security researcher, but I have discovered what I believe is a security issue in the core logic of the [`request`](https://www.npmjs.com/package/request) module. Since this module has been abandoned, and has no security policy, I am at a loss as to where to report it.

Given that the module still sees 20M weekly downloads, and is part of the active node 14 releases, I don't think it is appropriate to just ignore it.

For reference, this is not the only unhandled security issue, eg. https://github.com/request/request/issues/3412, https://github.com/request/request/issues/3411, https://github.com/request/request/issues/3399, and https://github.com/request/request/issues/3394.

Any suggestions?

**Comment by lirantal** [comment]
@kanongil a large user base might be at risk. While it isn't maintained anymore, it is still advised (my own opinion here) that you should be reaching out to report the vulnerability and hopefully, a fix can still be released if this issue is severe.

**Comment by DanielRuf** [comment]
> has no security policy, I am at a loss as to where to report it.

Afaik Snyk as CNA can support here. Or @lirantal can internally ask the Snyk team if they can help here and how.

https://snyk.io/vulnerability-disclosure/

Alternatively GitHub (who also owns npm) is another CNA which can also address this. There is the "report malware" button on npmjs that you can use to escalate things to GitHub too.

**Comment by kanongil** [comment]
Thanks for the feedback. I will see about approaching Snyk.
