### ISSUE TITLE
OpenJS Foundation Slack channel

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#812]
The README is pointing to an out-of-date link. Besides that, I don't see a #nodejs-security-wg channel in the OpenJS Foundation Slack. I just want to confirm that we don't have a proper channel so I'll create one.

cc: @nodejs/security-wg

**Comment by vdeturckheim** [comment]
Technically, we have a separate older Slack, but it has been pretty inactive recently. I don't mind moving to the OpenJS one :)

**Comment by UlisesGascon** [comment]
+1 to move to the OpenJS

**Comment by fraxken** [comment]
Ok for moving to the OpenJS Slack.

**Comment by RafaelGSS** [comment]
Here we go https://app.slack.com/client/T0K2RM7F0/C03Q9MS3KFB
