### ISSUE TITLE
Definition of what is/is not a vulnerability

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#817]
We have some good discussion/work going on in the Threat Model document - https://docs.google.com/document/d/10so8HJdNVYr9q66tyl6caK9s56c4ucNIUs_J1BzjZLo/edit#.

I think that will take some additional time/work to get it into it's final form with the threats/mitigations etc.

I'd like to see if we can agree on how we can community what is/is not a vulnerability and start using that to address vulnerabilities reported to the project.  In that documented I suggested this as a starting point. There were some suggestion for improvement but I think generally people thought it was a good start.

My goal is to discuss just this part in the issue with the goal of getting to something we can propose to the collaborators/TSC in the near term:

Initial proposal:

Being able to cause a negative outcome in a way that requires control of the elements that are not trusted by Node.js is not considered a vulnerability in Node.js.

Being able to cause the following through control of the elements that Node.js does trust is considered a vulnerability:
* Disclosure or loss of integrity or confidentiality of data protected through the correct use of Node.js APIs
* The availability of the runtime, including the unbounded degradation of its performance

Node.js trusts the developers and infrastructure that runs it. Therefore, it trusts
* The operating system and its configuration, along with everything in the environment accessible to it.
* The code it is asked to run includes JavaScript and native code, even if said code is dynamically loaded
* Inputs are provided to it by the code it is asked to run, as it is the responsibility of the application to perform the required input validations

Node.js does NOT trust

* The remote end of network connections exposed by the use of Node.js APIs, this includes data received through HTTP and HTTP/2.
* The remote end of network connections opened by the runtime through the use of command line options, unless only accessible from the local machine.
* Consumers of data protected through the use of Node.js APIs

In addition to addressing vulnerabilities based on the above, the project works to avoid APIs and internal implementations that make it “easy” for application code to use the APIs incorrectly in a way that results in vulnerabilities within the application code itself. While we don’t consider those vulnerabilities in Node.js itself and will not necessarily issue a CVE we do want them to be reported privately to Node.js first. We often choose to work to improve our APIs based on those reports and issue fixes either in regular or security releases depending on how much of a risk to the community they pose.

**Comment by mhdawson** [comment]
In the meeting [facutuesca](https://github.com/facutuesca) identified that we check headers etc for HTTP but pass the body on without checks related to:

The remote end of network connections exposed by the use of Node.js APIs, this includes data received through HTTP and HTTP/2.

Thinking about it some more, I think the text we have is probably ok, because since we don't parse the body and just send it on, it should not be possible to cause a vulnerability in Node.js itself through the content of the body.

**Comment by mhdawson** [comment]
@nodejs/security-wg, please take a look, comment etc.   Once we have agreement in this group we might have the broader discussion through a PR to https://github.com/nodejs/node/blob/main/SECURITY.md

**Comment by mcollina** [comment]
I reviewed that document and it's great.

**Comment by arhart** [comment]
There is a section in the document marked for removal. Is the intent to move it to another document/discussion to the attack explanation document mentioned at the top or simply remove it?

I'm interested in what the problems running from /tmp are. Typically files belonging to other users can't be modified due to the sticky bit. If it's just the looking for node_modules and package.json, perhaps Windows should be mentioned due to default permissions of root directories which permit any authenticated user to create directories at the root like c:/node_modules.

**Comment by arhart** [comment]
> Being able to cause a negative outcome in a way that requires control of the elements that are not trusted by Node.js is not considered a vulnerability in Node.js.

> Being able to cause the following through control of the elements that Node.js does trust is considered a vulnerability:

Are those backwards?

**Comment by RafaelGSS** [comment]
> There is a section in the document marked for removal. Is the intent to move it to another document/discussion to the attack explanation document mentioned at the top or simply remove it?

It will be moved to a second document. 

> I'm interested in what the problems running from /tmp are. Typically files belonging to other users can't be modified due to the sticky bit. If it's just the looking for node_modules and package.json, perhaps Windows should be mentioned due to default permissions of root directories which permit any authenticated user to create directories at the root like c:/node_modules.

The files _might_ not be modified, but if you run your application in a shared path, which means, that any user in the OS has access to add/remove files, the application will be vulnerable to tampering.

> Are those backwards?

Not sure what you mean. Those statements are valid regardless of the Node.js version.

**Comment by arhart** [comment]
I'd expect it to instead read like this (with my suggested **additions** and ~~subtractions~~ marked):

Being able to cause a negative outcome in a way that requires control of the elements that are ~~not~~ trusted by Node.js is not considered a vulnerability in Node.js.

Being able to cause the following through control of the elements that Node.js does **not** trust is considered a vulnerability:

- Disclosure or loss of integrity or confidentiality of data protected through the correct use of Node.js APIs

- The ~~availability~~ **unavailability** of the runtime, including the unbounded degradation of its performance

**Comment by RafaelGSS** [comment]
Can you make those suggestions in the document? We'll go through it in the Security WG Meeting. Thanks!

**Comment by arhart** [comment]
Thanks! I hadn't realized I could edit the document.

**Comment by arhart** [comment]
> The files might not be modified, but if you run your application in a shared path, which means, that any user in the OS has access to add/remove files, the application will be vulnerable to tampering.

Typically users can't remove files belonging to other users from /tmp. It seems Node.js should permit scripts to be run securely from there if the user takes certain precautions such as creating a package.json file and not requiring files which might be editable by another user.

**Comment by RafaelGSS** [comment]
_/tmp_ is just an example folder of a shared path. The same statement applies to any shared path.

**Comment by mhdawson** [comment]
@RafaelGSS do you think we need more discussion of the short "what is/is not a vuln" within the security working group before we ask for input from the TSC?  Was thinking we'd want to do that as a next step.

**Comment by RafaelGSS** [comment]
> @RafaelGSS do you think we need more discussion of the short "what is/is not a vuln" within the security working group before we ask for input from the TSC? Was thinking we'd want to do that as a next step.

I think we can jump directly to it in tomorrow's meeting and after that, we ask for the TSC input

**Comment by RafaelGSS** [comment]
Concluded in #799
