### ISSUE TITLE
broken links regarding membership

### ISSUE THREAD

**Issue by arhart** [nodejs/security-wg#820]
The README.md links to ./processes/security_team_membership_policy.md, but that link is dead.

processes/wg_offboarding.md points to https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md, but that link is dead.

**Comment by arhart** [comment]
What is the current membership policy?

**Comment by RafaelGSS** [comment]
https://github.com/nodejs/security-wg/blob/main/processes/wg_onboarding.md. Would you like to fix the links?

**Comment by arhart** [comment]
Most of what the old document said isn't relevant now that the [TSC has responsibility for Node.js security](https://github.com/nodejs/security-wg/commit/b342b38ff6f9209b09066406c8a2fb8198cb6127#diff-279b28c12a28e2eb2057da703e14f5dafd7b1ccd5fafdd1b4031a0889bed5952)

I was still expecting to find things like what privileges and responsibilities a member has compared to a non-member who takes interest in the responsibilities listed in the current Charter. https://github.com/nodejs/security-wg/blob/main/processes/wg_offboarding.md covers some of that, although it's hard to tell what's current.

**Comment by RafaelGSS** [comment]
cc: @nodejs/tsc
