### ISSUE TITLE
Secure Open Source Rewards by the Linux Foundation

### ISSUE THREAD

**Issue by DanielRuf** [nodejs/security-wg#826]
Today I was made aware of https://sos.dev

Is this already on our radar and something that can help the Node.js project to get some support from the foundation or are there possible caveats with the OpenJS Foundation?

**Comment by Trott** [comment]
I believe the incoming Node.js project rep on the OpenJS Foundation board is @mcollina. I suspect he would know or could find out. (Or maybe there's no need to go through Matteo and we can ping @rginn on this directly?)

**Comment by Trott** [comment]
Pinging @mcollina @joesepi @rginn in case any of them have context to add (or other folks to ping).

**Comment by mcollina** [comment]
I'm aware of that! Do you think there is anybody that qualifies here? @RafaelGSS likely does not because his work is funded by the very same source.

**Comment by mhdawson** [comment]
We had requested one for one of our collaborators that had helped with a past security release and did get that reward. It's good to keep it in mind as a way to reward non-funded people who make a significant contribution.
