### ISSUE TITLE
Automate updates of all dependencies

### ISSUE THREAD

**Issue by mhdawson** [nodejs/security-wg#828]
PR's like this are really hard to validate and should probably be done through automation.

https://github.com/nodejs/node/pull/44283

@RafaelGSS,@facutuesca is that something you could add to your do list?

https://github.com/nodejs/node/blob/main/doc/contributing/maintaining-root-certs.md)
- [x] [acorn](https://github.com/nodejs/node/tree/main/deps/acorn)
- [x] [ada](https://github.com/nodejs/node/tree/main/deps/ada)
- [x] [base64](https://github.com/nodejs/node/tree/main/deps/base64)
- [x] [brotli](https://github.com/nodejs/node/tree/main/deps/brotli)
- [x] [cares](https://github.com/nodejs/node/tree/main/deps/cares)
- [x] [cjs-module-lexer](https://github.com/nodejs/node/tree/main/deps/cjs-module-lexer)
- [x] [corepack](https://github.com/nodejs/node/tree/main/deps/corepack)
- [x] [googletest](https://github.com/nodejs/node/tree/main/deps/googletest)
- [x] [histogram](https://github.com/nodejs/node/tree/main/deps/histogram)
- [x] [icu-small](https://github.com/nodejs/node/tree/main/deps/icu-small)
- [x] [llhttp](https://github.com/nodejs/node/tree/main/deps/llhttp)
- [x] [nghttp2](https://github.com/nodejs/node/tree/main/deps/nghttp2)
- [x] [ngtcp2](https://github.com/nodejs/node/tree/main/deps/ngtcp2)
- [x] [npm](https://github.com/nodejs/node/tree/main/deps/npm)
- [x] [openssl](https://github.com/nodejs/node/tree/main/deps/openssl)
- [x] [undici](https://github.com/nodejs/node/tree/main/deps/undici)
- [x] [uv](https://github.com/nodejs/node/tree/main/deps/uv)
- [x] [uvwasi](https://github.com/nodejs/node/tree/main/deps/uvwasi)
- [x] [v8](https://github.com/nodejs/node/tree/main/deps/v8)
- [x] [zlib](https://github.com/nodejs/node/tree/main/deps/zlib)
- [x] [root certificate updates](https://github.com/nodejs/node/blob/main/doc/contributing/maintaining-root-certs.md)
- [x] [simdutf](https://github.com/nodejs/node/tree/main/deps/simdutf)
- [x] [minimatch](https://github.com/nodejs/node/tree/main/deps/minimatch)

**Comment by richardlau** [comment]
FYI if you are not aware there is a PR to add a workflow for updating the timezone information: https://github.com/nodejs/node/pull/43988. 

Updating ICU itself is sometimes done together with V8 updates if V8 has bumped ICU versions.

**Comment by mhdawson** [comment]
@richardlau thanks for pointing that out.  

@RafaelGSS, @facutuesca maybe what we should focus on is looking at all of the dependencies, if upates are automated and if not identify which ones should be, and prioritize which ones we'd want to automate. (For example I think we had some discusssions around openSSL, but I think we should track/work on them as an overall program to ensure progress).

If that makes sense to you two I might update the title of this issue to be more about doing it in general for all of the dependencies.

**Comment by RafaelGSS** [comment]
That makes sense to me.

**Comment by facutuesca** [comment]
@mhdawson I'll start working on this (looking at all dependencies and see which ones we could update with a script). Should we change the title of the issue to match that?

**Comment by mhdawson** [comment]
@facutuesca thanks, I've  updated the title.

**Comment by mhdawson** [comment]
I updated the first part of the issue to have the list of deps along with checkboxes. We can track progress there in terms of which ones we have automated versus not so far.

**Comment by mhdawson** [comment]
@BethGriggs if you have any insight/suggestions of what we might need/want to include in the automation based on what you have leared about SALSA, that info would be good to factor into how we do the automation.

**Comment by RafaelGSS** [comment]
I'd go with the ones that are often updated, such as OpenSSL / ICU / zlib

**Comment by richardlau** [comment]
ICU doesn't update very often (about once a year), although we do now have an automated workflow for updating the timezone information (which updates more often) in the ICU data file.

I believe the npm team have their own automation to push npm releases into Node.js core.

**Comment by mhdawson** [comment]
I'd agree that starting with the ones we update most often would be good, and in particular OpenSSL.  I think we have a few starting points. I'd written up https://github.com/nodejs/node/issues/42395 and I think that @RafaelGSS had also done some work on that front as well.

I also think that working on the list for which we have no instructions is also a priority as I see not having that documented as a risk we might get it wrong if we do have to do an update.

**Comment by mhdawson** [comment]
@facutuesca and thanks for the good categorization, it's good to be able to look at the overall list like that.

**Comment by mhdawson** [comment]
@richardlau thanks for pointing that out. I think starting with automating the root cert updates would be a good thing to start with.

**Comment by facutuesca** [comment]
So far we have added:
- acorn: https://github.com/nodejs/node/pull/45357
- base64: https://github.com/nodejs/node/pull/45300
- libuv: https://github.com/nodejs/node/pull/45362

Currently on review:
- OpenSSL: https://github.com/nodejs/node/pull/45605

cc @RafaelGSS

**Comment by mhdawson** [comment]
@facutuesca thanks for progressing this and the update.

**Comment by marco-ippolito** [comment]
we can update the list since nghttp2 is now updated with action with this pr https://github.com/nodejs/node/pull/46700

**Comment by RafaelGSS** [comment]
@marco-ippolito I've selected `llhttp` as completed, but IIRC we use a different major of llhttp on v16/v14, so this automation wouldn't solve all the lines.

Maybe bring this discussion up in the next security-wg call? We might find some ideas.

**Comment by marco-ippolito** [comment]
feel free to edit if I made a mistake
update on dependecy status:


The following dependencies are already updated automatically via a Github action:

- corepack
- eslint
- undici
- cares
- llhttp
- nghttp2
- npm (we have the npm-cli-bot)
- base64
- ada 

The following have a script + docs on how to update them (but no GH Action):

- acorn (no docs)

The following have only docs on how to update them:

- cjs-module-lexer
- icu-small
- ngtcp2 
- OpenSSL
- V8
- zlib

Finally, the following don't have any docs/scripts/etc:

- brotli
- googletest
- histogram
- uv

**Comment by mhdawson** [comment]
@richardlau thanks! Great to see that automated.

**Comment by RafaelGSS** [comment]
UPDATE from #945

- [ ] Create a maintaining-overview.md

**Comment by tniessen** [comment]
> histogram (version header file missing I've opened a [PR](https://github.com/HdrHistogram/HdrHistogram_c/pull/115) to include it)

FWIW, the version header file is not necessary. You can take a look at my approach from https://github.com/nodejs/node/pull/47482, which uses some git magic to figure out if anything changed between the latest upstream version and what's in the node repository. It doesn't actually matter what version is in the node repo. The only difference to https://github.com/nodejs/node/pull/47482 is that for googletest, we follow HEAD, whereas for HdrHistogram_c we probably want to use the latest published release.

**Comment by tniessen** [comment]
There appears to be an issue with nghttp3 updates, see https://github.com/nodejs/node/pull/47576#issuecomment-1537382159.

**Comment by marco-ippolito** [comment]
Last dependency  update automation https://github.com/nodejs/node/pull/48171

**Comment by marco-ippolito** [comment]
and it's merged  🎉🎉🎉🎉🎉🎉 all the dependencies are automated 🥳

**Comment by UlisesGascon** [comment]
Bravo!! 

![](https://media.giphy.com/media/l0MYt5jPR6QX5pnqM/giphy.gif)
