### ISSUE TITLE
Guidance for maintainers on how they should deal with security/vulnerability disclosure

### ISSUE THREAD

**Issue by fraxken** [nodejs/security-wg#832]
Hello team 👋 

I'm opening this issue to initiate a discussion on **how maintainers should deal and receive security/vulnerability disclosure** (as suggested by @lirantal). I am in this position myself as a baby-born maintainer 🐤.

Previously I had set up the template and the badge pointing to the Node.js disclosure program on HackerOne. However, this initiative is no longer relevant, so I have recently started to remove it.

But my contributors and I were wondering if we shouldn't put something else in place. So I made a [tweet](https://twitter.com/fraxken/status/1567595389695451141) today to see if anyone had any recommendations or best practices on the subject.

**Comment by lirantal** [comment]
There's a related/similar effort going onin one of the OpenSSF working groups that I suggest we take a look at first to not duplicate the work or cause further confusion: https://github.com/ossf/package-manager-best-practices/pull/36

Would be great to collaborate on this.

**Comment by lirantal** [comment]
Also noting here that there's the CVD Guide from OpenSSF which is on this spectrum of vulnerability disclosure: https://openssf.org/blog/2022/09/13/coordination-is-key-the-openssfs-cvd-guide-for-finders/

As such, there are:
1. maintainer guide: https://github.com/ossf/oss-vulnerability-guide/blob/main/maintainer-guide.md#readme
2. finder guide: https://github.com/ossf/oss-vulnerability-guide/blob/main/finder-guide.md#readme

**Comment by fraxken** [comment]
Closing as OSSF is definitively the thing to look at, thanks.
