### ISSUE TITLE
Avoid hard code supported versions

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#871]
> Easily, I don't think so. @nodejs/releasers do we have an API with this info?

https://github.com/pkgjs/nv with the `supported` alias.

_Originally posted by @richardlau in https://github.com/nodejs/security-wg/pull/866#discussion_r1087854007_

**Comment by Ranieri93** [comment]
Hey @RafaelGSS, as you suggested  the`nv` package (https://www.npmjs.com/package/@pkgjs/nv) is providing us a convenient way of retrieving node version and they allow multiple choices:
```
all: All node versions
lts_active: Head of LTS and Active major version lines
lts: Head of current LTS lines
active: The newest version in the active but not maintenance mode lines
lts_latest/lts/*: Latest of the LTS lines (lts/* for nvm compatibility)
supported: Head of all maintained lines
DEPRECATED maintained: Head of all maintained lines
current/node: Newest of all maintained lines (node for nvm compatibility)
```
I'm guessing form following the code that the one we need is the `supported` one, which will lead in something like 
`[ '14.21.3', '16.20.0', '18.15.0', '19.8.1' ]` but I'm not sure, so here I am, you know I'm all about dummy questions!

**Comment by RafaelGSS** [comment]
Exactly! `supported`.
