### ISSUE TITLE
Overlap with single-executable effort

### ISSUE THREAD

**Issue by bmeck** [nodejs/security-wg#879]
Per https://github.com/nodejs/security-wg/blob/main/meetings/2023-02-16.md , there is some form of potential overlap where a Windows OS integration might need to add a section to the binary to force certain flags to be always enabled and unable to be disabled, just posting this as a cross reference issue for @nodejs/single-executable .

**Comment by RaisinTen** [comment]
> to force certain flags

By that do we mean having a way to hard code a value for the [`--policy-integrity=sri`](https://nodejs.org/api/cli.html#--policy-integritysri) CLI option into the binary?

**Comment by bmeck** [comment]
@RaisinTen not just those flags, they would need to add another couple flags most likely to enforce policy manifest lookups include a side-car signature file.

**Comment by RaisinTen** [comment]
Okay, it should be possible to make a change to Node.js to read the CLI options from an injected resource on PE files on Windows and process that during startup. I imagine the implementation would have things in common with https://github.com/nodejs/node/pull/45038 which adds initial support for single executable applications. The injection part could be handled by any tool that is capable of adding resources to PE files like resource hacker, postject, LIEF, rcedit, etc.

**Comment by bmeck** [comment]
@RaisinTen great, I can make a PR to mandate needing to have a policy to run and then look at that. CC: @nodejs/loaders I believe this might be a little bit relevant but not directly overlap the effort around having a standardized way of automatically configuring loaders.

**Comment by bmeck** [comment]
single executable apps (SEA) need to figure out how to sign flags or security wg would need to. Right now SEA cannot sign any security flags in a way that will error if they are changed

**Comment by RafaelGSS** [comment]
Alright, this can be a good initiative for next quarter. Adding to the agenda for awareness. Is there any PR/Issue we can get more information about it?

**Comment by RaisinTen** [comment]
The discussion in https://github.com/nodejs/single-executable/issues/72 led to this conclusion, so you'll find more information there.
