### ISSUE TITLE
Improve SecurityWG Scorecard

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#884]
Following https://github.com/nodejs/security-wg/blob/main/tools/ossf_scorecard/report.md + Code Scanning, we have a few security concerns to mitigate in this repository and then improve our score. Let's use this issue to keep track of the progress:

- [x] Token-Permissions
  - .github/workflows/ossf-scorecard-reporting.yml:11
  - > score is 0: topLevel 'contents' permission set to 'write'
Remediation tip: update your workflow using [https://app.stepsecurity.io](https://app.stepsecurity.io/secureworkflow/nodejs/security-wg/ossf-scorecard-reporting.yml/main?enable=permissions)
Click Remediation section below for further remediation help
  - .github/workflows/validate-vulnerability.yml:1
  - > score is 0: no topLevel permission defined
Remediation tip: update your workflow using [https://app.stepsecurity.io](https://app.stepsecurity.io/secureworkflow/nodejs/security-wg/validate-vulnerability.yml/main?enable=permissions)
Click Remediation section below for further remediation hel
- [x] Pinned-Dependencies
  - All `.yml` files.
- [x] SAST Tool
- [ ] Fuzzing
- [x] Code-Review

**Comment by UlisesGascon** [comment]
I am happy to help with some PRs for the tokens and pinned dependencies. Regarding SAST Tool I can enable [CodeQL](https://codeql.github.com/) from the github settings in few minutes.

Regarding fuzzing maybe @fraxken can lead it :)

**Comment by shubham-y** [comment]
I would like to work on this issue

**Comment by RafaelGSS** [comment]
@shubham-y feel free to pick one item from the list and make the PR.

**Comment by varunsh-coder** [comment]
Hi All, I am the founder of StepSecurity. We are developing a few tools like app.stepsecurity.io to simplify developers' work and increase the OpenSSF Scorecard score using automation. Please let me know if I can help in any way. 

I am curious if this issue is only for this repo or to increase the score across nodejs repos?

**Comment by RafaelGSS** [comment]
Currently, only this repo. The plan is to perform this for all the repos in the org.

**Comment by fraxken** [comment]
If we fix remaining issues with token permissions the score will up to ~9.2 

For fuzzing I don't think that applicable here.

We can also improve the score by completing the `CII-Best-Practices` program (but again not sure if that useful for this repository?).

**Comment by UlisesGascon** [comment]
We can explore how `CII-Best-Practices` works in this repo and then try to replicate it for Node and Undici.

I completed the `CII-Best-Practices` for [one of the projects](https://bestpractices.coreinfrastructure.org/en/projects/7143) that I maintain and it is quite long process but super interesting as leads to more opportunities to discuss and improve outside the automatic scoring.

**Comment by RafaelGSS** [comment]
CII-Best-Practices seems interesting.

**Comment by RafaelGSS** [comment]
UPDATE From #961 

| Repository | Commit | Score | Date | Difference | Report Link | StepSecurity Link |
| -- | -- | -- | -- | -- | -- | -- |
| [nodejs/security-wg](https://github.com/nodejs/security-wg) | [436ca24](https://github.com/nodejs/security-wg/commit/436ca245e1dc0be2dbbed75b333a2f2cd162dd32) | 8.2 | 2023-04-24T22:24:57Z | 0.1 | [Full Report](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/security-wg) | [Fix it](https://app.stepsecurity.io/securerepo?repo=nodejs/security-wg) |

**Comment by UlisesGascon** [comment]
UPDATE from #981


| Repository | Commit | Score | Date | Difference | Report Link | StepSecurity Link |
| -- | -- | -- | -- | -- | -- | -- |
| [nodejs/security-wg](https://github.com/nodejs/security-wg) | [b3757f5](https://github.com/nodejs/security-wg/commit/b3757f5868be5175793b6532d11ae4646e87f03d) | 8.2 | 2023-05-09T11:18:48Z | 0 | [Full Report](https://kooltheba.github.io/openssf-scorecard-api-visualizer/#/projects/github.com/nodejs/security-wg/commit/b3757f5868be5175793b6532d11ae4646e87f03d) | [Fix it](https://app.stepsecurity.io/securerepo?repo=nodejs/security-wg) |

**Comment by RafaelGSS** [comment]
I'm closing it since we've achieved our goal of improving the scorecard and now, we're monitoring the score on each meeting.
