### ISSUE TITLE
Workflows failing due repo config

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/security-wg#908]
The [OpenSSF Scoring workflow](https://github.com/nodejs/security-wg/actions/runs/4394801710/jobs/7696070088) is failing has we had changed the rules in the repo to make `main` a protected branch:

```
Pushing changes to database and report
/usr/bin/git push origin --force --no-verify --repo ***github.com/undefined.git
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/nodejs/security-wg
 ! [remote rejected] main -> main (protected branch hook declined)
```

You can check the settings [here](https://github.com/nodejs/security-wg/settings/branch_protection_rules/1866271). I believe that we might make it work by disable the `Do not allow bypassing the above settings` option. But this might impact the scorecard for nodejs/security-wg

**Comment by RafaelGSS** [comment]
Sending a PR should be the best choice

**Comment by UlisesGascon** [comment]
Also the [update core index.js](https://github.com/nodejs/security-wg/actions/runs/4455923946/jobs/7826032561) is failing:

![Captura de pantalla 2023-03-18 a las 15 55 08](https://user-images.githubusercontent.com/5110813/226113556-10e597bf-a2d6-443d-b1b0-5f80c5fee95b.png)


I assume the same will happen with Update Npm Index as it will require write permissions.

**Comment by UlisesGascon** [comment]
Maybe the best option for now is disable the protection to a level that the workflows can commit to main?

**Comment by UlisesGascon** [comment]
As agreed on last meeting, the approach will be to migrate the Github actions with writing permissions to send a Pr with the changes:
- [ ] [Update core index.json](https://github.com/nodejs/security-wg/actions/workflows/update-core-index.yml)
- [ ] [Update npm index.json](https://github.com/nodejs/security-wg/actions/workflows/update-npm-index.yml)
- [ ] [OpenSSF Scoring](https://github.com/nodejs/security-wg/actions/workflows/ossf-scorecard-reporting.yml)

In the meantime I can keep my fork running the actions and I can PR the changes until we make the refactor as my fork does not includes the branch protections. This won't impact negatively in the scorecard as it is a Pr that we will review 😉

**Comment by UlisesGascon** [comment]
I close the issues as the workflows are working fine now 🎉
