### ISSUE TITLE
bug: npm test

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/security-wg#922]
Seems like `npm test` is broken and also is not included in the pipeline.

Full context: https://github.com/nodejs/security-wg/pull/918#issuecomment-1476200545

**Comment by mateonunez** [comment]
Hey @UlisesGascon, I have in locally the fix of the tests and I want to push it as soon as possible.

I just want to know more about the CI:
- Is there a specific OS to run the tests? (Linux, Windows, etc)
- Which version of Node.js?

Thanks!

**Comment by UlisesGascon** [comment]
It will be great to have the matrix strategy for all the active Node.js versions. Regarding OS `ubuntu-latest` will be fine.


Here is a snippet reference, extracted from [here](https://github.com/UlisesGascon/simple-api/blob/main/.github/workflows/check.yml) (as an example from another project)
```
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [14.x, 16.x, 18.x, 19.x]
```

Side note: I will recommend you to use [stepsecurity](https://app.stepsecurity.io/) to secure the Github action easily (pin versions, etc..)

**Comment by mateonunez** [comment]
I think we can close this issue since #931 has been merged.
