### ISSUE TITLE
Recommended text and template for 3rd party module authors

### ISSUE THREAD

**Issue by mcollina** [nodejs/security-wg#93]
As a module author, I would like to recommend my users to leverage https://github.com/nodejs/security-wg/blob/master/processes/third_party_vuln_process.md for receiving security vulnerabilities.

Should we include a list of recommendation for things to be added in the README of those modules?

**Comment by vdeturckheim** [comment]
Great idea @mcollina . 

Also we could imagine a "report a vulnerability" button to add to README, wdyt?

**Comment by mcollina** [comment]
👍  for that.

We should encourage this.

**Comment by reedloden** [comment]
I would recommend having a separate `SECURITY.md` in the top-level of a project providing all the necessary information on how to report an issue. See https://github.com/electron/electron/blob/master/SECURITY.md as an example.

**Comment by lirantal** [comment]
great stuff, had actually pondered exactly that a couple months back (https://twitter.com/liran_tal/status/933322223783424000), and recently me and @grnd shared some ideas related to this too

would love to push this forward

**Comment by mhdawson** [comment]
@lirantal sounds good.

**Comment by cjihrig** [comment]
@vdeturckheim can the security-wg-agenda label be dropped?

**Comment by vdeturckheim** [comment]
Dropping from agenda as I believe this should get into a broader evangelism strategy.

**Comment by lirantal** [comment]
Closing for now that we have the badge and the policy file.

**Comment by mcollina** [comment]
I think this needs to documented and linked in the README of this wg. Otherwise the info is hard to find. Also, a blog post on the foundation medium would be awesome as well.

**Comment by lirantal** [comment]
@mcollina so besides the badge to also have a short section about it?

will try to work out a small post about our initiatives to send over but if someone else beats me to it go for it.
