### ISSUE TITLE
Update Meeting template

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/security-wg#940]
We agreed in the las meeting that we want to include the Scorecard analysis in the meeting agenda templates. I am not very sure where is the  code that generates the Google Docs content but I will be happy to update the agenda template

@mhdawson Can you help me to identify the repo that generates the Google Doc?

**Comment by mhdawson** [comment]
@UlisesGascon I believe this is the template you want to update - https://github.com/nodejs/create-node-meeting-artifacts/blob/main/templates/minutes_base_security-wg
