### ISSUE TITLE
Ecosystem triage severity scale

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/security-wg#98]
Now that we are actually assessing and triaging security issues in the ecosystem, we should probably start to think about a methodology to consider the severity of issues.

Possible directions:
* perform [CIA evaluation](http://whatis.techtarget.com/definition/Confidentiality-integrity-and-availability-CIA) of the vuln 
* take the popularity of the module in account ? (I'm not a big fan of this)
* other things?

cc @lirantal

**Comment by lirantal** [comment]
If we can stick to HackerOne's severity rating which allows you to use [CVSSv3](https://www.first.org/cvss/user-guide) then I think that would be good (see also https://support.hackerone.com/hc/en-us/articles/213421106-How-does-HackerOne-recommend-determining-Severity-)

**Comment by vdeturckheim** [comment]
Right, I believe that is the easiest ready to use framework and since it is already integrated in H1, it is our best call.

@lirantal wdyt we PR https://www.first.org/cvss/user-guide in the 3rd party vuln process?

**Comment by mhdawson** [comment]
+1 for cvss and getting a ref into the def of the vuln process.

**Comment by lirantal** [comment]
@vdeturckheim definitely sounds good, go for it 👍
