### ISSUE TITLE
Access to security tab in Github for key projects

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/security-wg#984]
We discussed in #977 that It will useful for the @nodejs/security members to have access to the Security Alerts for the key repositories that we are tracking in the Scorecard (Undici and Node). 

[Github documentation reference](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-security-and-analysis-settings-for-your-repository#granting-access-to-security-alerts)

**Comment by tniessen** [comment]
As far as I can tell, these alerts so far only show what is reported by the scorecard action, which does not appear to be too useful, as well as known vulnerabilities in some dependencies. Are other kinds of alerts going to show up there, too?
