### ISSUE TITLE
Requirement: Static source code analysis daily or per commit

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/security-wg#985]
Original discussion: https://github.com/nodejs/security-wg/pull/954/files#r1167970826 @mhdawson @tniessen 

> It is SUGGESTED that static source code analysis occur on every commit or at least daily.

Currently this requirement is UNMET

**Comment by tniessen** [comment]
Coverity is supposed to be updated at least daily. However, it currently says that the last build was a month ago. I am still unclear as to how we submit build requests, cc @nodejs/build.

**Comment by richardlau** [comment]
> Coverity is supposed to be updated at least daily. However, it currently says that the last build was a month ago. I am still unclear as to how we submit build requests, cc @nodejs/build.

[node-daily-coverity](https://ci.nodejs.org/view/Node.js%20Daily/job/node-daily-coverity/) runs the scanning tool daily and submits the results to Coverity. The uploads are being rejected: https://github.com/nodejs/build/issues/3343

**Comment by mhdawson** [comment]
I think the requirement is met, we just need to get coverity going again.
