### ISSUE TITLE
Nominate Ashish Kurmi

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/security-wg#989]
I'd like to nominate Ashish Kurmi (@ashishkurmi) to the Security WG. He has been joining the Security WG meeting very often and helping a lot with the Scorecard action.

I've sent him a message and he's interested in participating as a member.

**Comment by mhdawson** [comment]
+1

**Comment by UlisesGascon** [comment]
+1 🎉

**Comment by fraxken** [comment]
+1
